### ISSUE TITLE
体外OA系统中，激励支付和采购付款增加多银行卡支付功能，并且生成对应的凭证明细

### ISSUE THREAD

**Issue by kingofhawks** [qianlimu/yycoin#405]

**Comment by kingofhawks** [comment]
采购管理-》待财务付款环节，没看到菜单项呢？

**Comment by kingofhawks** [comment]
永银周苏东  10:43:41
这个是指在激励支付里提供多个银行卡支付的行项目
因为体外是用的个人卡，有额度限制，所以有时付款得用多张卡来付
smartman  10:44:07
激励支付，是“激励申请”待支付环节吗？
永银周苏东  10:44:15
对
smartman  10:44:57
采购付款，是这个页面，我看银行卡可以多张呀？

永银周苏东  10:45:36
嗯，采购付款不用管了，就激励那边要修改

**Comment by kingofhawks** [comment]
处理借款申请失败:总借[40.00],总贷[30.00]不等,凭证增加错误

**Comment by kingofhawks** [comment]
多余多张银行卡的情况，凭证和付款单是有多个吗？

**Comment by poseidon-Liang** [comment]
周苏东 9-10 09:41:09
多个银行卡拆分成多个金额，费用项还是累计
周苏东 9-10 09:41:23
具体场景可以让财务列个示例 


UT201809071129459714
UT201809070929455959
这些都可以试
我跟财务打个招呼，今天不要付

**Comment by kingofhawks** [comment]
永银周苏东(70907255)  14:17:34
没问题，在凭证里增加多个银行条目
不要多个凭证，一个凭证里搞定
smartman(2054958070)  14:18:11
一个凭证对应多个付款单？然后每个付款单对应一个银行？
smartman(2054958070)  14:19:41
现在的代码是每个付款银行就对应生成一个凭证，那段代码现在会报错。
永银周苏东(70907255)  14:32:33
那也可以按一个银行对应一个凭证，对应一个付款单
这样更清晰
smartman(2054958070)  14:32:56
恩，那就是多个凭证。
smartman(2054958070)  14:34:13
那我就这么改了啊，多个银行，分别对应生成多个凭证。每个凭证的激励费用科目就对应该银行的支付额
永银周苏东(70907255)  14:34:59
对
smartman(2054958070)  14:36:53
好的

**Comment by kingofhawks** [comment]
UT201809040929144897

**Comment by kingofhawks** [comment]
永银周苏东(70907255) 2018/09/11 13:53:31
UT201807171500000623，可以参照体外系统这张报销单的逻辑
永银周苏东(70907255) 2018/09/11 13:54:18
凭证按实际银行卡支付金额生成，一个帐户生成一张凭证，对应一张收款单，借方先都挂在申请人名下
然后单独生成一张凭证，借 实际承担人，贷 申请人
永银周苏东(70907255) 2018/09/11 15:49:57
王工，这个需求你开始改了吗，没有的话停掉吧，财务太随意了，又说线下搞，不改系统了

永银-梁惠鹏(524123975) 2018/09/11 15:52:18
@永银周苏东 周总，那我这个需求结束了
smartman(2054958070) 2018/09/11 15:52:25
还没有，就是不太确定
永银周苏东(70907255) 2018/09/11 15:52:45
结束
smartman(2054958070) 2018/09/11 16:01:33
好的
