### ISSUE TITLE
结算价调整添加日志

### ISSUE THREAD

**Issue by poseidon-Liang** [qianlimu/yycoin#416]
结算价调整现在只能看到最新一次的记录，新增同一产品结算价先后调整的所有日志记录；
操作路径：批量导入“公共资源--导入结算价格”，手工修改“产品管理--产品价格配置”

**Comment by kingofhawks** [comment]
手工修改“产品管理--产品价格配置”这个页面是对应T_CENTER_PRICE_CONFIG表，
批量导入“公共资源--导入结算价格”是对应T_CENTER_SAILCONF
