### ISSUE TITLE
体外oa中待库管审批环节审批时提示报错

### ISSUE THREAD

**Issue by poseidon-Liang** [qianlimu/yycoin#419]

**Comment by kingofhawks** [comment]
哪个单号报什么错误？

**Comment by poseidon-Liang** [comment]
LYTW1809171606002185712

**Comment by kingofhawks** [comment]
核算项中人员[崔恒]不属于核算中的部门[04-01-04-04集邮业务部],组织架构数无法展开，数据有问题。

**Comment by poseidon-Liang** [comment]
TRUNCATE TABLE uportaltw.t_center_principalship;
INSERT INTO uportaltw.t_center_principalship SELECT * FROM uportal.t_center_principalship
表数据完全复制的；
SELECT b.* FROM uportaltw.t_center_oastaffer a
LEFT JOIN uportaltw.t_center_principalship b on a.industryId3 = b.ID
where a.`name` = '崔恒'
查询也正常；
还有什么关联表么？
