### ISSUE TITLE
激励问题，这批单号不需要生成

### ISSUE THREAD

**Issue by poseidon-Liang** [qianlimu/yycoin#434]
手动修改订单，激励改为未申请，去掉对应的UT单；
select * from t_center_out where fullid in ('SO1804200922610145948'
,'SO1804210858610282985'
,'SO1805030956612044392'
,'SO1805042313612277780'
,'SO1805250920615416570'
,'SO1807110948622445200'
,'SO1807310903624922046'
,'SO1808010902625052700'
,'SO1808100857626129205'
,'SO1808102258626162852'
,'SO1808140914626634035'
,'SO1808150903626793212'
,'SO1808180846627193153'
,'SO1808220850627671160'
,'SO1808230858627794868'
,'SO1808230858627794871'
,'SO1808310849628786614'
,'SO1808312150628821707')
motivationFlag改为0
motivationApplyId全部改为空
第二天又改为已申请，对应的UT单也挂上了；

**Comment by kingofhawks** [comment]
把这个JOB停掉exceptionalIbReportJob
