### ISSUE TITLE
总部结算价取值调整

### ISSUE THREAD

**Issue by kingofhawks** [qianlimu/yycoin#440]

**Comment by kingofhawks** [comment]
smartman(2054958070) 2018/10/09 12:03:15
@永银周苏东 周总，总部结算价这个修改需求，是不是要把系统导入开单生成结算价的地方都改掉?
永银周苏东(70907255) 2018/10/09 13:48:32
和订单生成没关系，只和合成、采购、结算价配置这几个地方有关
smartman(2054958070) 2018/10/09 16:41:28
和订单没关系？这个需求是说取值规则修改，那这个取值啥时候用到呢？比如合成，目前并不涉及到总部结算价啊。
永银周苏东(70907255) 2018/10/09 16:42:17
订单按正常逻辑计算结算价取值
更改的是总部结算价，合成时，如果是新的合成价格，就得更新这个合成成品的结算价
smartman(2054958070) 2018/10/09 16:43:27
以合成为例，根据产品合成，去修改对应产品的总部结算价吗？
首先明确一点，这个需求，最终的结果，是不是修改产品表的总部结算价？
smartman(2054958070) 2018/10/09 16:45:56
现在开单时，用到的总部结算价，是计算出来的，不是取得某个字段。产品表中只有这个字段
[图片]
smartman(2054958070) 2018/10/09 17:09:57
产品表中只有结算价sailPrice字段[图片]
是要修改这个字段吗？
永银周苏东(70907255) 2018/10/09 17:13:45
对
smartman(2054958070)  17:15:46
合成，采购，手工配置，这三个入口，把product表的sailPrice字段给修改掉，是这样吧？
永银周苏东(70907255)  17:16:02
是的
smartman(2054958070)  17:16:09
好的

**Comment by kingofhawks** [comment]
有个问题：
1. 产品合成时把product表的结算价修改掉
2. 接着又做采购入库，这时候还需要再次把结算价覆盖掉吗？

**Comment by kingofhawks** [comment]
select * from t_center_depotpart where name='空退空开库（仅限商务部操作）';

**Comment by kingofhawks** [comment]
smartman(2054958070)  11:15:39
@永银周苏东 周总，有两个问题：
1. 结算价修改的顺序
步骤1 产品合成把product表的结算价修改掉
步骤2 接着又做该产品的采购入库，这时候还需要再次把产品的结算价覆盖掉吗？
2. 虚料清单能否在product表加个字段？
永银周苏东(70907255)  11:16:58
对，只要有不一样的价格且有可更改标识的就自动更新掉
记录日志
虚料可以加个字段
smartman(2054958070)  11:19:14
产品表加2个字段，一个可更改标识，一个虚料。
有可更改标识的，不管业务是做合成还是采购，也不管先后顺序，只要做了就修改产品的sailPrice
永银周苏东(70907255)  11:19:47
对
smartman(2054958070)  11:32:07
好的

**Comment by kingofhawks** [comment]
alter table T_CENTER_PRODUCT add column sailPriceFlag int(2) default 0, add column virtualFlag int(2) default 0;

**Comment by kingofhawks** [comment]
SO1810171732632962118

**Comment by kingofhawks** [comment]
YZ0202601 第三套人民币珍藏套装(绝品不含贰圆)+福字银币-9张光钞（普2）

**Comment by kingofhawks** [comment]
insert into t_center_schedule_job values (554,'2010-10-22 00:00:00','2010-10-22 00:00:00','sailPriceJobManager','Default','0','0 45 12 * * ?','结算价更新','com.china.center.oa.job.manager.impl.SailPriceJobManagerImpl','0','sailPriceJobManager','run',0);

**Comment by kingofhawks** [comment]
YZ0372500 响洪甸水库银章20g（定制中心）（普16）

**Comment by kingofhawks** [comment]
YZ0254205 2018年熊猫金币普通套装含包装-30克金币（普0）
该产品昨天下午做了采购单，采购单的入库成本为8310，但是刚刚查询系统中总部结算价是8340，SO1810281947634021765

**Comment by poseidon-Liang** [comment]
结算价找周总确认版本

job更新config的虚料，如果没有config配置项，直接更新product的sailprice

有配置项，先更新配置项的辅料字段，然后通过公式，金银价那些东西来算出结算价，然后更新回product的sailprice
double sailPrice = product.getCost() * gold*bean.getGoldPriceFactor() + product.getPlanCost() * silver*bean.getSilverPriceFactor() + bean.getPrice() + bean.getGsPriceUp();
结算价 = 金价*金价系数*金克数+银价*银价系数*银克数+邮票费用+辅料费用;

页面：销售->产品查询，非销售直接读取sailprice，销售人员，通过sailprice+事业部价格显示

**Comment by kingofhawks** [comment]
YZ0386900 投资金条10克（无企业LOGO版）（普16）

**Comment by kingofhawks** [comment]
A1201811131535795113

**Comment by poseidon-Liang** [comment]
1.同一产品，既有合成单，又有采购单，以合成单数据为准；
2.同一产品A，有多个合成单，有的合成单含虚料，有的合成单不含虚料，在用这个A产品，去合成B产品的时候，以最近一次合成单为参照，多层套叠以此类推
