### ISSUE TITLE
批量退货

### ISSUE THREAD

**Issue by kingofhawks** [qianlimu/yycoin#441]

**Comment by kingofhawks** [comment]
![32 bjn yoc h fci z 0m0](https://user-images.githubusercontent.com/45868/46657968-22b3f080-cbe4-11e8-9269-ccb4751939a3.png)

**Comment by kingofhawks** [comment]
备份原菜单
INSERT INTO uportal.t_center_oamenuitem (id, MENUITEMNAME, URL, PARENTID, BottomFlag, AUTH, indexPos, description) VALUES ('1434', '批量退货', '../sail/out.do?method=addBatchBack', '14', 1, '1401', 99, null);

**Comment by kingofhawks** [comment]
导入时报错“参数为空”，一般都是导入模板格式的问题。

**Comment by poseidon-Liang** [comment]
批量退货优化： 1：  模板里面“成本”字段，改为非必填项，判断对应销售订单里面是否同一个产品存在多个成本，如果是，并且模板里面没有填写对应成本，则给出报错提示，某某行订单存在多个成本，需写出对应的成本，如果销售单里面的商品仅存在一个成本，则无视成本价正常退货。    
2：模板去除“销售价”字段

**Comment by kingofhawks** [comment]
批量退货问题：
1：订单状态在待商务审批，待库存审批的状态可以退货（实际不允许）
2：当退货数量大于可退数量时，仍然可以退货  XT1811131657635808503
3：订单退货商品存在发票，发票还没有退，也可以退货XT1811131707635808866（实际不允许）

**Comment by kingofhawks** [comment]
../sail/batchBack2.jsp

**Comment by kingofhawks** [comment]
SO1811200919636624283 这个退货单又出问题了
退货数量大于销售单数量，没报错

**Comment by kingofhawks** [comment]
XT1811201555636657199
退货单号

**Comment by kingofhawks** [comment]
之前那个批量退货的，销售单批量退货是没有问题的，赠送单批量退货，生成单号是xt的，应该生成zt的
