### ISSUE TITLE
平台手续费优化

### ISSUE THREAD

**Issue by poseidon-Liang** [qianlimu/yycoin#442]
需求说明：
由于钱币线上零售价特殊，无法维护一个固定的平台手续费额度，故将系统中“平台手续费”取值优化。
1.如果客户名称为“永银文化-天猫、钱币交易部-淘宝、中金国华-天猫、钱币交易部-京东、中金国华-京东”，则系统自动计算，平台手续费=零售价*1%；
2.如果客户名不在以上客户名中，则直接取“在售产品明细表”中维护的“平台手续费”额度。

**Comment by kingofhawks** [comment]
平台手续费测试反馈：
测试单号：SO1810121032632467242
客户名称：中金国华-天猫
零售价：175
按照优化需求：平台手续费=零售价*1%=175*1%
测试单中平台手续费金额为：0
