### ISSUE TITLE
停用账号回收客户报错

### ISSUE THREAD

**Issue by kingofhawks** [qianlimu/yycoin#449]
回收/驳回职员客户失败:PreparedStatementCallback; SQL [INSERT INTO T_CENTER_VS_STACUS(stafferId, customerId) VALUES (?, ?)]; Duplicate entry '631455244' for key 'inx_cus'; nested exception is com.mysql.jdbc.exceptions.MySQLIntegrityConstraintViolationException: Duplicate entry '631455244' for key 'inx_cus
--

**Comment by kingofhawks** [comment]
select * from T_CENTER_VS_STACUS where CUSTOMERID='631455244';
这行数据在体外表有了.

**Comment by poseidon-Liang** [comment]
因触发器原因导致更新失败，现触发器已删除改为过程执行；
