### ISSUE TITLE
添加采购单，特殊处理拆单

### ISSUE THREAD

**Issue by poseidon-Liang** [qianlimu/yycoin#450]

**Comment by kingofhawks** [comment]
CQBJ201810161634229947872

**Comment by kingofhawks** [comment]
这里面多加了个拆单
你这里需要单独处理下
需要使用t_purchase_bj的adviseSupplier等于t_purchase_pj_xqqr的adviseSupplier
永银-梁惠鹏 2018/10/17 09:56:49
即[图片]
这样
否则的话会出现重复项，导致你显示和入库不准确

**Comment by kingofhawks** [comment]
duplicate #452
