### ISSUE TITLE
批量修改发票号码-导入添加发票代码

### ISSUE THREAD

**Issue by poseidon-Liang** [qianlimu/yycoin#456]
OA-资金管理-批量修改发票号码，导入模板需扩展一个字段“发票代码”

**Comment by kingofhawks** [comment]
alter table T_CENTER_VS_INVOICENUM add column invoiceCode varchar(64) default '';

**Comment by poseidon-Liang** [comment]
功能已完成，导入的下载模板需要添加上发票代码
