### ISSUE TITLE
到货完成后调拨

### ISSUE THREAD

**Issue by poseidon-Liang** [qianlimu/yycoin#460]

**Comment by kingofhawks** [comment]
SELECT  
a.dhno 到货单号,
a.productid 产品ID,
a.cg_amount 采购数量,
a.ydh_amount 应到数量,
b.zj_hg_amount 合格数量,
a.ydh_amount - b.zj_hg_amount 不合格数量,
b.sccg_rkfx 仓库id,
b.sccg_isyd 是否异地 # 1：是，0：否
FROM t_center_dh_zjb a
LEFT JOIN t_center_dh_result b on a.dhno = b.dhno and a.productid = b.productid
where a.`status` = '结束'

**Comment by kingofhawks** [comment]
合格的调拨到查询出来的仓库内；
不合格的调拨到不良品仓
SELECT * FROM t_center_depotpart
where name like '%不良品仓%';
depotpartid = 7

**Comment by kingofhawks** [comment]
create table uportal.t_center_dh_zjb
(
	id int auto_increment
		primary key,
	stockid varchar(40) null,
	productid int null,
	cg_amount int null,
	ydh_amount int null,
	transportno varchar(40) null,
	dhno varchar(50) null,
	status varchar(20) null,
	createtime datetime null,
	createuser int null
)
;

**Comment by kingofhawks** [comment]
create table uportal.t_center_dh_result
(
	id int auto_increment
		primary key,
	dhno varchar(50) null,
	productid int null,
	sd_amount int null,
	wl_remarks varchar(100) null,
	wl_sh_user int null,
	wl_sh_time datetime null,
	wl_ch_time datetime null,
	wl_jkdw varchar(50) null,
	wl_time datetime null,
	zj_hg_amount int null,
	zj_blyy varchar(100) null,
	zj_blyy_fj varchar(100) null,
	zj_clyj varchar(100) null,
	zj_result varchar(100) null,
	zj_user int null,
	zj_sh_user int null,
	zj_time datetime null,
	zj_zkdw varchar(50) null,
	sccg_rkfx varchar(50) null,
	sccg_cljg varchar(100) null,
	sccg_cldz varchar(100) null,
	sccg_user int null,
	sccg_time datetime null,
	sccg_rk_type varchar(20) null,
	sccg_isyd int(1) null
)
;

**Comment by kingofhawks** [comment]
INSERT INTO uportal.t_center_depot (id, type, name, description, industryId, industryId2, status, item) VALUES ('A1201705251771966137', 1, '生产作业库', '生产部专用', '2043336', '99', 0, '全部');

**Comment by kingofhawks** [comment]
DB1811181521636381382  DB1811181320636380267  
PZ201811181536381387 
这些生成的删除下

**Comment by kingofhawks** [comment]
SO_CG201811161430636201594   对应调拨单号：DB1811181610636382434   ，例如这个，采购成本实际为：273.15    调拨单入库成本：1129.77

**Comment by poseidon-Liang** [comment]
生产录入处理之后，只生成一张调拨单，调拨数量取实到数量。不考虑不良情况，直接入选择的仓库

**Comment by kingofhawks** [comment]
DB1811200920636624368      DB1811201051636629094     PZ201811201036629099
帮忙删除下

**Comment by kingofhawks** [comment]
DB1811231610637080082  DB1811231605637079391
物流中心作业库，会重复生成。

**Comment by kingofhawks** [comment]
alter table t_center_dh_zjb add column outId varchar(64) default null;

**Comment by kingofhawks** [comment]
select a.id,a.stockid,a.dhno,a.createUser,a.productId,a.cg_amount,a.ydh_amount,b.sd_amount,b.zj_hg_amount,a.ydh_amount-b.zj_hg_amount as bhg_amount,b.sccg_rkfx from t_center_dh_zjb a left join t_center_dh_result b on a.dhno=b.dhno and a.productid=b.productid where a.status='结束' and a.processedFlag=0

**Comment by kingofhawks** [comment]
如果调拨失败，不要把生成的DB单号写入zjb表，只更新标志位。
