### ISSUE TITLE
导入开单“收货人手机”和“固定电话”至少填写一个字段

### ISSUE THREAD

**Issue by kingofhawks** [qianlimu/yycoin#461]
商务在oa中导入开单模板时，现在模板中“收货人手机”为必填项，“固定电话”不是必填项，需要优化为：“收货人手机”和“固定电话”至少填写一个字段（如果两个都为空则不允许提交，至少填写一个，或者两个都填写）

**Comment by poseidon-Liang** [comment]
去掉手机号必须限制；
导入的时候固话和手机号都有，只保留手机号；
二选其一的时候判断有值的正常录入即可

**Comment by kingofhawks** [comment]
永银-梁惠鹏 2018/10/26 16:46:56
现在限制放开，手机只允许11位，固话随意；
导入时候固话，手机号都有只填写手机号入表；
二选其一正常录入即可
