### ISSUE TITLE
OA-客户关系管理-导入客户->个人类型

### ISSUE THREAD

**Issue by poseidon-Liang** [qianlimu/yycoin#464]
现修改，个人类型，用户名唯一，手机号取消约束

**Comment by poseidon-Liang** [comment]
个人类型，用户名前两个字必须为永银

**Comment by poseidon-Liang** [comment]
个人类型，相同用户名没有做控制，用户名需唯一

**Comment by poseidon-Liang** [comment]
新规则：
个人类型客户导入：
1、手机号必填，去除“停用”，“重复”状态，手机号唯一；
2、用户名必须以“永银”两个字开头，无视状态，唯一；
3、地址允许为空；
以上修改忽略原违规数据，新导入的做控制

**Comment by kingofhawks** [comment]
如果客户手机号存在“停用”，“重复”职员下边，就可以允许手机号重复。其他情况都不允许手机号重复。
