### ISSUE TITLE
优化中信导入、D单号生成关联product_import_id

### ISSUE THREAD

**Issue by poseidon-Liang** [qianlimu/yycoin#470]

**Comment by kingofhawks** [comment]
alter table t_center_product_import add column item varchar(20) default '', add column isSell varchar(20) default '';

**Comment by kingofhawks** [comment]
alter table t_center_base add column productImportId varchar(20) default null;

**Comment by kingofhawks** [comment]
alter table t_center_out_import add column productImportId varchar(20) default null;

**Comment by kingofhawks** [comment]
ALTER TABLE t_center_olbase CHANGE product_import_id productImportId varchar(20) DEFAULT null;

**Comment by kingofhawks** [comment]
alter table T_CENTER_OLBASE add column productImportId varchar(20) default null;
