### ISSUE TITLE
优化资金管理

### ISSUE THREAD

**Issue by poseidon-Liang** [qianlimu/yycoin#478]
1：路径：  OA-资金管理-付款单管理   新增付款单类型“离职人员报销”，并自动生成凭证，借：其他应付款-个人   贷方：银行存款。  详情如附件。  2：OA-资金管理-采购付款审批，新增“合计金额”字段。取“实付金额”字段的合计。

**Comment by kingofhawks** [comment]
INSERT INTO uportal.t_center_tax (ID, parentId, parentId0, parentId1, parentId2, parentId3, parentId4, parentId5, parentId6, parentId7, parentId8, code, ptype, name, bname, refId, refType, type, status, bottomFlag, level, forward, unit, department, staffer, depot, product, duty, checkStaffer) VALUES ('2181-02', '2181', '2181', '', '', '', '', '', '', '', '', '2181-02', 'A1110000000000000002', '其他应付款-个人', '其他应付款-个人', '', 0, 2, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0);

**Comment by kingofhawks** [comment]
采购付款审批目前需要一单点开查看实付金额，减慢审核速度。
按照供应商筛选，界面的总金额定义为实付金额，筛选后在界面自动出现合计实付金额。
