### ISSUE TITLE
优化新建产品

### ISSUE THREAD

**Issue by poseidon-Liang** [qianlimu/yycoin#480]
新建产品时，增加字段“是否为虚拟产品”，并且为必填项；
路径：OA--产品管理--批量导入新产品申请（批量新增）
OA--产品管理--新产品申请（单独手动新增）
原因：将产品打上“虚拟产品”标志的环节在新建新品的时候就完成，避免后期批量打标延时的情况

**Comment by kingofhawks** [comment]
发现product表之前有个字段abstractType，也是定义为“虚拟产品”，后来又加了一个字段virtualFlag,确认一下这两个字段作用是一样的吗？

**Comment by kingofhawks** [comment]
alter table T_PRODUCT_APPLY add column virtualFlag int(2) default 0;

**Comment by poseidon-Liang** [comment]
新建产品时，增加字段“是否为虚拟产品”测试结果反馈：
1.OA--产品管理--新产品申请（手工单独新增）路径已经测试完毕；
2.OA--产品管理--批量导入新产品申请测试未通过：a.新下载的模板中未新增字段“是否为虚料”；b.导入时没有必填项提醒
