### ISSUE TITLE
回款单 HK201811151136057745 有问题

### ISSUE THREAD

**Issue by poseidon-Liang** [qianlimu/yycoin#481]

**Comment by kingofhawks** [comment]
11月出现不少回款拆分异常和凭证异常的单据
暂时没发现什么规律
HK201811271437526613  

HK201811131035778078

HK201811151136057745
SF单的合计金额不等于HK金额
凭证也没生成

**Comment by kingofhawks** [comment]
T_CENTER_VS_OUTPAY表中有三行重复的与out表关联关系？HK201811271437526613

**Comment by poseidon-Liang** [comment]
HK201812201540448304

**Comment by kingofhawks** [comment]
HK201904231059318844

**Comment by kingofhawks** [comment]
HK201905241664204313正常单据应该类似这个。

**Comment by kingofhawks** [comment]
passPaymentApplyForJob()

**Comment by kingofhawks** [comment]
INSERT INTO uportal.t_center_payment (ID, name, fromer, refId, bankId, stafferId, customerId, batchId, type, status, useall, money, handling, useMoney, receiveTime, logTime, description, destStafferId, updateTime, checks1, checks2, checkStatus, checks3, bakmoney, fromerNo, ctype, posTerminalNumber) VALUES ('HK201905241664204313', '', '上海志行合力网络技术有限公司', '2019052400005', 'A1201609211538498967', '136887', '14613967', '20190524165202209', 0, 1, 1, 60000, 0, 60000, '2019-05-24', '2019-05-24 16:52:28', '', '0', '2019-05-24 17:35:01', '', '', 0, '', 60000, '310066632018170111965', 0, '');

**Comment by kingofhawks** [comment]
INSERT INTO uportal.t_center_payapply (ID, paymentId, stafferId, customerId, type, status, badMoney, moneys, logTime, locationId, approve, description, vtype, checkStatus, checks, checkrefId, oriCustomerId, oriStafferId, oriBillId, operator, operatorName) VALUES ('UH201905241764208999', 'HK201905241664204313', '136887', '14613967', 0, 1, 0, 60000, '2019-05-24 17:30:26', '999', '', '0', 0, 0, '', '', '', '', '', '136887', '黄文林');

**Comment by kingofhawks** [comment]
INSERT INTO uportal.t_center_vs_outpay (id, parentId, outId, outBalanceId, paymentId, billId, moneys, stafferId, locationId, logTime) VALUES ('A1201905241764209000', 'UH201905241764208999', 'SO1901020850642049322', '', 'HK201905241664204313', 'SF201905241764209084', 60000, '136887', '999', '2019-05-24 17:30:26');
INSERT INTO uportal.t_center_vs_outpay (id, parentId, outId, outBalanceId, paymentId, billId, moneys, stafferId, locationId, logTime) VALUES ('A1201905241764209001', 'UH201905241764208999', '', '', 'HK201905241664204313', '', 0, '136887', '999', '2019-05-24 17:30:26');

**Comment by kingofhawks** [comment]
INSERT INTO uportal.t_center_payment (ID, name, fromer, refId, bankId, stafferId, customerId, batchId, type, status, useall, money, handling, useMoney, receiveTime, logTime, description, destStafferId, updateTime, checks1, checks2, checkStatus, checks3, bakmoney, fromerNo, ctype, posTerminalNumber) VALUES ('HK201903081551990734', '', '本系统转账32429807', '2019030800040', 'A1201706081873339929', '639000232', '641369398', '20190308150833454', 0, 1, 0, 1380, 4.14, 0, '2019-03-08', '2019-03-08 15:09:05', '131560000753201903072843428314', '0', '', '', '', 0, '', 1380, '131560000753201903072843428314', 0, '');

**Comment by kingofhawks** [comment]
INSERT INTO uportal.t_center_payapply (ID, paymentId, stafferId, customerId, type, status, badMoney, moneys, logTime, locationId, approve, description, vtype, checkStatus, checks, checkrefId, oriCustomerId, oriStafferId, oriBillId, operator, operatorName) VALUES ('UH201903191553737739', 'HK201903081551990734', '639000232', '641369398', 0, 1, 0, 1380, '2019-03-19 15:41:44', '999', '', '永银钱币博物馆', 0, 0, '', '', '', '', '', '639000232', '张涛-博物馆');

**Comment by kingofhawks** [comment]
INSERT INTO uportal.t_center_vs_outpay (id, parentId, outId, outBalanceId, paymentId, billId, moneys, stafferId, locationId, logTime) VALUES ('A1201903191553737765', 'UH201903191553737739', '', '', 'HK201903081551990734', '', 30, '639000232', '999', '2019-03-19 15:41:44');
INSERT INTO uportal.t_center_vs_outpay (id, parentId, outId, outBalanceId, paymentId, billId, moneys, stafferId, locationId, logTime) VALUES ('A1201903191553737755', 'UH201903191553737739', 'SO1903130932652773619', '', 'HK201903081551990734', '', 60, '639000232', '999', '2019-03-19 15:41:44');
INSERT INTO uportal.t_center_vs_outpay (id, parentId, outId, outBalanceId, paymentId, billId, moneys, stafferId, locationId, logTime) VALUES ('A1201903191553737764', 'UH201903191553737739', 'SO1903130932652773619', '', 'HK201903081551990734', '', 60, '639000232', '999', '2019-03-19 15:41:44');
INSERT INTO uportal.t_center_vs_outpay (id, parentId, outId, outBalanceId, paymentId, billId, moneys, stafferId, locationId, logTime) VALUES ('A1201903191553737754', 'UH201903191553737739', 'SO1903130932652773622', '', 'HK201903081551990734', '', 15, '639000232', '999', '2019-03-19 15:41:44');
INSERT INTO uportal.t_center_vs_outpay (id, parentId, outId, outBalanceId, paymentId, billId, moneys, stafferId, locationId, logTime) VALUES ('A1201903191553737763', 'UH201903191553737739', 'SO1903130932652773622', '', 'HK201903081551990734', '', 15, '639000232', '999', '2019-03-19 15:41:44');
INSERT INTO uportal.t_center_vs_outpay (id, parentId, outId, outBalanceId, paymentId, billId, moneys, stafferId, locationId, logTime) VALUES ('A1201903191553737753', 'UH201903191553737739', 'SO1903130932652773634', '', 'HK201903081551990734', '', 80, '639000232', '999', '2019-03-19 15:41:44');
INSERT INTO uportal.t_center_vs_outpay (id, parentId, outId, outBalanceId, paymentId, billId, moneys, stafferId, locationId, logTime) VALUES ('A1201903191553737762', 'UH201903191553737739', 'SO1903130932652773634', '', 'HK201903081551990734', '', 80, '639000232', '999', '2019-03-19 15:41:44');
INSERT INTO uportal.t_center_vs_outpay (id, parentId, outId, outBalanceId, paymentId, billId, moneys, stafferId, locationId, logTime) VALUES ('A1201903191553737752', 'UH201903191553737739', 'SO1903130932652773640', '', 'HK201903081551990734', '', 20, '639000232', '999', '2019-03-19 15:41:44');
INSERT INTO uportal.t_center_vs_outpay (id, parentId, outId, outBalanceId, paymentId, billId, moneys, stafferId, locationId, logTime) VALUES ('A1201903191553737761', 'UH201903191553737739', 'SO1903130932652773640', '', 'HK201903081551990734', '', 20, '639000232', '999', '2019-03-19 15:41:44');
INSERT INTO uportal.t_center_vs_outpay (id, parentId, outId, outBalanceId, paymentId, billId, moneys, stafferId, locationId, logTime) VALUES ('A1201903191553737751', 'UH201903191553737739', 'SO1903130932652773650', '', 'HK201903081551990734', '', 98, '639000232', '999', '2019-03-19 15:41:44');
INSERT INTO uportal.t_center_vs_outpay (id, parentId, outId, outBalanceId, paymentId, billId, moneys, stafferId, locationId, logTime) VALUES ('A1201903191553737760', 'UH201903191553737739', 'SO1903130932652773650', '', 'HK201903081551990734', '', 98, '639000232', '999', '2019-03-19 15:41:44');
INSERT INTO uportal.t_center_vs_outpay (id, parentId, outId, outBalanceId, paymentId, billId, moneys, stafferId, locationId, logTime) VALUES ('A1201903191553737750', 'UH201903191553737739', 'SO1903130932652773656', '', 'HK201903081551990734', '', 15, '639000232', '999', '2019-03-19 15:41:44');
INSERT INTO uportal.t_center_vs_outpay (id, parentId, outId, outBalanceId, paymentId, billId, moneys, stafferId, locationId, logTime) VALUES ('A1201903191553737759', 'UH201903191553737739', 'SO1903130932652773656', '', 'HK201903081551990734', '', 15, '639000232', '999', '2019-03-19 15:41:44');
INSERT INTO uportal.t_center_vs_outpay (id, parentId, outId, outBalanceId, paymentId, billId, moneys, stafferId, locationId, logTime) VALUES ('A1201903191553737749', 'UH201903191553737739', 'SO1903130932652773665', '', 'HK201903081551990734', '', 10, '639000232', '999', '2019-03-19 15:41:44');
INSERT INTO uportal.t_center_vs_outpay (id, parentId, outId, outBalanceId, paymentId, billId, moneys, stafferId, locationId, logTime) VALUES ('A1201903191553737758', 'UH201903191553737739', 'SO1903130932652773665', '', 'HK201903081551990734', '', 10, '639000232', '999', '2019-03-19 15:41:44');
INSERT INTO uportal.t_center_vs_outpay (id, parentId, outId, outBalanceId, paymentId, billId, moneys, stafferId, locationId, logTime) VALUES ('A1201903191553737748', 'UH201903191553737739', 'SO1903151043653134499', '', 'HK201903081551990734', '', 88, '639000232', '999', '2019-03-19 15:41:44');
INSERT INTO uportal.t_center_vs_outpay (id, parentId, outId, outBalanceId, paymentId, billId, moneys, stafferId, locationId, logTime) VALUES ('A1201903191553737757', 'UH201903191553737739', 'SO1903151043653134499', '', 'HK201903081551990734', '', 88, '639000232', '999', '2019-03-19 15:41:44');
INSERT INTO uportal.t_center_vs_outpay (id, parentId, outId, outBalanceId, paymentId, billId, moneys, stafferId, locationId, logTime) VALUES ('A1201903191553737747', 'UH201903191553737739', 'SO1903151043653134511', '', 'HK201903081551990734', '', 60, '639000232', '999', '2019-03-19 15:41:44');
INSERT INTO uportal.t_center_vs_outpay (id, parentId, outId, outBalanceId, paymentId, billId, moneys, stafferId, locationId, logTime) VALUES ('A1201903191553737756', 'UH201903191553737739', 'SO1903151043653134511', '', 'HK201903081551990734', '', 60, '639000232', '999', '2019-03-19 15:41:44');
INSERT INTO uportal.t_center_vs_outpay (id, parentId, outId, outBalanceId, paymentId, billId, moneys, stafferId, locationId, logTime) VALUES ('A1201903191553737746', 'UH201903191553737739', 'SO1903151043653134514', '', 'HK201903081551990734', '', 15, '639000232', '999', '2019-03-19 15:41:44');
INSERT INTO uportal.t_center_vs_outpay (id, parentId, outId, outBalanceId, paymentId, billId, moneys, stafferId, locationId, logTime) VALUES ('A1201903191553737745', 'UH201903191553737739', 'SO1903151043653134517', '', 'HK201903081551990734', '', 88, '639000232', '999', '2019-03-19 15:41:44');
INSERT INTO uportal.t_center_vs_outpay (id, parentId, outId, outBalanceId, paymentId, billId, moneys, stafferId, locationId, logTime) VALUES ('A1201903191553737744', 'UH201903191553737739', 'SO1903151043653134526', '', 'HK201903081551990734', '', 60, '639000232', '999', '2019-03-19 15:41:44');
INSERT INTO uportal.t_center_vs_outpay (id, parentId, outId, outBalanceId, paymentId, billId, moneys, stafferId, locationId, logTime) VALUES ('A1201903191553737743', 'UH201903191553737739', 'SO1903151043653134535', '', 'HK201903081551990734', '', 105, '639000232', '999', '2019-03-19 15:41:44');
INSERT INTO uportal.t_center_vs_outpay (id, parentId, outId, outBalanceId, paymentId, billId, moneys, stafferId, locationId, logTime) VALUES ('A1201903191553737742', 'UH201903191553737739', 'SO1903151043653134553', '', 'HK201903081551990734', '', 100, '639000232', '999', '2019-03-19 15:41:44');
INSERT INTO uportal.t_center_vs_outpay (id, parentId, outId, outBalanceId, paymentId, billId, moneys, stafferId, locationId, logTime) VALUES ('A1201903191553737741', 'UH201903191553737739', 'SO1903151043653134559', '', 'HK201903081551990734', '', 30, '639000232', '999', '2019-03-19 15:41:44');
INSERT INTO uportal.t_center_vs_outpay (id, parentId, outId, outBalanceId, paymentId, billId, moneys, stafferId, locationId, logTime) VALUES ('A1201903191553737740', 'UH201903191553737739', 'SO1903181605653558177', '', 'HK201903081551990734', '', 60, '639000232', '999', '2019-03-19 15:41:44');

**Comment by kingofhawks** [comment]
T_CENTER_VS_OUTPAY表中paymentId+outId，应该不允许重复。
