### ISSUE TITLE
中信导入去掉映射关系，直接读取product

### ISSUE THREAD

**Issue by poseidon-Liang** [qianlimu/yycoin#488]
优化需求：
商务在OA导入开单模板，系统生成订单时，订单中的OA品名直接读取在售产品明细表维护的OA品名，省去原先维护银行产品名称与OA品名映射关系这一环节@梁惠鹏  
维护映射关系的路径：OA--中信销售--中信产品导入
导入开单模板的路径：OA--中信销售--中信数据导入;
逻辑修改之后映射关系导入菜单隐藏

**Comment by kingofhawks** [comment]
有点问题，现在只有销售出库才读在售产品明细表，导入其它销售单类型时不会读产品明细表。

**Comment by kingofhawks** [comment]
改为从product表根据商品名称读取，在售产品读取逻辑不变，商品名是唯一的。
