### ISSUE TITLE
修改凭证生成借方科目

### ISSUE THREAD

**Issue by poseidon-Liang** [qianlimu/yycoin#491]
路径：销售管理-我的销售单，点击勾款，坏账部分的金额生成凭证，修改凭证生成借方科目

**Comment by kingofhawks** [comment]
rawPayment3->addApply2->addPaymentApply->addPaymentApplyWithoutTrans

**Comment by kingofhawks** [comment]
PaymentApplyListenerTaxGlueImpl.mainFinanceInBadPay

**Comment by kingofhawks** [comment]
坏账部分的金额生成凭证，借方科目目前为：其他应收款-坏账(1133-10)   贷方科目为：应收账款，需修改凭证生成的借方科目，如下：
修改为：借方科目：销售费用   科目编码：5504-25

**Comment by kingofhawks** [comment]
销售单"确认坏账"功能对应的凭证也是用的“其它应收-坏账”，也要修改吗？
