### ISSUE TITLE
体外系统，客户名为“上海金币投资有限公司”时，发货单模板  ----优先处理

### ISSUE THREAD

**Issue by poseidon-Liang** [qianlimu/yycoin#497]

**Comment by poseidon-Liang** [comment]
Poseidon ’(524123975)  11:34:14
这个需求优先么？
周苏东　永银(70907255)  11:35:11
优先
Poseidon ’(524123975)  11:35:26
好的
周苏东　永银(70907255)  11:42:43
订单时间和分行名称不用增加字段，用原来模板里的中信订单日期和分行名称字段

**Comment by kingofhawks** [comment]
![q8edqs pt sk k 1j tv js](https://user-images.githubusercontent.com/45868/49512242-4b94f100-f8c8-11e8-8b25-3f7c7c59cb38.png)

**Comment by kingofhawks** [comment]
永银周苏东(70907255) 2018/12/05 11:42:43
订单时间和分行名称不用增加字段，用原来模板里的中信订单日期和分行名称字段
