### ISSUE TITLE
历史黑名单应收优化  ->优先

### ISSUE THREAD

**Issue by poseidon-Liang** [qianlimu/yycoin#500]
周苏东 12-6 10:27:32
所以按销售价统计的逻辑可以不用改，但要增加个统计字段

周苏东 12-6 10:29:05
所有单据的要统计按   成本价*应收数量，单列字段，不在前台显示

**领样**的销售价目前为0，需要后台加逻辑去计算，成本价*应收数量来统计；
前台页面不显示，导出也不显示。只为了后期审核数据校验使用。

**Comment by poseidon-Liang** [comment]
如果没有数量的判断，还需要加上数量正负为0的校验，与原金额校验并行

**Comment by kingofhawks** [comment]
永银周苏东(70907255)  13:12:57
嗯，刚确认过，取结算价， 不取成本价
永银周苏东(70907255)  13:18:47
体外系统，袁少龙，LYTW1811131535002330237
金额取事业部结算价187，现在应收里是0

**Comment by kingofhawks** [comment]
smartman(2054958070)  15:34:40
领样的现在销售价为0，只要改成根据结算价*数量来计算，不用新增字段吧？

smartman(2054958070)  15:35:56
明细里边金额和列表页面显示金额不一致，也是这个问题吗？
永银周苏东(70907255)  15:36:43
不是
明细里的应收金额应该是这个页面上的金额累计
smartman(2054958070)  15:37:26
明细里金额和列表页面不一致是正常的？
永银周苏东(70907255)  15:38:00

是这页面上金额的累计
不用管
smartman(2054958070)  15:38:17
好
为什么同样是领样单，有些有金额，有些没有金额？
永银周苏东(70907255)  15:38:49
领样的金额全改成 结算价*数量
因为开单时有的输入价格为0，有的又写上了销售额，各种渠道和规定花样太多
所以全改成按结算价算金额，省得烦了
smartman(2054958070)  15:40:02
个人领样和银行领样？
永银周苏东(70907255)  15:40:07
这个不是最关键的，最关键的是应收的对比逻辑，现在只是销售额和回款，退货额比，要再加上数量的比较
smartman(2054958070)  15:41:42
还不止是这个金额的问题吗？
永银周苏东(70907255)  15:42:23

两个事
smartman(2054958070)  15:43:05
数量比对是为了什么原因？
成本价*应收数量
你说的是应收数量吧？
永银周苏东(70907255)  15:43:50
因为销售额为0，这样数量再多，退一个也是平了，就不在应收范围内了
smartman(2054958070)  15:45:23
就是领样单的应收金额=事业部结算价*应收数量，包括个人领样和银行领样，是这样吧？
永银周苏东(70907255)  15:45:57
这是显示的统计金额，另一个是要增加比对维度
不然应该进入应收明细的都没统计进来，就谈不上显示什么金额了
smartman(2054958070)  15:46:29
有点晕了
永银周苏东(70907255)  15:46:40
你方便接电话不
smartman(2054958070)  15:46:50
这会不方便，周围都是人
永银周苏东(70907255)  15:46:58
哦
其实就是两个事
一个是解决应收范围对比逻辑的事
另一个是解决显示金额的事
smartman(2054958070)  15:47:45
关键还是看写入哪张表吧？
永银周苏东(70907255)  15:48:05
写入的表没变化
写入什么有变化
我找张单子吧
smartman(2054958070)  15:48:26
写入表不变？
永银周苏东(70907255)  15:48:34
嗯
smartman(2054958070)  15:48:42
入库的数据不变吗？
永银周苏东(70907255)  15:52:15
不变，只是现在有些该进表的单据没进去
稍等，我找个单号出来
smartman(2054958070)  15:54:47
嗯
永银周苏东(70907255)  16:04:52
LY1811261045637382164
这单领了10个，退了3个，但不在应收明细里
因为销售金额是0，退一个就是0，系统认为平了，就变成已付款状态
永银周苏东(70907255)  16:06:04
所以要在销售额这个维度外增加 数量维度
smartman(2054958070)  16:07:42
所以这个单据在黑名单统计的时候，就不会被统计到？
永银周苏东(70907255)  16:10:24
对
但应该在里面
smartman(2054958070)  16:13:52
现在统计黑名单的时候条件是这样的，要求付款状态是“未付款”
那现在就要变成已付款的领样单也要检查，然后计算金额再根据结算价*应收数量
永银周苏东(70907255)  16:14:47
所以要么在订单更新时检查数量，要么在黑名单统计 增加检查数量
可以控制为金额为0的已付款的领样单
永银周苏东(70907255)  16:16:04
我感觉在订单更新付款状态时检查更好些
这样我只要初始化一下现在的异常，就不要动应收的统计逻辑了
smartman(2054958070)  16:22:25
嗯，可以改订单付款状态更新的逻辑
永银周苏东(70907255)  16:22:37
那也行
smartman(2054958070)  16:22:40
这样就清楚了，否则真是一团雾水
个人领样和银行领样，两个类型吧？
永银周苏东(70907255)  16:23:01
嗯嗯，就是两个事
smartman(2054958070)  16:23:38
现在是只要退货就变成已付款了？
永银周苏东(70907255)  16:24:18
还有客户铺货，巡展领样
是的
smartman(2054958070)  16:24:41
实际上是两个事情：
1、部分订单付款状态错误，导致统计不到
2、部分订单虽然统计到了，但是金额为0
永银周苏东(70907255)  16:24:49
对
smartman(2054958070)  16:24:59
这样就清楚了
永银周苏东(70907255)  16:25:31
都是在退货或转销售订单时触发了付款状态
smartman(2054958070)  16:25:42
嗯
永银周苏东(70907255)  16:25:54
可以更简单点，所有单据都判断数量差异
甭管什么类型
smartman(2054958070)  16:26:55
只要有退单，就检查累计退单数量<开单数量，就不能更新订单付款状态？
永银周苏东(70907255)  16:42:22
对
smartman(2054958070)  16:44:16
好的

**Comment by kingofhawks** [comment]
领样销售退库-》确认退库环节修改付款状态

**Comment by kingofhawks** [comment]
检查一下是否有JOB在更新付款状态

**Comment by kingofhawks** [comment]
LY1806151347618768300
