### ISSUE TITLE
到货调拨优化

### ISSUE THREAD

**Issue by poseidon-Liang** [qianlimu/yycoin#504]
测试系统，到货单号：DH201812111426492411394 ；
采购单：SO_CG201812111423637898835；
原因为采购单同一个产品有2个供应商，导致调拨报错：源仓库库存不足。

**Comment by poseidon-Liang** [comment]
自动到货调拨，添加读取t_center_dh_result的sccg_cldz字段，放到OA对应调拨单备注内

**Comment by poseidon-Liang** [comment]
自动到货调拨，添加读取t_center_dh_result的sccg_cldz字段，放到OA对应调拨单备注内
已完成

**Comment by kingofhawks** [comment]
select * from t_center_dh_result where dhno = 'DH201902131017078186789';
生成的DB单号在zjb表中对应错行了
