### ISSUE TITLE
中信导入发票类型问题

### ISSUE THREAD

**Issue by kingofhawks** [qianlimu/yycoin#507]
关于刚才中信导入的问题，没有导入发票类型，但是out表中的类型为17的票子，需要查询下原因
SO1812120912639296332
SO1812120912639296335
SO1812120912639296335
SO1812120912639296320
SO1812120912639296308
这是单号

**Comment by kingofhawks** [comment]
导入开单模板中的开票类型目前未使用。

**Comment by poseidon-Liang** [comment]
目前开单导入是写死的，001发票类型

**Comment by kingofhawks** [comment]
目前开票类型在导入模板中不是必填项，是不是要改成必填项？

**Comment by kingofhawks** [comment]
不用在导入这个环节控制了，在销售单明细里把写死的税率改成取产品主数据t_center_product表中的销项税率就行了

**Comment by kingofhawks** [comment]
duplicate with #600
