### ISSUE TITLE
吉林银行发货模板修改

### ISSUE THREAD

**Issue by poseidon-Liang** [qianlimu/yycoin#516]

**Comment by kingofhawks** [comment]
CK201710091085904016

**Comment by kingofhawks** [comment]
CK201901011438314186

**Comment by kingofhawks** [comment]
问题1：格式没有分开   2：两张订单，因收货人相同，合并发货，但是机构号不同，系统将两个机构号的商品给合并了，仅显示了一个机构号，应该以机构号分开    3：赠品数量不对，收货人相同，合并之后，赠品数量应该对应的是2和4，系统仅显示了一个2
