### ISSUE TITLE
结算价修改

### ISSUE THREAD

**Issue by poseidon-Liang** [qianlimu/yycoin#522]
1.新增批量导入“基础结算价”的功能

2.在维护“总部结算价”的环节，增加一个“是否绑定基础结算价”的判断：
【绑定基础结算价】--同现有逻辑，在基础结算价基础上根据维护的总部结算率计算得到总部结算价
【不绑定基础结算价】--新增一个必填框“总部结算价”，直接读取填写的总部结算价金额
操作路径： |   |  
【手动单个产品操作】OA--公共资源--结算价格管理
【批量导入】OA--公共资源--导入结算价格

**Comment by kingofhawks** [comment]
SO1812301159641791778

**Comment by kingofhawks** [comment]
SOTW1905090909002844890，这张刚在体外入库的，结算价好像没更新

**Comment by kingofhawks** [comment]
SO1905091106661836128,体内这单采购入库，产品是虚料产品，在BASE表里是有虚拟金额，在库存表里没有，结算价也不是0

**Comment by kingofhawks** [comment]
拨报这个错误，然后也没办法撤回申请 ，单号：DB1905091549661859160
DB1905091548661858671

**Comment by kingofhawks** [comment]
DB1905101350662035899

**Comment by kingofhawks** [comment]
DB1905101509662043340
DB1905101508662043147  这两个单号一个通过一个驳回
