### ISSUE TITLE
采购拿货优化

### ISSUE THREAD

**Issue by poseidon-Liang** [qianlimu/yycoin#531]
路径：OA-采购管理-采购拿货，点击拿货，取“采购部-卢工仓区，采购部-马甸仓区，采购部-其他仓区”三个仓区，
新增“生产作业库-采购仓，生产作业库-深圳百吉仓，生产作业库-东莞铭丰仓，生产作业库-其他生产仓，生产作业库-无锡巨洋仓，生产作业库-南京国声仓“几个仓区，
备注：增加时，以仓库-仓区的形式显示，同时将在售仓也修改为”生产作业库-在售仓“  同时修改批量拿货和单独拿货两个功能。

**Comment by kingofhawks** [comment]
INSERT INTO uportal.t_center_depotpart (id, type, name, locationId, description, item) VALUES ('A1201901022042107261', 0, '采购仓', 'A1201705251771966137', '', '体内');
INSERT INTO uportal.t_center_depotpart (id, type, name, locationId, description, item) VALUES ('A1201901022042107271', 0, '深圳百吉仓', 'A1201705251771966137', '', '体内');
INSERT INTO uportal.t_center_depotpart (id, type, name, locationId, description, item) VALUES ('A1201901022042107272', 0, '东莞铭丰仓', 'A1201705251771966137', '', '体内');
INSERT INTO uportal.t_center_depotpart (id, type, name, locationId, description, item) VALUES ('A1201901022042107273', 0, '其他生产仓', 'A1201705251771966137', '', '体内');
INSERT INTO uportal.t_center_depotpart (id, type, name, locationId, description, item) VALUES ('A1201901022042108489', 0, '无锡巨洋仓', 'A1201705251771966137', '', '体内');
INSERT INTO uportal.t_center_depotpart (id, type, name, locationId, description, item) VALUES ('A1201901031042206604', 0, '南京国声仓', 'A1201705251771966137', '', '体内');

**Comment by kingofhawks** [comment]
永银周苏东(70907255) 2019/01/08 09:57:25
就两个选项，仓库，选了仓库出现此仓库的仓区列表，再选，确认完事
永银周苏东(70907255) 2019/01/08 09:58:18
仓库就限制为  生产作业库、采购中心库
仓区不限制
