### ISSUE TITLE
打印优化

### ISSUE THREAD

**Issue by poseidon-Liang** [qianlimu/yycoin#536]
OA--发货管理--拣配查询，“打印回执单”“批量打印”时，如果客户为“紫金农商”的客户，在打印回执单的时候重复打印两份

**Comment by poseidon-Liang** [comment]
广东农信也同样如此

**Comment by kingofhawks** [comment]
CK201903041751216991----紫金农商
CK201903011750860065----广东农信

**Comment by poseidon-Liang** [comment]
拣配查询-打印客户出库单，都是读取的第一条。需要按照复选框选中的行来打印

**Comment by poseidon-Liang** [comment]
异常已解决，两次打印未解决

**Comment by kingofhawks** [comment]
ref #171
