### ISSUE TITLE
采购付款优化

### ISSUE THREAD

**Issue by poseidon-Liang** [qianlimu/yycoin#538]
OA-采购付款申请优化——>原菜单取消，新逻辑: 
财务付款之后通过标识更新t_center_paypool_log对应的outstatus为1

**Comment by kingofhawks** [comment]
是的
采购付款和预付款
现在不从OA走申请了
我这里统一处理，处理完之后财务支付我给OA一个订单，然后财务付款即可
付完款需要给我的中间表改下状态
代表付款结束

**Comment by kingofhawks** [comment]
create table t_center_paypool_log
(
	id int auto_increment
		primary key,
	provider varchar(40) not null,
	type int(1) not null,
	status int(2) not null,
	moneys double not null,
	stockid varchar(40) null,
	stockitemid varchar(40) null,
	changeuser varchar(40) null,
	changetime datetime null,
	remarks varchar(255) null,
	outid varchar(40) null,
	outStatus int(1) null,
	beforeMoneys double null
)
;

**Comment by kingofhawks** [comment]
A120190319124436254048
SF201903201043442481
