### ISSUE TITLE
库存统计优化

### ISSUE THREAD

**Issue by poseidon-Liang** [qianlimu/yycoin#545]
增加需求：
1.在storageralation表增加字段  虚料金额
2.在产品合成，生产经理通过时，检查配件中有无 标识为虚料的配件，如有，将虚料配件的成本累加置为 虚料金额，其他字段取值逻辑不变
 3.在BASE表增加字段  虚料成本，将开单时涉及产品的 虚料金额字段取出置入，其他字段取值逻辑不变
  4.原来的合成或采购时变更结算价的程序，调整为结算价金额为  成本价-虚料价，不用做多级穿刺计算

**Comment by kingofhawks** [comment]
永银周苏东 2019/4/3 14:00:59
简单的来说，就是两点变化，1.库存里 虚料 字段，每次合成时，把虚料类型的配件的成本单独统计写在这个字段里，其他逻辑不变，唯一性判断字段增加虚料字段
永银周苏东 2019/4/3 14:01:23
2.取最新的合成单或采购入库单作为基础结算价
3.在BASE表里把虚料字段值也加进去
smartman 2019/4/3 14:04:51
2还是用之前弄的job吧？
永银周苏东 2019/4/3 14:05:50
2，可以用JOB，不过实时更新应该也可以，没什么数据量
smartman 2019/4/3 14:06:07
嗯
永银周苏东 2019/4/3 14:06:08
1，3应该都是实时的

**Comment by kingofhawks** [comment]
alter table T_CENTER_STORAGERALATION add column virtualPrice double default 0;

**Comment by kingofhawks** [comment]
1、储位表T_CENTER_STORAGERALATION增加虚料字段，并作为唯一性约束条件之一？
2、产品合成变动库存时，把虚料金额作为条件传入，可能存在两种情况：新增库存或修改库存？

**Comment by kingofhawks** [comment]
好，总结一下：
1、储位表T_CENTER_STORAGERALATION增加虚料字段，默认为0，并作为唯一性约束条件之一。
2、产品合成变动库存时，把虚料金额作为条件传入，可能存在两种情况：新增库存或修改库存。
3、虚料类型的配件的成本是检查product表的虚料标志，并把所有虚料配件成本累计。
4、BASE表新增虚料金额字段，在开单时取值于T_CENTER_STORAGERALATION表。
永银周苏东  17:05:46
5.有合成或采购单通过入库时，更新产品成本价-虚料价格作为基础结算价

**Comment by kingofhawks** [comment]
alter table T_CENTER_STORAGERALATION add column virtualPrice double default 0,add column virtualPriceKey varchar(32) default '';

**Comment by kingofhawks** [comment]
结算价没有更新，合成单号A1201904151745628943

**Comment by kingofhawks** [comment]
手工开单提交后就写入成本，导入开单是在商务审批后才写入成本costPrice，在写入成本时候一并把虚料金额写进去。

**Comment by kingofhawks** [comment]
SO1904192117646001105

**Comment by kingofhawks** [comment]
SO1904221751646234415

**Comment by kingofhawks** [comment]
alter table T_CENTER_COMPOSE_ITEM add column virtualPrice double default 0;

**Comment by kingofhawks** [comment]
A1201904271046604949，这单可以合成了，不过结算价里没有把虚料金额去掉

**Comment by kingofhawks** [comment]
A1201904281546708933

**Comment by kingofhawks** [comment]
还有个地方要改下，采购或合成时，如果产品是 虚拟产品，则虚拟金额就等于成本价

**Comment by kingofhawks** [comment]
A1201904301746949127这张合成单测的虚拟产品合成，虚料金额是等于成本金额了，但没改变结算价，结算价应该更新为0的

**Comment by kingofhawks** [comment]
alter table T_CENTER_base add column virtualPrice double default 0,add column virtualPriceKey varchar(32) default '0';

**Comment by kingofhawks** [comment]
1、手工开单多行商品时，不显示虚料金额
2、产品拆分
3、增加入库单时也显示虚料金额

**Comment by kingofhawks** [comment]
alter table T_CENTER_DECOMPOSE add column virtualPrice double default 0;

**Comment by kingofhawks** [comment]
alter table T_CENTER_COMPOSE add column virtualPrice double default 0;

**Comment by kingofhawks** [comment]
调拨还有点问题
调到目的库后，库存表里的虚料金额没了
DB1905112209648274696
