### ISSUE TITLE
财务支付优化

### ISSUE THREAD

**Issue by poseidon-Liang** [qianlimu/yycoin#561]
OA-报销管理-待我处理，在财务支付环节生成的凭证明细，取值为申请报销时填写的申请金额，修改为“待财务审批”时，财务审批时确认的稽核金额。

**Comment by kingofhawks** [comment]
![xx 5 3y 5bss2 g 4la 9x](https://user-images.githubusercontent.com/45868/52679513-4f9c5980-2f70-11e9-8d84-c31c995dcc4c.png)

**Comment by kingofhawks** [comment]
财务支付环节生成的凭证正确，但是JOB生成的凭证有问题。

**Comment by kingofhawks** [comment]
UT201902011446889822

**Comment by kingofhawks** [comment]
UT201902121048150458

**Comment by kingofhawks** [comment]
UT201902121548183251

**Comment by kingofhawks** [comment]
UT201811282337751902

**Comment by kingofhawks** [comment]
最后生成凭证的时候，是根据费用分担来的，不是直接和稽核金额关联的。[图片]
smartman(2054958070)  20:54:01
但系统中分担金额并没有修改，所以还需要自动换算一下才行，最终凭证还是根据人员分担来的。
@永银周苏东 是这样吧？
永银周苏东(70907255)  21:42:57
是的
smartman(2054958070)  21:43:49
恩，就是费用分担的实际总金额要根据稽核金额的总数来，而不是根据报销的总金额，是把？
永银周苏东(70907255)  22:05:46
是的
smartman(2054958070)  22:06:02
好的

**Comment by kingofhawks** [comment]
smartman(2054958070)  22:10:10
我看了下系统里边有些单子的凭证又正确的，是不是手工修改过？
永银周苏东(70907255)  22:10:53
应该是，你看凭证类型是原始还是修改，如果不是原始，就是手工修改过
smartman(2054958070)  22:13:38
恩，确实修改过。

**Comment by kingofhawks** [comment]
UT201902120940848486
