### ISSUE TITLE
导出科目明细带出科目

### ISSUE THREAD

**Issue by poseidon-Liang** [qianlimu/yycoin#584]
OA-税务管理-分类账，导出科目明细时，模板增加一个字段，凭证对应科目，将凭证的对应科目带出来，例如，应收账款的科目，导出的明细将这个对应的科目带出来，例如导出里面原来的应收账款，那么对应的就带出预收账款
![image](https://user-images.githubusercontent.com/39727150/53946734-50ec1c80-40ff-11e9-8c7e-e3e3d46a068f.png)
![image](https://user-images.githubusercontent.com/39727150/53946736-52b5e000-40ff-11e9-943c-d03dfea8657d.png)

**Comment by kingofhawks** [comment]
对应科目是不是可能有多个？

**Comment by kingofhawks** [comment]
凭证科目中，除查询科目外的其他所有科目，都显示出来。
永银-梁惠鹏(524123975)  9:20:52
稍等，我问下具体需求方
smartman(2054958070)  9:21:00
好
永银-梁惠鹏(524123975)  9:30:39
所有科目，导出明细里面的所有凭证对应的科目全部导出
smartman(2054958070)  9:33:11
那我就把所有科目逗号隔开放一个栏位了，这个是动态的
永银-梁惠鹏(524123975)  10:01:01
你可以多个PZ
也可以后面扩列
永银周苏东(70907255)  10:01:22
其实就是导出凭证明细
永银-梁惠鹏(524123975)  10:01:26
对的
永银周苏东(70907255)  10:01:54
把这个科目相关的凭证明细导出来，和正常的凭证明细导出结果一样就行了
smartman(2054958070)  10:34:03
就是我说的这个方式吧
把所有科目逗号隔开放一个栏位了
现在这个导出功能是根据凭证项来的，然后再去找对应凭证下的其他科目。
永银周苏东(70907255)  10:35:59
不是，就是取凭证项对应的PID，然后按凭证管理里导出凭证的格式导出就行了
smartman(2054958070)  10:37:04
那就是一个PID对应多个凭证科目，导出时就是多行，不是增加一个栏位了
，比如这个，就是一个凭证变成多行了，每行一个科目？
永银-梁惠鹏(524123975)  10:39:37
你这样操作也方便啊。直接读取PID都拿出来就好了，EXCEL筛选的时候按PID过滤不就可以了
smartman(2054958070)  10:40:11
就是和你们确认下，是不是改成我刚才说的样子
永银-梁惠鹏(524123975)  10:41:04
按周总说的多行吧
smartman(2054958070)  10:41:23
对啊，我说的就是多行的方式啊
一个凭证变成多行导出，不是新增一个栏位
永银-梁惠鹏(524123975)  10:42:02
按多行
