### ISSUE TITLE
自动异地调拨并且生成发货单

### ISSUE THREAD

**Issue by poseidon-Liang** [qianlimu/yycoin#590]
![Z_VE9VSB@3T5$ GURUAAERU](https://user-images.githubusercontent.com/39727150/54250822-38a55300-4580-11e9-846c-1502b4426262.png)
取status=1的生成调拨单同时生成发货单

**Comment by poseidon-Liang** [comment]
源仓库和成本必须有值才可以生成调拨单，同时newAmount > 0

**Comment by poseidon-Liang** [comment]
生成成功后该状态为2，同时DB单号写入dbno

**Comment by poseidon-Liang** [comment]
体内/体外分别入不同的库。

**Comment by kingofhawks** [comment]
create table t_center_frdb
(
	id int auto_increment
		primary key,
	outid varchar(40) null,
	sys varchar(10) null,
	productid varchar(40) null,
	productname varchar(255) null,
	amount int null,
	mdk varchar(40) null,
	fj varchar(255) null,
	fhfs int(1) null,
	ysfs int(1) null,
	yfpay int(1) null,
	provinceid int null,
	cityid int null,
	adress varchar(255) null,
	receiver varchar(40) null,
	telephone varchar(40) null,
	dutyid varchar(40) null,
	changeuser varchar(40) null,
	changetime datetime null,
	status int(2) null,
	dbno varchar(40) null,
	newAmount int null,
	yck varchar(40) null,
	cb double(12,2) null
)
;

**Comment by kingofhawks** [comment]
alter table t_center_frdb add column errorMessage varchar(128) default '';

**Comment by kingofhawks** [comment]
INSERT INTO uportal.t_center_schedule_job (id, createTime, updateTime, jobName, jobGroup, jobStatus, cronExpression, description, beanClass, isConcurrent, springId, methodName, type) VALUES (560, '2019-03-16 00:00:00', '2019-03-16 00:00:00', 'frDbJob', 'Default', '1', '0 0/1 * * * ?', '异地调拨', 'com.china.center.oa.sail.manager.impl.OutManagerImpl', '0', 'outManager', 'frDbJob', 0);

**Comment by kingofhawks** [comment]
DB1903191603643359436的PS单产品明细看不到仓库

**Comment by poseidon-Liang** [comment]
调拨已完成，CK单未生成
