### ISSUE TITLE
新增商务销售赠品绑定关系以及审批过单

### ISSUE THREAD

**Issue by poseidon-Liang** [qianlimu/yycoin#593]
商务批量通过SO的时候，把关联的赠送单也一起审批通过。
赠品不足的时候，提示赠品不足，不允许审批通过。
赠送单状态只允许为待商务审批，否则也报错，赠品单状态不是待商务审批。

**Comment by kingofhawks** [comment]
如果赠送单报错，那对应的SO单，是不是也不允许审批通过呢？

**Comment by poseidon-Liang** [comment]
中间表 t_center_sw_oano；过单的时候抓下这个表的记录

**Comment by poseidon-Liang** [comment]
![image](https://user-images.githubusercontent.com/39727150/54904237-f59c9580-4f18-11e9-9c42-4820a3c43e44.png)

**Comment by poseidon-Liang** [comment]
待库管也类似上面，一起批量待下去

**Comment by kingofhawks** [comment]
SO1904040909644728889

**Comment by yanglu-china** [comment]
1、审批过单包括单独的待商务审批和批量审批过单；
2、只要绑定了，主体是什么状态不管是驳回还是通过都跟着赠品就是什么状态（主体过完待商务时开发票，系统自动过待库管的时候，赠品也跟着主体一起）；
3.不管是待商务还是待库管，只要取消绑定了，赠品就跟主体没关系，比如，我在待商务的时候是绑定关系，然后到了待库管，我取消了绑定关系，那么我过主体单子的待库管的时候，我的赠送单就不跟着主体单自动下去；
4、赠品不足的时候，提示赠品不足，赠品不足的时候，提示赠品不足，不允许审批通过（除非取消绑定关系）；
5、赠送单状态只允许为待商务审批，否则也报错，赠品单状态不是待商务审批。

**Comment by kingofhawks** [comment]
@周苏东 @杨露 赠品过单的问题再和你们确认一下：
1、确保赠品和对应销售单的状态是一致的
2、审批动作包括通过和驳回
3、手工过单和批量过单都要改
4、商务审批和库管审批环节都要改
是这样吧啊？
周苏东(70907255)  20:16:58
对

**Comment by kingofhawks** [comment]
SO1907081703650437195

**Comment by kingofhawks** [comment]
赠品过单时，参考CK单合并，根据收货人、号码、地址三者一致。
