### ISSUE TITLE
处理历史优化

### ISSUE THREAD

**Issue by poseidon-Liang** [qianlimu/yycoin#610]
![image](https://user-images.githubusercontent.com/39727150/54898900-eca3c800-4f08-11e9-92f9-20457ebbee41.png)
![image](https://user-images.githubusercontent.com/39727150/54898905-ee6d8b80-4f08-11e9-8714-9328f4db634d.png)

跟时间一样，读取自己名下最新历史日志的审批动作结果。

**Comment by 39189058** [comment]
add 2views, refer to portal/db/view.sql

CREATE or REPLACE VIEW v_center_tcpstatus
AS
SELECT id, `type`, `status`, `status` AS name, 'apply' AS tablename FROM t_center_tcpapply
union
SELECT id, `type`, `status`, `status` AS name, 'expense' AS tablename FROM t_center_tcpexpense;

CREATE or REPLACE VIEW v_center_tcphandlehis
AS
SELECT his.*,st.`status`,st.tablename
FROM t_center_tcphandlehis his
LEFT JOIN v_center_tcpstatus st on (st.id=his.refId and st.type=his.type);

**Comment by kingofhawks** [comment]
CREATE or REPLACE VIEW v_center_tcphandlehis
AS
SELECT his.*,
CASE 
WHEN (his.type>10 AND his.type<=20 AND NOT(exp.status is NULL)) THEN exp.status
ELSE app.status
END AS status
FROM t_center_tcphandlehis his
LEFT JOIN t_center_tcpapply app on (app.id=his.refId and app.type=his.type)
LEFT JOIN t_center_tcpexpense exp on (exp.id=his.refId and exp.type=his.type);

**Comment by kingofhawks** [comment]
CREATE or REPLACE VIEW v_center_tcphandlehis
AS
SELECT his.*,
CASE 
WHEN (his.type>10 AND his.type<=20 AND NOT(exp.status is NULL)) THEN exp.status
ELSE app.status
END AS status
FROM t_center_tcphandlehis his
LEFT JOIN t_center_tcpapply app on (app.id=his.refId and app.type=his.type)
LEFT JOIN t_center_tcpexpense exp on (exp.id=his.refId and exp.type=his.type);

**Comment by kingofhawks** [comment]
SELECT his.*,
CASE 
WHEN (his.type<=10) THEN app.status
WHEN (his.type>10 AND his.type<=20) THEN exp.status
WHEN (his.type=21) THEN reb.status
WHEN (his.type=22) THEN pre.status
ELSE bac.status
END AS status
FROM t_center_tcphandlehis his
LEFT JOIN T_CENTER_TRAVELAPPLY app on (app.id=his.refId and app.type=his.type)
LEFT JOIN T_CENTER_TCPEXPENSE exp on (exp.id=his.refId and exp.type=his.type)
LEFT JOIN T_CENTER_REBATE reb on (reb.id=his.refId and reb.type=his.type)
LEFT JOIN T_CENTER_PREINVOICE pre on (pre.id=his.refId and pre.type=his.type)
LEFT JOIN T_CENTER_BACKPREPAY_APPLY bac on (bac.id=his.refId and bac.type=his.type)

**Comment by kingofhawks** [comment]
CREATE or REPLACE VIEW v_center_tcphandlehis
AS
SELECT his.*,
CASE 
WHEN (his.type<=10) THEN app.status
WHEN (his.type>10 AND his.type<=20) THEN exp.status
WHEN (his.type=21) THEN reb.status
WHEN (his.type=22) THEN pre.status
ELSE bac.status
END AS status
FROM t_center_tcphandlehis his
LEFT JOIN T_CENTER_TRAVELAPPLY app on (app.id=his.refId and app.type=his.type)
LEFT JOIN T_CENTER_TCPEXPENSE exp on (exp.id=his.refId and exp.type=his.type)
LEFT JOIN T_CENTER_REBATE reb on (reb.id=his.refId and reb.type=his.type)
LEFT JOIN T_CENTER_PREINVOICE pre on (pre.id=his.refId and pre.type=his.type)
LEFT JOIN T_CENTER_BACKPREPAY_APPLY bac on (bac.id=his.refId and bac.type=his.type);
