### ISSUE TITLE
供应商优化

### ISSUE THREAD

**Issue by poseidon-Liang** [qianlimu/yycoin#615]
类似仓库打标识，区分体内，体外，国华体内，全部，目前这4个类型；
之后所有的供应商都再体内新建，各个系统负责修改自己的。

**Comment by 39189058** [comment]
database scripts:
alter table t_center_provide add item varchar(64) default '体内';
alter table t_center_provide_bak add item varchar(64) default '体内';
alter table t_center_provide_his add item varchar(64) default '体内';
