### ISSUE TITLE
体外转移客户异常

### ISSUE THREAD

**Issue by poseidon-Liang** [qianlimu/yycoin#618]
目前体内OA中，如果订单未付款，在转移客户的时候，订单会随着客户转移到新的业务员名下，例如：SO1903111500652448374，现在发现体外OA未付款的订单，在客户转移后，订单没有一起转移到新业务员名下，例如：SOTW1903181648002694030
![image](https://user-images.githubusercontent.com/39727150/55380979-70d2fc80-5554-11e9-91cb-25489e578ccf.png)
![image](https://user-images.githubusercontent.com/39727150/55380981-73355680-5554-11e9-9207-bd609f10ba38.png)
![image](https://user-images.githubusercontent.com/39727150/55380984-74668380-5554-11e9-8a82-e0db44ce9468.png)

**Comment by kingofhawks** [comment]
体外T_CENTER_APPROVELOG表未查到“变更单据提交人”的日志

**Comment by kingofhawks** [comment]
ClientManagerImpl.batchTransCustomer()

**Comment by kingofhawks** [comment]
本地和体外测试无法重现，需要在生产体外测试一下才行。
