### ISSUE TITLE
帆软订单提报线下订单生成时多加一个逻辑+帆软开单和OA中信端口开单读取

### ISSUE THREAD

**Issue by yanglu-china** [qianlimu/yycoin#625]
OA优化：
1：帆软订单提报线下订单生成时，原逻辑为通过olbase的productimprotid 关联在售表，关联不到，系统报错。现在要多加一个逻辑，通过olbase的productimprotid先关联在售表，如果id匹配不到，则关联产品表id，银行产品名为OA品名，如果在关联不到，则报错。
2：帆软开单和OA中信端口开单，读取在售表数据的产品的订单，OA出库单数量等于折算系数*开单数量。读取非在售表产品数据的订单，OA出库数量等于开单数量，发货单品名为：OA产品名称

**Comment by yanglu-china** [comment]
非在售表产品数据的订单，OA出库数量等于开单数量，读取非在售表生成的订单，发货单品名为：OA产品名称，数量等于折算系数*开单数量  最后面这句话是新加的

**Comment by yanglu-china** [comment]
非在售表产品数据的订单，OA出库数量等于开单数量，读取非在售表生成的订单，发货单品名为：OA产品名称，数量等于折算系数*开单数量

**Comment by yanglu-china** [comment]
读取非在售表产品数据的订单，OA出库数量等于开单数量，发货单品名为：OA产品名称

**Comment by kingofhawks** [comment]
alter table T_CENTER_PRODUCT_IMPORT add column rated double default 1;

**Comment by kingofhawks** [comment]
体内测试没问题，体外测试，数量没有乘折算系数，另外体外OA生成的订单，有的不带tw，例如订单号：SO1904181535002839016

**Comment by kingofhawks** [comment]
导入开单和手工开单也要乘以折算系数

**Comment by kingofhawks** [comment]
体外的我又试了一次，帆软订单提报和OA批量导入订单，数量还是没有生成折算系数，现在发现的问题是：在olbase表有productimportID，但是到base表就没有productimportID，是不是因为没有拿到这个id，导致匹配不到主数据？例如订单：SOTW1904190944002841053，你看下呢

**Comment by kingofhawks** [comment]
你这id不对吧，你看我的模板里面，商品编码和商品名称对应的在售表里面的数据id：20190318112305128，但是你生成的订单，productImportId是：2019032510092028 
[图片]
Red Hat(1079827851) 2019/04/19 12:51:06
我刚刚又导入了一条，productImportId有了，但是对应的id也不对，SOTW1904191247002841259
这个是导入模板，对应的productImportId应该是：2019031811230595

**Comment by kingofhawks** [comment]
数量＝原数量＊折算系数，单价＝原单价／折算系数
