### ISSUE TITLE
中原银行贵金属交接单打印优化：按照顾客姓名合并打印

### ISSUE THREAD

**Issue by yanglu-china** [qianlimu/yycoin#626]
1.附件为当前中原银行贵金属交接单打印页面，需要在现有基础上优化为：一个顾客姓名就直接合并打印一张贵金属交接单，如果有多个顾客姓名就分开打印多份贵金属交接单
2.本优化调整针对整个中原银行

**Comment by yanglu-china** [comment]
![image](https://user-images.githubusercontent.com/49268537/58074316-95079d00-7bd7-11e9-96b5-8cf7a9a106dc.png)

**Comment by kingofhawks** [comment]
CK201904111157358217

**Comment by kingofhawks** [comment]
<c:if test="${varStatus.last}">
      <div>
    </c:if>
    <c:if test="${!varStatus.last}">
      <div style="page-break-after: always;">
    </c:if>
