### ISSUE TITLE
增加新审批流“特殊流程报销”

### ISSUE THREAD

**Issue by yanglu-china** [qianlimu/yycoin#627]
增加新审批流“特殊流程报销”，此流程审批流为：
提交人—提交人中心负责人—承担人中心负责人—财务审批—财务支付—结束

提交人中心负责人，通过提交人用户名到bankbu_level找name字段相同的行，取managerid为下一环节人
承担人中心负责人，通过承担人用户名到bankbu_level找name字段相同的行，取managerid，并去除重复的处理人为下一环节共同处理人，全部承担人的中心负责人处理完成后，转至财务审批环节。

**Comment by 39189058** [comment]
部署需执行脚本db/upgrade627.sql

**Comment by 39189058** [comment]
增加新审批流“特殊流程报销”，此流程审批流为：
提交人—提交人中心负责人—承担人中心负责人—财务审批—财务支付—结束

提交人中心负责人，通过提交人id到bankbu_level找id字段相同的行，取managerid为下一环节人
承担人中心负责人，通过承担人id到bankbu_level找id字段相同的行，取managerid，并去除重复的处理人为下一环节共同处理人，全部承担人的中心负责人处理完成后，转至财务审批环节。

改用id匹配
