### ISSUE TITLE
修改现在的报销申请审批流

### ISSUE THREAD

**Issue by yanglu-china** [qianlimu/yycoin#628]
在确认承担人直属上级处理人时，通过承担人用户名到bankbu_level找name字段相同的行，判断sybname的字段值，分为以下三种情况
	Sybname字段值不包含“事业部”或等于“渠道事业部”字符时，审批流照旧
	Sybname字段值等于“终端事业部”字符时，承担人直属上级处理人为manager字段值
	Sybname字段值等于“银行事业部”字符时，按sybmanager--manager—regionaledirector—regionalmanager—provincemanager的顺序查找提交人，如在任意一个级别，则承担人直属上级处理人为其前一字段人员，下一环节审批后至财务审批；
如在以上环节中未找到提交人，提交人只存在NAME字段时，则按provincemanager与regionalmanager共同审批后再到财务环节。

**Comment by 39189058** [comment]
在确认承担人直属上级处理人时，通过承担人id到bankbu_level找id字段相同的行，

用id匹配

**Comment by 39189058** [comment]
周总更新
1.1、提报人为“id/provincemanagerid”时，审批人直接流转到“regionalmanagerid”名下审批；
1.2、提报人为“regionalmanagerid/managerid/sybmanagerid”时，审批人流转到“managerid/sybmanagerid/zcid” 三个前后是一一对应的；

**Comment by 39189058** [comment]
经整理，本条需求描述更新如下：
一、	确定提交人直属上级处理人
1.提报人为“id/provincemanagerid”时，审批人直接流转到“regionalmanagerid”名下审批；
2.提报人为“regionalmanagerid/managerid/sybmanagerid”时，审批人流转到“managerid/sybmanagerid/zcid” 三个前后是一一对应的；

二、确认承担人直属上级处理人
通过承担人用户名到bankbu_level找name字段相同的行，判断sybname的字段值，分为以下三种情况
1. Sybname字段值不包含“事业部”或等于“渠道事业部”字符时，审批流照旧
2. Sybname字段值等于“终端事业部”字符时，承担人直属上级处理人为manager字段值
3.Sybname字段值等于“银行事业部”字符时，按sybmanager--manager—regionaledirector—regionalmanager—provincemanager的顺序查找承担人，如在任意一个级别，则承担人直属上级处理人为其前一字段人员，下一环节审批后至财务审批；如在以上环节中未找到承担人，承担人只存在NAME字段时，则按provincemanager与regionalmanager共同审批后再到财务环节。

**Comment by kingofhawks** [comment]
alter table t_center_bankbu_level add column sybmanager varchar(25) default null,add column sybmanagerId varchar(25) default null,add column sybname varchar(40) default null,add column zc varchar(64) default null,add column zcId varchar(64) default null;

**Comment by 39189058** [comment]
一、确定提交人直属上级处理人
1 提报人为“id/provincemanagerid”时，审批人直接流转到“regionalmanagerid”名下审批；
2 提报人为“regionalmanagerid/managerid/sybmanagerid”时，审批人流转到“managerid/sybmanagerid/zcid” 三个前后是一一对应的；
3 如在以上环节中未找到提交人，提交人只存在NAME字段时，则按provincemanager与regionalmanager共同审批后再到财务环节。

二、确认承担人直属上级处理人
通过承担人用户名到bankbu_level找name字段相同的行，判断sybname的字段值，分为以下三种情况
l	Sybname字段值不包含“事业部”或等于“渠道事业部”字符时，审批流照旧
l	Sybname字段值等于“终端事业部”字符时，承担人直属上级处理人为manager字段值
l	Sybname字段值等于“银行事业部”字符时，按sybmanager--manager—regionaledirector—regionalmanager—provincemanager的顺序查找提交人，如在任意一个级别，则承担人直属上级处理人为其前一字段人员，下一环节审批后至财务审批；

**Comment by 39189058** [comment]
一、确定提交人直属上级处理人
1 提报人为“id/provincemanagerid”时，审批人直接流转到“regionalmanagerid”名下审批；
2 提报人为“regionalmanagerid/managerid/sybmanagerid”时，审批人流转到“managerid/sybmanagerid/zcid” 三个前后是一一对应的；
3 如在以上环节中未找到提交人，提交人只存在NAME字段时，则按provincemanager与regionalmanager共同审批后再到财务环节。(这一条有点疑问)

二、确认承担人直属上级处理人
通过承担人用户名到bankbu_level找name字段相同的行，判断sybname的字段值，分为以下三种情况
l	Sybname字段值不包含“事业部”或等于“渠道事业部”字符时，审批流照旧
l	Sybname字段值等于“终端事业部”字符时，承担人直属上级处理人为manager字段值
l	Sybname字段值等于“银行事业部”字符时，按sybmanager--manager—regionaledirector—regionalmanager—provincemanager的顺序查找提交人，
如在任意一个级别，则承担人直属上级处理人为其前一字段人员，下一环节审批后至财务审批；
承担人上级的审批流略有调整，如果承担人的最高层级为provincemanager和NAME时，只跳转到regionaledirector这个角色人审批，其他层级还是依次为上一环节审批人
