### ISSUE TITLE
虚拟订单标识更新及黑名单统计处理 

### ISSUE THREAD

**Issue by yanglu-china** [qianlimu/yycoin#629]
1.在订单导入模板中增加“虚拟订单”字段，字段值可以为空，有值时必须为“是或否”，生成订单时将OUT表中virtualstatus字段值设为1；
2.退单时将前续单据的virtualstatus字段值复制到退单中；
3.黑名单统计程序统计数据时，将OUT表中virtualstatus字段值为1 的订单排除在外；
4. 虚拟订单的处理过程和正常订单一致；
5.增加应收商品数量统计，此统计不涉及金额，只统计数量，包括所有订单，不区分是否为虚拟订单；
6.可以考虑在现有程序上新增虚拟标识，只在前端输出中区分为两个类型输出；

**Comment by kingofhawks** [comment]
3.黑名单统计程序统计数据时，将OUT表中virtualstatus字段值为1 的订单排除在外；
退单virtualstatus字段值为1 的订单也要排除在外吧？

**Comment by kingofhawks** [comment]
alter table t_center_out_import add column virtualstatus int(11) default 0;
alter table t_center_out_out add column virtualstatus int(11) default 0;
