### ISSUE TITLE
 OA发货清单（打印回执单）优化需求

### ISSUE THREAD

**Issue by yanglu-china** [qianlimu/yycoin#632]
OA发货清单（打印回执单）优化需求：OA发货清单需修改一个逻辑：发货清单里面的数量等于原始开单数量，不在乘折算系数（折算系数仅生成订单时的数量等于折算系数*原始开单数量）

**Comment by kingofhawks** [comment]
ref #625 折算系数

**Comment by kingofhawks** [comment]
alter table T_CENTER_PACKAGE_ITEM add column productImportId varchar(32) default null;

**Comment by kingofhawks** [comment]
smartman(2054958070)  20:18:04
@李雪伶 这个折算涉及到所有银行吗？
现在打印回执单不同银行代码也都不太一样
李雪伶(1079827851)  20:22:56
跟银行没关系，不考虑银行的，只涉及到在售表里面，银行名称为钱币拍卖的

**Comment by kingofhawks** [comment]
SO1904301339646932139

**Comment by kingofhawks** [comment]
SOTW1904301702002873046

**Comment by kingofhawks** [comment]
SOTW1905051402002881823

**Comment by kingofhawks** [comment]
钱币拍卖客户的单子，开单数量没有×折算系数，例如订单：SO1905062125661337610   读取的productimprotid是：201905062110101
