### ISSUE TITLE
东莞农商贵金属库存管理需求表

### ISSUE THREAD

**Issue by yanglu-china** [qianlimu/yycoin#639]
[东莞.zip](https://github.com/qianlimu/yycoin/files/3159885/default.zip)

**Comment by kingofhawks** [comment]
1、针对东莞农商行，批量打印时多打印一张单子。

**Comment by kingofhawks** [comment]
2、t_center_branch_relation，要在这表里加个一级分行字段

**Comment by kingofhawks** [comment]
refer to https://github.com/kingofhawks/yycoin/issues/45

**Comment by kingofhawks** [comment]
东莞农商的打印就按一张CK单打印一张接收单的方式处理，因为CK单是按收货地址合并的，同一个一级支行收货，地址信息是一样的

**Comment by kingofhawks** [comment]
alter table T_CENTER_BRANCH_RELATION add column yjzh varchar(32) default '';

**Comment by kingofhawks** [comment]
CK201905141748614184
CK201905141748614182
永银周苏东 2019/05/14 19:16:51
商品能带出来，但是没有放在一个单子上
