### ISSUE TITLE
报销异常：无审批人

### ISSUE THREAD

**Issue by yanglu-china** [qianlimu/yycoin#640]
通用费用报销，UT201905052161171447，该单显示是“承担人直属上级审批”状态，但是“处理人”为空，需要看下什么原因导致
![image](https://user-images.githubusercontent.com/49268537/57756577-25e8ff00-7726-11e9-9839-a2afb4b62d19.png)

**Comment by 39189058** [comment]
已让流程走下去。对于造成这一问题的原因，还会继续查找。代码里面会加一些检查。

![image](https://user-images.githubusercontent.com/28384119/57777705-0ae1b380-7755-11e9-92f7-9182a5daf2c8.png)
