### ISSUE TITLE
应收统计异常

### ISSUE THREAD

**Issue by yanglu-china** [qianlimu/yycoin#641]
YL1905081601661671626，该单5月8日已出库，并且不存在退货，在应收统计明细中没有统计在内，需要看下什么原因导致；
LY1811231443637071690应收显示还有两个，实际查的这个订单退了4个，应该只剩余1
![企业微信截图_15579040724034](https://user-images.githubusercontent.com/49268537/57756662-4fa22600-7726-11e9-8169-06b2c7032241.png)
![`F}GA9A4@4DR6{F~(4%_1XE](https://user-images.githubusercontent.com/49268537/57756678-56309d80-7726-11e9-987b-dd805ee3b9a3.png)

**Comment by kingofhawks** [comment]
YL1905081601661671626的virtualStatus=null,未统计到。
LY1811231443637071690无法重现。

**Comment by kingofhawks** [comment]
SO1902200916649415612，这单在t_center_black_out和t_center_black_out_detail的金额不一样
out表里的总金额不等于detail表里的金额*数量

**Comment by kingofhawks** [comment]
INSERT INTO uportal.t_center_out (id, fullId, flowId, outTime, managerTime, outType, channel, locationID, location, industryId, industryId2, department, customerId, description, total, hadPay, badDebts, status, type, hasInvoice, invoiceStatus, invoiceId, dutyId, mark, pay, inway, tempType, customerName, phone, stafferName, connector, checks, reday, arriveDate, redate, depotpartId, destinationId, tranNo, refOutFullId, stafferId, managerId, reserve1, reserve2, reserve3, reserve4, reserve5, reserve6, reserve7, reserve8, reserve9, invoiceMoney, curcredit, staffcredit, managercredit, checkStatus, badDebtsCheckStatus, changeTime, mtype, sailType, productType, ratio, vtype, vtypeFullId, pmtype, industryId3, payTime, forceBuyType, eventId, refBindOutId, promValue, promStatus, lastModified, operator, operatorName, logTime, guarantor, feedBackVisit, feedBackCheck, taxTotal, hasRebate, piDutyId, piMtype, piType, piStatus, hasConfirm, hasConfirmInsMoney, emergency, presentFlag, podate, ibFlag, motivationFlag, remoteAllocate, reason, transportNo, swbz, outbackStatus, customerCreated, flowTime, ibApplyId, motivationApplyId, refGiftId, profigflag, cashflag, ibFlag2, ibApplyId2, motivationFlag2, motivationApplyId2, customerDescription, delivery, posPayer, recommendation, platformFlag, platformApplyId, virtualstatus) VALUES (649415612, 'SO1902200916649415612', 'CITIC', '2019-02-20', '2019-02-20 11:28:13', 0, '', 999, '99000000000000000002', '180301084', '180301050', '', '10804417', '陆运___线下单号___D536596201902200901', 133500, 0, 0, 4, 0, 0, 0, '90000000000000000037', '90201008080000000001', 0, 0, 0, 0, '北京永特365商务有限公司', '', '张皓', '', '', '0', '2019-02-20', '2019-02-20', '1', '0', '', '', '536596', '', 0, 0, 2, '', '', '', '', '', '', 0, 0, 0, 0, 0, 0, '2019-02-20 11:28:43', 0, '', '', '', 0, '', 0, '180301014', '', -1, '', '', 0, -1, '', '', '系统', '2019-02-20 09:16:49', '', 0, 0, 0, 0, '', -1, -1, -1, 0, 0, 0, 9, '2019-02-20', 0, 0, 0, '', '', '特殊需求：跨越陆运', '', 0, '2019-02-20 11:28:44', '', '', '', 0, 0, 0, '', 0, '', '', '', '', '', 0, '', 0);
INSERT INTO uportal.t_center_out (id, fullId, flowId, outTime, managerTime, outType, channel, locationID, location, industryId, industryId2, department, customerId, description, total, hadPay, badDebts, status, type, hasInvoice, invoiceStatus, invoiceId, dutyId, mark, pay, inway, tempType, customerName, phone, stafferName, connector, checks, reday, arriveDate, redate, depotpartId, destinationId, tranNo, refOutFullId, stafferId, managerId, reserve1, reserve2, reserve3, reserve4, reserve5, reserve6, reserve7, reserve8, reserve9, invoiceMoney, curcredit, staffcredit, managercredit, checkStatus, badDebtsCheckStatus, changeTime, mtype, sailType, productType, ratio, vtype, vtypeFullId, pmtype, industryId3, payTime, forceBuyType, eventId, refBindOutId, promValue, promStatus, lastModified, operator, operatorName, logTime, guarantor, feedBackVisit, feedBackCheck, taxTotal, hasRebate, piDutyId, piMtype, piType, piStatus, hasConfirm, hasConfirmInsMoney, emergency, presentFlag, podate, ibFlag, motivationFlag, remoteAllocate, reason, transportNo, swbz, outbackStatus, customerCreated, flowTime, ibApplyId, motivationApplyId, refGiftId, profigflag, cashflag, ibFlag2, ibApplyId2, motivationFlag2, motivationApplyId2, customerDescription, delivery, posPayer, recommendation, platformFlag, platformApplyId, virtualstatus) VALUES (658414142, 'XT1904170956658414142', '', '2019-04-17', '', 5, '', 999, '99000000000000000002', '180301084', '180301050', '', '10804417', '销售退库,销售单号:SO1902200916649415612. 1', 90780, 0, 0, 3, 1, 0, 0, '90000000000000000037', '90201008080000000001', 0, 1, 0, 0, '北京永特365商务有限公司', '', '张皓', '', '', '0', '', '', '', '0', '', 'SO1902200916649415612', '536596', '', 0, 0, 0, '', '', '', '', '', '', 0, 0, 0, 0, 0, 0, '2019-04-17 11:30:04', 1, '', '', '', 0, '', 1, '180301014', '', -1, '', '', 0, -1, '', '455013144', '田月琴', '', '', 0, 0, 0, 0, '', -1, -1, -1, 0, 0, 0, 0, '2019-04-17', 0, 0, 0, '', '7620853198', '', '', 0, '2019-04-17 11:30:04', '', '', '', 0, 0, 0, '', 0, '', '', '', '', '', 0, '', 0);
INSERT INTO uportal.t_center_base (id, inway, productId, unit, amount, price, costPrice, costPriceKey, value, owner, ownerName, locationId, description, productName, showName, showId, outId, storageId, depotpartName, depotpartId, inputPrice, mtype, invoiceMoney, pprice, iprice, deliverType, expressPay, transportPay, profit, profitRatio, oldGoods, taxrate, tax, inputRate, refId, ibMoney, motivationMoney, profitmoney, grossProfit, checkgrossProfit, cash, ibMoney2, motivationMoney2, platformFee, productImportId, ykibMoney, cash2, virtualPrice, virtualPriceKey) VALUES (649436626, 0, '629467355', '套', 50, 2670, 2128.81, '212881', 133500, '0', '公共', '99000000000000000002', '', 'YZ0371400 盛世中华中国经典钱币邮票珍藏套装（封装版）（普16）', '', '', 'SO1902200916649415612', '', '可发成品仓', '1', 2074, 0, 0, 2074, 2074, 0, -1, -1, 29800, 0.22322097378277153, -1, 0.17, 0, 0, '', 0, 270, null, 0, null, 0, 0, 0, 0, '201812141720241', 0, null, 0, '0');
INSERT INTO uportal.t_center_base (id, inway, productId, unit, amount, price, costPrice, costPriceKey, value, owner, ownerName, locationId, description, productName, showName, showId, outId, storageId, depotpartName, depotpartId, inputPrice, mtype, invoiceMoney, pprice, iprice, deliverType, expressPay, transportPay, profit, profitRatio, oldGoods, taxrate, tax, inputRate, refId, ibMoney, motivationMoney, profitmoney, grossProfit, checkgrossProfit, cash, ibMoney2, motivationMoney2, platformFee, productImportId, ykibMoney, cash2, virtualPrice, virtualPriceKey) VALUES (658414143, 0, '629467355', '套', 34, 2670, 2128.81, '212881', 90780, '0', '公共', '99000000000000000002', '2128.81', 'YZ0371400 盛世中华中国经典钱币邮票珍藏套装（封装版）（普16）', '', '', 'XT1904170956658414142', '', '可发成品仓', '1', 2074, 1, 0, 2074, 2074, -1, -1, -1, 0, 0, -1, 0, 0, 0, '', 0, 270, null, 0, null, 0, 0, 0, 0, '', 0, 0, 0, '0');
