### ISSUE TITLE
订单信息异常

### ISSUE THREAD

**Issue by yanglu-china** [qianlimu/yycoin#644]
【异常类型】订单信息相关异常
【异常描述】SO1808281544628399395，这单根据下面的开票明细统计出的开票金额是71920，但是订单明细中“开票金额”显示为29760，两边存在差异，想问下这个29760的开票金额是如何计算得来的
![P RI)CD5MYZ$ VINNAQEO16](https://user-images.githubusercontent.com/49268537/57913313-ee618a80-78be-11e9-8f86-54e513bfde4e.png)

**Comment by kingofhawks** [comment]
从代码逻辑看应该是等于所有已开票金额之和71920，看不出来为何会是29760.
