### ISSUE TITLE
报销凭证异常

### ISSUE THREAD

**Issue by yanglu-china** [qianlimu/yycoin#645]
体内OA，通用费用报销单号： UT201904151458084480 、UT201904071956834777，在4月26号流程已经审批结束，但是只生成了一个凭证，缺少一张费用凭证
![企业微信截图_15584101943376](https://user-images.githubusercontent.com/49268537/58078460-62fb3880-7be1-11e9-91ef-bed16e8ce440.png)
目前已手工添加凭证，麻烦查一下具体原因

**Comment by 39189058** [comment]
我们4月做过一个变更“报销申请中现在的系统JOB生成的凭证在 财务审批通过时就生成例 #622”，把凭证生成的节点提前了。如果当时有些报销流程已经“财务审批通过”，这样它再往下走就不会生成了。我看了下#622是4月24日左右close的，时间上和那两条有问题的差不多。如果还有其他单子在系统升级时，刚好处于“待财务支付”状态的，可能会有同样问题。
我看了下，还有好多在我们系统更新之前已经处于“待财务支付”状态。那个生成凭证的job可能暂时还不能停。
