### ISSUE TITLE
批量转移客户相关异常

### ISSUE THREAD

**Issue by yanglu-china** [qianlimu/yycoin#648]
体内OA，客户关系管理--批量转移客户，有如图所示报错，重新从系统下载新模板也是一样报错，另外，导入文件中“现业务员、新业务员”均没有“专员-高丽婷-三部”，但是报错提示是“专员-高丽婷-三部”
![企业微信截图_15584904343291](https://user-images.githubusercontent.com/49268537/58142373-588c7d80-7c79-11e9-967a-0d836a25d308.png)

**Comment by kingofhawks** [comment]
富滇银行昆明金实支行-银行
专员-骆晨曦-三部
