### ISSUE TITLE
报销关联异常

### ISSUE THREAD

**Issue by yanglu-china** [qianlimu/yycoin#649]
![image](https://user-images.githubusercontent.com/49268537/58222859-07988a00-7d4a-11e9-9bc3-a0206beb6862.png)
![image](https://user-images.githubusercontent.com/49268537/58222880-2008a480-7d4a-11e9-96f3-d0905ef55ceb.png)
报销单号：UT201904170858403337、 关联申请单号UT201903151653155558，目前申请单显示未关联，麻烦查一下

**Comment by 39189058** [comment]
![image](https://user-images.githubusercontent.com/28384119/58370888-5dce1e80-7f3e-11e9-8ca4-51413a73b01d.png)
把onEndExpenseApplyJob临时开启后，报销和申请关联起来了。经查看代码，关联申请这个是在生成凭证的时候做的。
