### ISSUE TITLE
OA产品合成异常

### ISSUE THREAD

**Issue by yanglu-china** [qianlimu/yycoin#650]
提交产品合成，审批时报错，配件是有库存的，合成单号：A1201905241164181463，产品名：YZ0512900 时代印记45福字-15Z-4T纪念册（SD版）（普13）
![QQ浏览器截图20190524113016](https://user-images.githubusercontent.com/49268537/58304539-45b7ab80-7e27-11e9-8eca-1fe624274a0d.png)

**Comment by kingofhawks** [comment]
库存不足
