### ISSUE TITLE
体内OA产品合成异常

### ISSUE THREAD

**Issue by yanglu-china** [qianlimu/yycoin#655]
提交产品合成，审批时报错，配件是有库存的，合成单号：A1201905271664683943，产品名：YZ0481100 钱到家笔筒含10克银章（浦发版），请看下什么原因 
![1(1)](https://user-images.githubusercontent.com/49268537/58408727-faa8cd00-80a0-11e9-8e68-67958b4a9d1a.png)
![QQ浏览器截图20190527164434](https://user-images.githubusercontent.com/49268537/58408728-fc729080-80a0-11e9-8434-c2185b8510c2.png)

**Comment by yanglu-china** [comment]
提交产品合成，审批时报错，配件是有库存的，合成单号：A1201905271664688440
![企业微信截图_15589538029222](https://user-images.githubusercontent.com/49268537/58414894-5b3f0680-80af-11e9-93ea-f711f1a3ec44.png)

**Comment by kingofhawks** [comment]
YZ0462804 钱到家笔筒含10克银章（浦发版）-笔筒（普16）(647030050)
