### ISSUE TITLE
发票相关异常

### ISSUE THREAD

**Issue by yanglu-china** [qianlimu/yycoin#657]
O1905281829664806204销售单发票没有ck单，发票标识：A1201905281464746620，虚拟发票号XN201905281464746624 
![image](https://user-images.githubusercontent.com/49268537/58523092-b844d480-81f5-11e9-9831-40d6891a563e.png)

**Comment by kingofhawks** [comment]
CK201905291264983808

**Comment by kingofhawks** [comment]
CK201905290864965138
