### ISSUE TITLE
中原银行发货单异常

### ISSUE THREAD

**Issue by yanglu-china** [qianlimu/yycoin#659]
同一批次中，其他发货单打印都正常，但中原银行发货单打印界面出不来，单号：CK201905291564992243 
![企业微信截图_1559117913287](https://user-images.githubusercontent.com/49268537/58541228-9c5d2500-822d-11e9-8bcf-ef7653a313f1.png)
![企业微信截图_15591177932259](https://user-images.githubusercontent.com/49268537/58541233-9e26e880-822d-11e9-8a3c-21d13501ef8c.png)
![企业微信截图_15591177726414](https://user-images.githubusercontent.com/49268537/58541235-9ff0ac00-822d-11e9-81e8-70c83dde49d0.png)

**Comment by kingofhawks** [comment]
INSERT INTO uportal.t_center_package (Id, customerId, shipping, transport1, address, receiver, mobile, description, expressPay, amount, total, status, stafferName, industryName, departName, logTime, pickupId, index_pos, transport2, transportPay, productCount, locationId, shipTime, cityId, emergency, sendMailFlag, billsTime, insFollowOut, sfReceiveDate, transportNo, sendMailFlagNbyh, sendMailFlagSails, zsFollowOut, pickupTime, printTime, telephone, direct, createTime) VALUES ('CK201905291564992243', '262882812', 2, 1, '河南省信阳市浉河区中山北路鑫鑫广场门面房中原银行', '蔡军琳', '13700761681', null, 2, 3, 0, 2, '专员-柴福振-三部', '04-13银行事业部', '04-13-05-03华中大区', '2019-05-29 15:04:58', 'PC201905291564993439', 20, 0, -1, 1, '99', '', '411500', 0, 0, '', 1, '2019-05-29 16:13:48', '232122953036', 0, 0, 1, '2019-05-29 15:07:06', '2019-05-29 16:10:27', '', 0, '2019-05-29 15:04:58');
INSERT INTO uportal.t_center_package_item (Id, packageId, outId, baseId, productId, productName, amount, price, value, description, outTime, customerId, printText, emergency, productImportId) VALUES (2707465, 'CK201905291564992243', 'ZS1905291103664975287', '664992233', '659644979', 'YZ0501600 第五轮5元纪念钞含红包（普2）', 3, 0, 0, '数据接口批量导入，银行单号20190529.（根据《世园会产品配置伍元生日钞活动方案》）19630711、20030412、20090602', '2019-05-29', '262882812', '', 0, '');
INSERT INTO uportal.t_center_out (id, fullId, flowId, outTime, managerTime, outType, channel, locationID, location, industryId, industryId2, department, customerId, description, total, hadPay, badDebts, status, type, hasInvoice, invoiceStatus, invoiceId, dutyId, mark, pay, inway, tempType, customerName, phone, stafferName, connector, checks, reday, arriveDate, redate, depotpartId, destinationId, tranNo, refOutFullId, stafferId, managerId, reserve1, reserve2, reserve3, reserve4, reserve5, reserve6, reserve7, reserve8, reserve9, invoiceMoney, curcredit, staffcredit, managercredit, checkStatus, badDebtsCheckStatus, changeTime, mtype, sailType, productType, ratio, vtype, vtypeFullId, pmtype, industryId3, payTime, forceBuyType, eventId, refBindOutId, promValue, promStatus, lastModified, operator, operatorName, logTime, guarantor, feedBackVisit, feedBackCheck, taxTotal, hasRebate, piDutyId, piMtype, piType, piStatus, hasConfirm, hasConfirmInsMoney, emergency, presentFlag, podate, ibFlag, motivationFlag, remoteAllocate, reason, transportNo, swbz, outbackStatus, customerCreated, flowTime, ibApplyId, motivationApplyId, refGiftId, profigflag, cashflag, ibFlag2, ibApplyId2, motivationFlag2, motivationApplyId2, customerDescription, delivery, posPayer, recommendation, platformFlag, platformApplyId, virtualstatus) VALUES (664975287, 'ZS1905291103664975287', 'CITIC', '2019-05-29', '2019-05-29 15:04:46', 4, '', 999, '99000000000000000002', '180301076', '180301047', '', '262882812', '数据接口批量导入，银行单号20190529.（根据《世园会产品配置伍元生日钞活动方案》）19630711、20030412、20090602', 0, 0, 0, 4, 0, 0, 0, '90000000000000000007', '90201008080000000001', 0, 1, 0, 0, '中原银行信阳中山路支行-银行', '', '专员-柴福振-三部', '', '', '30', '29/05/2019', '2019-05-29', '', '0', '', '', '618166304', '', 0, 0, 2, '', '', '', '', '', '', 0, 0, 0, 0, 0, 0, '2019-05-29 15:04:56', 1, '', '', '', 0, '', 0, '644989058', '2019-05-29 15:04:56', -1, '', '', 0, -1, '2019-05-29', '576437478', '黄友丽', '', '', 0, 0, 0, 0, '', -1, -1, -1, 0, 0, 0, 1, '2019-05-29', 0, 0, 0, '', '', '特殊需求：生日号码：19630711/20030412/20090602', '', 0, '2019-05-29 15:04:56', '', '', '', 0, 0, 0, '', 0, '', '', '', '', '', 0, '', 0);
INSERT INTO uportal.t_center_base (id, inway, productId, unit, amount, price, costPrice, costPriceKey, value, owner, ownerName, locationId, description, productName, showName, showId, outId, storageId, depotpartName, depotpartId, inputPrice, mtype, invoiceMoney, pprice, iprice, deliverType, expressPay, transportPay, profit, profitRatio, oldGoods, taxrate, tax, inputRate, refId, ibMoney, motivationMoney, profitmoney, grossProfit, checkgrossProfit, cash, ibMoney2, motivationMoney2, platformFee, productImportId, ykibMoney, cash2, virtualPrice, virtualPriceKey) VALUES (664992233, 0, '659644979', '套', 3, 0, 24.8, '2480', 0, '0', '公共', '99000000000000000002', '', 'YZ0501600 第五轮5元纪念钞含红包（普2）', '', '', 'ZS1905291103664975287', '', '可发成品仓', '1', 35.55, 0, 0, 35.55, 35.55, 0, -1, -1, 0, 0, -1, 0.02, 0, 0, '', 0, 0, null, 0, null, 0, 0, 0, 0, '', 0, 0, 0, '0');

**Comment by kingofhawks** [comment]
INSERT INTO uportal.t_center_vs_packcust (Id, packageId, customerId, customerName, indexPos) VALUES (23420833, 'CK201905291564992243', '262882812', '中原银行信阳中山路支行-银行', 1);

**Comment by kingofhawks** [comment]
INSERT INTO uportal.t_center_out_import (id, fullId, batchId, type, customerId, branchName, secondBranch, comunicationBranch, comunicatonBranchName, productId, productCode, productName, amount, price, style, value, midValue, arriveDate, storageType, citicNo, invoiceNature, invoiceHead, invoiceCondition, bindNo, invoiceType, invoiceName, invoiceMoney, provinceId, cityId, address, receiver, handPhone, status, OANo, reason, logTime, firstName, citicOrderDate, transport1, itype, outType, depotId, depotpartId, stafferId, description, shipping, transport2, expressPay, transportPay, preUse, reday, presentFlag, ibMoney, motivationMoney, customerName, nbyhNo, result, importFromMail, lhwd, telephone, direct, channel, cash, grossProfit, ibMoney2, motivationMoney2, delivery, posPayer, recommendation, platformFee, productImportId, ykIbMoney, cash2, virtualstatus) VALUES (2, 1057014, 'A1201905291164975282', 0, '262882812', '中原银行', '', '可发成品仓', '中原银行信阳中山路支行-银行', '659644979', '', 'YZ0501600 第五轮5元纪念钞含红包（普2）', 3, 0, '', 0, 0, '29/05/2019', 0, '20190529', 0, '', '', '', 0, '', 0, '410000', '411500', '河南省信阳市浉河区中山北路鑫鑫广场门面房中原银行', '蔡军琳', '13700761681', 2, 'ZS1905291103664975287', '576437478', '2019-05-29 11:03:06', 'N/A', '2019-05-29', 1, 1, 4, '99000000000000000002', '1', '', '（根据《世园会产品配置伍元生日钞活动方案》）19630711、20030412、20090602', 2, 0, 2, -1, 0, 30, 1, 0, 0, '', '', '成功', 0, '', '', 0, '', 0, 0, 0, 0, '', '', '', 0, '', 0, 0, 0);
