### ISSUE TITLE
东莞农商发货单异常

### ISSUE THREAD

**Issue by yanglu-china** [qianlimu/yycoin#660]
东莞农商的存货需求表中商品名称从主数据中取得商品名称与实际正常的主数据名称不同，麻烦看一下
![05407e23-948d-4096-8341-aaa9e13e7a9b(1)](https://user-images.githubusercontent.com/49268537/58618172-81a1b380-82f4-11e9-9746-aa71e2c0d5ed.jpg)
![企业微信截图_15592033747651](https://user-images.githubusercontent.com/49268537/58618173-836b7700-82f4-11e9-9127-aebd47262063.png)

**Comment by kingofhawks** [comment]
CK201905291665006078
