### ISSUE TITLE
体外OA其他费用申请处理异常

### ISSUE THREAD

**Issue by yanglu-china** [qianlimu/yycoin#661]
体外OA其他费用申请处理，财务支付完成后，审批单据报错，路径：李敏的账户，体外OA-报销管理-待我处理  单号：UT201904191658767252 麻烦看一下，谢谢 ![企业微信截图_15592077004845](https://user-images.githubusercontent.com/49268537/58624007-c97b0780-8301-11e9-85a7-6f03a97ef61b.png)
![企业微信截图_15592076723598](https://user-images.githubusercontent.com/49268537/58624011-caac3480-8301-11e9-9e64-75aafbcde34f.png)
![企业微信截图_15592076131458](https://user-images.githubusercontent.com/49268537/58624013-cc75f800-8301-11e9-85c5-c39c7946dc6d.png)

**Comment by 39189058** [comment]
![image](https://user-images.githubusercontent.com/28384119/58635775-4c5f8a80-8321-11e9-8b6f-b8edb7ef5fe7.png)
ratio 值异常，一般最大为100，这条记录8400。怀疑是数据录入错误。
已修正为100。

**Comment by 39189058** [comment]
select * from uportal.t_center_travelapply a where a.id like 'UT201904191658767252%';
select * from uportal.t_center_tcpshare a where a.refid like 'UT201904191658767252%';
update uportal.t_center_tcpshare set ratio=100 where id='A201904191658767252';
