### ISSUE TITLE
OA产品合成控制

### ISSUE THREAD

**Issue by yanglu-china** [qianlimu/yycoin#662]
在产品合成时，控制对比金额尾数在两位小数内

**Comment by kingofhawks** [comment]
生产部门天天会遇到合成时提示成本总金额或虚料总金额不平，要试到小数点后4到6位才能碰齐

**Comment by kingofhawks** [comment]
alter table T_CENTER_STORAGELOG add column virtualPrice double default 0,add column virtualPriceKey varchar(32) default '0';

**Comment by kingofhawks** [comment]
产品拆分页面，“自动调整..."按钮没有自动调整虚料金额
