### ISSUE TITLE
体内OA订单导出品名异常

### ISSUE THREAD

**Issue by yanglu-china** [qianlimu/yycoin#667]
品壮丽山河9X-4T纪念册系统内订单导出的品名显示有问号，提报激励申请的时候显示该品名不对
![企业微信截图_15597005151896](https://user-images.githubusercontent.com/49268537/58925503-53035d00-877a-11e9-8384-164efb138462.png)
[品名异常.xlsx](https://github.com/qianlimu/yycoin/files/3255220/default.xlsx)

**Comment by kingofhawks** [comment]
SO1903261249654815915
--
SO1903121435652624299
SO1901311259646672998
SO1901311259646672986
SO1901311259646672942
SO1901311259646672911
SO1901311259646672865
SO1901250934645560626
SO1901250934645560579

**Comment by kingofhawks** [comment]
集邮江苏省泰州市集邮公司
--
集邮江苏省泰州市靖江市集邮公司
集邮江苏省泰州市集邮公司
集邮江苏省泰州市集邮公司
集邮江苏省泰州市集邮公司
集邮江苏省连云港市集邮公司
集邮江苏省淮安市淮阴区集邮公司
集邮江苏省连云港市集邮公司
集邮江苏省南通市海安县集邮公司

**Comment by kingofhawks** [comment]
YZ0451400 壮丽山河9X-4T纪念册（FB版）（普16）

**Comment by kingofhawks** [comment]
INSERT INTO uportal.t_center_out (id, fullId, flowId, outTime, managerTime, outType, channel, locationID, location, industryId, industryId2, department, customerId, description, total, hadPay, badDebts, status, type, hasInvoice, invoiceStatus, invoiceId, dutyId, mark, pay, inway, tempType, customerName, phone, stafferName, connector, checks, reday, arriveDate, redate, depotpartId, destinationId, tranNo, refOutFullId, stafferId, managerId, reserve1, reserve2, reserve3, reserve4, reserve5, reserve6, reserve7, reserve8, reserve9, invoiceMoney, curcredit, staffcredit, managercredit, checkStatus, badDebtsCheckStatus, changeTime, mtype, sailType, productType, ratio, vtype, vtypeFullId, pmtype, industryId3, payTime, forceBuyType, eventId, refBindOutId, promValue, promStatus, lastModified, operator, operatorName, logTime, guarantor, feedBackVisit, feedBackCheck, taxTotal, hasRebate, piDutyId, piMtype, piType, piStatus, hasConfirm, hasConfirmInsMoney, emergency, presentFlag, podate, ibFlag, motivationFlag, remoteAllocate, reason, transportNo, swbz, outbackStatus, customerCreated, flowTime, ibApplyId, motivationApplyId, refGiftId, profigflag, cashflag, ibFlag2, ibApplyId2, motivationFlag2, motivationApplyId2, customerDescription, delivery, posPayer, recommendation, platformFlag, platformApplyId, virtualstatus) VALUES (654815915, 'SO1903261249654815915', 'CITIC', '2019-03-26', '2019-03-29 16:46:49', 0, '', 999, 'A1201310151011526376', '180301084', '180301051', '', '577245517', '数据接口批量导入，银行单号20190326501.', 1200, 1200, 0, 4, 0, 0, 1, '90000000000000000001', '90201008080000000001', 0, 1, 0, 0, '集邮江苏省泰州市集邮公司', '', '步伟', '', '', '30', '2019-03-26', '2019-04-25', '', '0', '', '', '575752935', '', 0, 0, 2, '', '', '', '', '', '', 1200, 0, 0, 0, 0, 0, '2019-03-29 16:47:28', 1, '', '', '', 0, '', 0, '180301015', '2019-04-25 18:00:56', -1, '', '', 0, -1, '2019-04-25', '17683237', '尹璐洁', '', '', 0, 0, 0, 0, '90201008080000000001', 1, 1, 1, 0, 0, 0, 0, '2019-03-26', 0, 1, 0, '', '', '', '', 0, '', '', 'UT201906051066324739', '', 0, 0, 0, '', 0, '', '', '', '', '', 0, '', 0);
INSERT INTO uportal.t_center_base (id, inway, productId, unit, amount, price, costPrice, costPriceKey, value, owner, ownerName, locationId, description, productName, showName, showId, outId, storageId, depotpartName, depotpartId, inputPrice, mtype, invoiceMoney, pprice, iprice, deliverType, expressPay, transportPay, profit, profitRatio, oldGoods, taxrate, tax, inputRate, refId, ibMoney, motivationMoney, profitmoney, grossProfit, checkgrossProfit, cash, ibMoney2, motivationMoney2, platformFee, productImportId, ykibMoney, cash2, virtualPrice, virtualPriceKey) VALUES (655362441, 0, '642234289', '套', 1, 1200, 442.01, '44201', 1200, '0', '公共', 'A1201310151011526376', '', 'YZ0451400 壮丽山河9X-4T纪念册（FB版）（普16）', '', '', 'SO1903261249654815915', '', '空退空开库（仅限商务部操作）_默认仓区', 'A1201310151011526377', 603.395, 0, 1200, 603.395, 603.395, 0, -1, -1, 596.605, 0.49717083333333334, -1, 0.17, 0, 0, '', 0, 40, null, 0, null, 0, 0, 0, 0, '2019022214450228', 0, 0, 0, '0');
