### ISSUE TITLE
体外OA采购付款—申请异常

### ISSUE THREAD

**Issue by yanglu-china** [qianlimu/yycoin#673]
体外OA采购付款—申请，财务再审批通过的时候报错，审批单据报错总借和总贷不等，路径：李敏的账户，体外OA采购管理—采购付款-申请 
![企业微信截图_15601446606209](https://user-images.githubusercontent.com/49268537/59177068-7ae52d00-8b8d-11e9-94eb-8e2c1e2f50bd.png)
![企业微信截图_15601447073181](https://user-images.githubusercontent.com/49268537/59177070-7d478700-8b8d-11e9-8c8e-bcfb27553cc9.png)

**Comment by 39189058** [comment]
因为用两个账户支付，现在2个账号支付的时候，校验“总借”和“总贷”的时候没有把两个账户支付金额合并后校验，而是分开校验，导致“总借”和“总贷”不相等。有没有可能用一个账户支付？

**Comment by 39189058** [comment]
![image](https://user-images.githubusercontent.com/28384119/59366724-53e55180-8d6d-11e9-88d1-79256b5fa215.png)
SO_CG201808141758626693499/143519 测试站点这个单子，两个数值存在精度差异，在值不等的时候，后台算法会，会修改InMoney值，造成总借、总贷不匹配。

**Comment by 39189058** [comment]
数值修改为278.86后，处理成功
