### ISSUE TITLE
钱币发货邮件推送异常

### ISSUE THREAD

**Issue by yanglu-china** [qianlimu/yycoin#674]
肖总反馈，今天凌晨永银邮箱推送给她的6月10日的发货信息邮件内容异常，明细里包含了2017年的发货单，快递单号：616090988441，是一笔领样订单，订单号：LY1708181428580244872
![企业微信截图_156021506722](https://user-images.githubusercontent.com/49268537/59236590-88e88b80-8c29-11e9-9a4f-d44ca2ab18f2.png)
![企业微信截图_15602146699715](https://user-images.githubusercontent.com/49268537/59236592-8ab24f00-8c29-11e9-99ca-ecefd4e9bcf5.png)

**Comment by kingofhawks** [comment]
CK201708181480245447
