### ISSUE TITLE
激励取值异常

### ISSUE THREAD

**Issue by yanglu-china** [qianlimu/yycoin#676]
[激励50元，调整70元浦发南京分行电子订单.xlsx](https://github.com/qianlimu/yycoin/files/3279124/50.70.xlsx)
此批订单在售读取的激励南京分行 5.20开始的数据照在售应该是70 ，系统生成的是50

**Comment by kingofhawks** [comment]
SO1905221022663807244
--
SO1906051031666325371
SO1906051031666325374
SO1906051031666325377
SO1906051031666325380
SO1906051031666325422
SO1906051031666325425
SO1906061005666615185
SO1906061005666615191
SO1906061005666615194
SO1906061005666615212
SO1906061005666615215
SO1906061005666615227
SO1906101024667419881
SO1906101025667420026
SO1906111049667667335
SO1906111049667667338
SO1906111049667667341
SO1906111049667667524
SO1906111049667667527

**Comment by kingofhawks** [comment]
201905201133121这个渠道是小浦金店

**Comment by kingofhawks** [comment]
INSERT INTO uportal.t_center_product_import (id, bank, branchname, customername, channel, bankProductCode, name, code, bankProductBarcode, bankProductName, properties, weight, material, retailPrice, costPrice, ibMoney, motivationMoney, grossProfit, cash, buyBack, onMarketDate, offlineDate, branchRange, taxRate, invoiceType, invoiceContent, discription, updateTime, operator, ibMoney2, motivationMoney2, isSell, item, platformFee, ykibMoney, cash2, syb, rated, invoicename) VALUES ('201904181655532', '浦发银行', ' ', ' ', ' ', '35S0138', 'YZ0480200 世界园艺博览会钱币册含5克银章（普13）', '650533427', '1', '世园会五十国钱币册', ' ', '5', 'Ag999', 998, 848.3, 149.7, 50, 70.3, 9, '0', '2019-04-22', '2028-01-01', '全行预售，广州分行除外。', '13', '增值税专用发票13%', '工艺品*产品名称、纪念品、宣传纪念品、工艺品、银制品（仅限含银产品）、礼品', null, '2019-04-18 16:55:53', '蒋逸敏', 0, 0, '在售', '体内', 0, 0, 4, '银行事业部', 1, null);
INSERT INTO uportal.t_center_product_import (id, bank, branchname, customername, channel, bankProductCode, name, code, bankProductBarcode, bankProductName, properties, weight, material, retailPrice, costPrice, ibMoney, motivationMoney, grossProfit, cash, buyBack, onMarketDate, offlineDate, branchRange, taxRate, invoiceType, invoiceContent, discription, updateTime, operator, ibMoney2, motivationMoney2, isSell, item, platformFee, ykibMoney, cash2, syb, rated, invoicename) VALUES ('201905201133122', '浦发银行', '南京分行', ' ', ' ', '35S0138', 'YZ0480200 世界园艺博览会钱币册含5克银章（普13）', '650533427', '1', '世园会五十国钱币册', ' ', '5', 'Ag999', 998, 848.3, 149.7, 70, 56.1, 8, '0', '2019-05-20', '2019-06-30', '全行预售，广州分行除外。', '13', '增值税专用发票13%', '工艺品*产品名称、纪念品、宣传纪念品、工艺品、银制品（仅限含银产品）、礼品', null, '2019-05-20 11:33:12', '蒋逸敏', 99.8, 0, '在售', '体内', 0, 0, 3.6, '银行事业部', 1, null);
