### ISSUE TITLE
激励申请异常

### ISSUE THREAD

**Issue by yanglu-china** [qianlimu/yycoin#679]
此批订单在申请激励的时候显示不在中收激励统计表中，此批订单未申请过中收激励，且订单是有激励的，麻烦看一下；单号：
SO1905081130661655930
SO1905101038662017198
SO1905140833662680638
SO1905151448662893460
![企业微信截图_1560407384892](https://user-images.githubusercontent.com/49268537/59411871-d4986200-8dee-11e9-8bd4-ad871a9d7b05.png)
![企业微信截图_15604085652019](https://user-images.githubusercontent.com/49268537/59411878-d6fabc00-8dee-11e9-86d1-8f3bf0cc12b2.png)

**Comment by kingofhawks** [comment]
INSERT INTO uportal.t_center_out (id, fullId, flowId, outTime, managerTime, outType, channel, locationID, location, industryId, industryId2, department, customerId, description, total, hadPay, badDebts, status, type, hasInvoice, invoiceStatus, invoiceId, dutyId, mark, pay, inway, tempType, customerName, phone, stafferName, connector, checks, reday, arriveDate, redate, depotpartId, destinationId, tranNo, refOutFullId, stafferId, managerId, reserve1, reserve2, reserve3, reserve4, reserve5, reserve6, reserve7, reserve8, reserve9, invoiceMoney, curcredit, staffcredit, managercredit, checkStatus, badDebtsCheckStatus, changeTime, mtype, sailType, productType, ratio, vtype, vtypeFullId, pmtype, industryId3, payTime, forceBuyType, eventId, refBindOutId, promValue, promStatus, lastModified, operator, operatorName, logTime, guarantor, feedBackVisit, feedBackCheck, taxTotal, hasRebate, piDutyId, piMtype, piType, piStatus, hasConfirm, hasConfirmInsMoney, emergency, presentFlag, podate, ibFlag, motivationFlag, remoteAllocate, reason, transportNo, swbz, outbackStatus, customerCreated, flowTime, ibApplyId, motivationApplyId, refGiftId, profigflag, cashflag, ibFlag2, ibApplyId2, motivationFlag2, motivationApplyId2, customerDescription, delivery, posPayer, recommendation, platformFlag, platformApplyId, virtualstatus) VALUES (661655930, 'SO1905081130661655930', 'CITIC', '2019-05-08', '2019-05-09 10:52:19', 0, '', 999, 'A1201205251506100751', '180301084', '180301050', '', '658421529', '陆运___线下单号___D536596201905081118.', 130200, 130200, 0, 4, 0, 0, 1, '90000000000000000046', '90201008080000000001', 0, 1, 0, 34, '南京千派文化发展有限公司', '', '张皓', '', '', '0', '2019-05-08', '2019-06-12', '1', '0', '', '', '536596', '', 0, 0, 2, '', '', '', '', '', '', 130200, 0, 0, 0, 0, 0, '2019-05-09 10:52:28', 0, '', '', '', 0, '', 0, '180301014', '2019-06-12 10:45:01', -1, '', '', 0, -1, '2019-06-12', '', '系统', '2019-05-08 11:30:29', '', 0, 0, 0, 0, '90201008080000000001', 1, 1, 1, 0, 0, 0, 9, '2019-05-08', 0, 0, 0, '', '', '', '', 0, '', '', '', '', 0, 0, 0, '', 0, '', '', '', '', '', 0, '', 0);
INSERT INTO uportal.t_center_base (id, inway, productId, unit, amount, price, costPrice, costPriceKey, value, owner, ownerName, locationId, description, productName, showName, showId, outId, storageId, depotpartName, depotpartId, inputPrice, mtype, invoiceMoney, pprice, iprice, deliverType, expressPay, transportPay, profit, profitRatio, oldGoods, taxrate, tax, inputRate, refId, ibMoney, motivationMoney, profitmoney, grossProfit, checkgrossProfit, cash, ibMoney2, motivationMoney2, platformFee, productImportId, ykibMoney, cash2, virtualPrice, virtualPriceKey) VALUES (661834805, 0, '652623508', '套', 200, 651, 407.93, '40793', 130200, '0', '公共', 'A1201205251506100751', '', 'YZ0484500 中国梦一带一路含4*10克银券套装（流通纪念币版）（普13）', '', '', 'SO1905081130661655930', '', '代发库--南京物流中心_默认仓区', 'A1201205251506100752', 407.9252, 0, 130200, 407.9252, 407.9252, 0, -1, -1, 50400, 0.3870967741935484, -1, 0.17, 0, 0, '', 0, 110, null, 0, null, 0, 0, 0, 0, '201904171003393', 0, 0, 0, '0');

**Comment by kingofhawks** [comment]
重启JOB后解决
