### ISSUE TITLE
体内OA调拨异常

### ISSUE THREAD

**Issue by yanglu-china** [qianlimu/yycoin#680]
![企业微信截图_15604826652245](https://user-images.githubusercontent.com/49268537/59481585-66f44080-8e97-11e9-9231-e3f1adfd77a0.png)

![企业微信截图_1560482671653](https://user-images.githubusercontent.com/49268537/59481525-285e8600-8e97-11e9-8823-42472bc1ba2e.png)

**Comment by kingofhawks** [comment]
select * from t_center_storageralation where priceKey='154991' and productId='624811466' and depotpartId='A1201808131402130407';
对应库存的virtualPriceKey是1038.22，与当前DB不一致。

**Comment by kingofhawks** [comment]
DB1906140945668369810

**Comment by kingofhawks** [comment]
“调拨申请”页面有问题，改用"新增入库单“页面解决
