### ISSUE TITLE
产品合成库存控制

### ISSUE THREAD

**Issue by yanglu-china** [qianlimu/yycoin#681]
![image](https://user-images.githubusercontent.com/49268537/59488073-1984cd00-8eb1-11e9-9519-7066444eb74d.png)

产品合成时加上数量控制，把已占库存从可用库存里去掉

**Comment by kingofhawks** [comment]
681的场景是：生产申请合成产品，将使用了产品库存，但是系统没有预占，商务还能看到产品库存，商务过完待商务之后生产合成审批通过了，再过待库管就会出现报错库存不足[图片][图片]
smartman 2019/07/01 13:36:46
嗯
我是全幼儿园脸皮最厚的 2019/07/01 13:37:08
所以希望是在生产申请的时候就预占掉
[图片]
smartman 2019/07/01 13:38:08
我以为是预占掉的库存，在选择合成产品时还没有去掉。你的问题是申请合成后，使用的产品库存未被预占是吧？
我是全幼儿园脸皮最厚的 2019/07/01 13:40:02
是的
