### ISSUE TITLE
开票异常

### ISSUE THREAD

**Issue by yanglu-china** [qianlimu/yycoin#682]
A1201906121067888560，SO1906121014667886720，发票号：10666152，财务无法查询到退票，麻烦看一下
![企业微信截图_15605059614568](https://user-images.githubusercontent.com/49268537/59501538-53b09780-8ece-11e9-8d10-5df0a6e76f18.png)

**Comment by kingofhawks** [comment]
t_center_invoiceins_item表中baseId为667886721，但是base表中ID为667888621
