### ISSUE TITLE
定单勾稽的收款单金额大于订单金额

### ISSUE THREAD

**Issue by yanglu-china** [qianlimu/yycoin#685]
定单勾稽的收款单金额大于订单金额，导致预收金额少了，麻烦看一下。HK201906171668676917——SO1906150849668477156，HK201906171068628494——SO1906150849668477159、SO1906150849668477162、SO1906150849668477165
![企业微信截图_15608296599421](https://user-images.githubusercontent.com/49268537/59657385-2700c680-91d3-11e9-910c-cb9c08ae6bc2.png)
![企业微信截图_15608295505652](https://user-images.githubusercontent.com/49268537/59657390-2b2ce400-91d3-11e9-97f5-cdfec5567e65.png)
![企业微信截图_15608295809179](https://user-images.githubusercontent.com/49268537/59657398-2ff19800-91d3-11e9-9b18-97d2e7b3326e.png)
![企业微信截图_15608295962180](https://user-images.githubusercontent.com/49268537/59657419-3849d300-91d3-11e9-9503-05a54f354e1d.png)

**Comment by kingofhawks** [comment]
SF201906171768681470
--

**Comment by kingofhawks** [comment]
INSERT INTO uportal.t_center_inbill (id, type, ulock, bankId, outId, outBalanceId, status, moneys, customerId, stafferId, ownerId, locationId, destBankId, refBillId, paymentId, logTime, description, checks, checkStatus, srcMoneys, updateId, createType, mtype, freeze, dutyId) VALUES ('SF201906171768681470', 0, 0, 'A1201408121516396612', 'SO1906150849668477156', '', 0, 267325, '10009033', '99999999', '579050696', '', '', '', 'HK201906171668676917', '2019-06-17 17:15:01', '从收款单:SF201906171768679937 收到预收(金额):351103.9 1<br>销售关联分拆了:83778.90出去,新单:SF201906171768682200<br>审批意见(SO1906150849668477156): ', '', 0, 351103.9, 0, 0, 1, 0, '90201008080000000001');

**Comment by kingofhawks** [comment]
销售单总金额与对应商品的金额不一致，周总手工改了数据。
