### ISSUE TITLE
产品合成异常

### ISSUE THREAD

**Issue by yanglu-china** [qianlimu/yycoin#686]
产品合成报错，提示系统内部错误  路径：体内OA-产品管理-合成申请/查询A1201906191569032077 
![企业微信截图_15609292966841](https://user-images.githubusercontent.com/49268537/59746416-79141b80-92a9-11e9-9dac-9c044b632da6.png)

**Comment by kingofhawks** [comment]
productId=647022042，两个商品行在库存表中的price字段一个是0.1312,一个是0.13，但是如compose_item表之后，价格都变成了0.13，导致t_center_storagelog表触发唯一性约束。
要看下compose_item表入库的逻辑。

**Comment by kingofhawks** [comment]
根据BOM选择产品之后，页面上只保留了2位小数。
