### ISSUE TITLE
过单异常

### ISSUE THREAD

**Issue by yanglu-china** [qianlimu/yycoin#687]
单号：SO1906200851669105389，商务审批过单报错
![企业微信截图_15610094588865](https://user-images.githubusercontent.com/49268537/59824573-1d5a9880-9364-11e9-9aa9-95fe9cf2af4a.png)
![企业微信截图_15610093732719](https://user-images.githubusercontent.com/49268537/59824579-221f4c80-9364-11e9-8219-f408cea8c3f1.png)

**Comment by kingofhawks** [comment]
select * from t_center_storageralation where productId='613024941' and priceKey='464902' and depotpartId='1';

**Comment by kingofhawks** [comment]
SO1906200851669105389商务过单时报错，因为对应库存里边有2条，一个是2，一个是10，两个库存的虚料金额不一致。单据商品为5，然后拆成多个商品行，进入base表就唯一性约束报错。
周总手工把两个库存合并起来过单了。
