### ISSUE TITLE
预算重复报错控制

### ISSUE THREAD

**Issue by yanglu-china** [qianlimu/yycoin#690]
![@L{W`A4(`~8SP%2F181%%NV](https://user-images.githubusercontent.com/49268537/59837077-36bd0e00-937f-11e9-9c64-1e37e43a684f.png)
中收激励导入可以重复预算，但驳回重新修改提交后显示上图报错，需要修改可以重复预算

**Comment by 39189058** [comment]
修改提交时，附件需要再次上传，已经有的附件系统不识别
