### ISSUE TITLE
中收激励统计表显示异常

### ISSUE THREAD

**Issue by yanglu-china** [qianlimu/yycoin#692]
单号：SO1906191552669034501，SO1906191552669034504，SO1906191552669034507，这三笔订单已勾款，系统有中收，但http://loc.dingtalk.com/QzpcVXNlcnNcQWRtaW5pc3RyYXRvclxBcHBEYXRhXFJvYW1pbmdcRGluZ1RhbGtcNTU5NjQ2MjY4X3YyXEltYWdlRmlsZXNcMTU2MTA4ODMzNDYzM19DMzA1NTdGMS0xQ0QzLTRjYzktODlCNC02ODM1NkE4RkZBMTQucG5n是在中收激励统计表中没有

**Comment by kingofhawks** [comment]
JOB占用资源比较多，没有运行结束。

**Comment by kingofhawks** [comment]
需要优化JOB，现在查询太耗内存了。

**Comment by kingofhawks** [comment]
select count(OutBean.id) from t_center_out OutBean left outer join t_center_base BaseBean on BaseBean.outId=OutBean.fullId where OutBean.type=0 and OutBean.outType=0  and OutBean.status!=2 and ((OutBean.ibFlag=0 and BaseBean.ibMoney>0) or (OutBean.ibFlag2=0 and BaseBean.ibMoney2>0) or (OutBean.motivationFlag=0 and BaseBean.motivationMoney>0) or (OutBean.motivationFlag2=0 and BaseBean.motivationMoney2>0) or (OutBean.platformFlag=0 and BaseBean.platformFee>0));

**Comment by kingofhawks** [comment]
select OutBean.fullId,BaseBean.ibMoney,BaseBean.ibMoney2,BaseBean.motivationMoney, BaseBean.motivationMoney2,BaseBean.platformFee from t_center_out OutBean left outer join t_center_base BaseBean on BaseBean.outId=OutBean.fullId where OutBean.outTime>'2015-04-01' and OutBean.type=0 and OutBean.outType=0 and OutBean.status!=2 and ((OutBean.ibFlag=0 and BaseBean.ibMoney>0) or (OutBean.ibFlag2=0 and BaseBean.ibMoney2>0) or (OutBean.motivationFlag=0 and BaseBean.motivationMoney>0) or (OutBean.motivationFlag2=0 and BaseBean.motivationMoney2>0) or (OutBean.platformFlag=0 and BaseBean.platformFee>0));

**Comment by 39189058** [comment]
TravelApplyManagerImpl.ibReportJob()
