### ISSUE TITLE
订单相关异常

### ISSUE THREAD

**Issue by yanglu-china** [qianlimu/yycoin#693]
中信端口导入的数据订单号：SO1906182134668943830，SO1906182129668943603，订单信息内容为空
![image](https://user-images.githubusercontent.com/49268537/59995126-e3053a00-9688-11e9-9fbc-e0206305d704.png)
![image](https://user-images.githubusercontent.com/49268537/59995132-e6002a80-9688-11e9-9569-fe3c2aa423e8.png)

**Comment by kingofhawks** [comment]
t_center_out_import 表没有相关导入记录。
