### ISSUE TITLE
开票优化需求

### ISSUE THREAD

**Issue by yanglu-china** [qianlimu/yycoin#695]
[6439890891OA开票优化需求20190620.xlsx](https://github.com/qianlimu/yycoin/files/3337367/6439890891OA.20190620.xlsx)

**Comment by kingofhawks** [comment]
1、商务推单，一个订单里开了一个产品，数量是2件，系统根据物流可发库成品仓的情况匹配了两个成本不一样的库存满足这个订单，生成了如上图所示的订单；
2、2件产品业务要求开一张发票，商务在帆软（帆软-运营-商务-操作端口-发票操作相关-开票信息校验导入）提交的是一条开票申请；
3、正常流程是这样的：财务在帆软（帆软-财务-开票信息校验审核）审批后导入OA系统（OA系统-中信销售-批量导入开票申请），导入OA的单据再OA审核一遍之后导出A标识（OA系统-资金管理-开票管理-待财务开票），然后将A标识导入（OA系统-资金管理-财务开票批量审批），根据物流给的pc单，在帆软（帆软-财务-批次打印开票明细）导出审核数据 ，打印发票然后进入OA系统（OA系统-资金管理-批量修改发票号码）导入发票号；
4、但是由于OA匹配的同一产品2件的成本不一样，导致由导入OA审核后，在导出的时候一个A标识导出了两条信息，如果不注意，财务没有手工合并开票，到帆软打印的时候就会重复开票；
财务提出要优化这块。因为财务开票不关注产品的成本，所以导入OA的时候希望可以根据销售金额匹配订单号直接合并生成一条信息。

**Comment by kingofhawks** [comment]
开票明细invoiceins_item表，针对同一商品不同成本合并为一行。
