### ISSUE TITLE
公共资源 - 人员管理 优化

### ISSUE THREAD

**Issue by yanglu-china** [qianlimu/yycoin#698]
路径公共资源 - 人员管理 - 增加人员，页面需要新增  
zw （职务）：文本框  （非必填）
status （oa状态：0-正常；99-废弃）：  如果oa新增用户的时候自动赋值0，则新增页面不需要加  （必填）
zzzt （帆软状态 ：在职，离职，停用） ：   下拉框  （必填）
lzsj （入职时间） ： 日期控件（年月日）     （必填）
wxname （微信名称） ： 文本控件 （好像没用到）（非必填）
superLeader ：直属领导  （现在帆软有个表在跑，页面是否需要加端口）？（非必填）

路径公共资源 - 人员管理 - 修改人员，页面需要新增
zw （职务）：文本框  （非必填）
status （oa状态：0-正常；99-废弃）： 下拉框  （必填）
zzzt （帆软状态 ：在职，离职，停用） ：   下拉框  （必填）
lzsj （入职时间） ： 日期控件（年月日）   （必填）
outsj（离职时间）： 日期控件（年月日）    （必填）
wxname （微信名称） ： 文本控件 （好像没用到）（非必填）
superLeader ：直属领导  （现在帆软有个表在跑，页面是否需要加端口）？（非必填）

oa这两个端口都有离职日期，这个看看是否是上述的lzsj（新增页面不需要离职时间）

**Comment by 39189058** [comment]
离职时间：（必填）？感觉不对

**Comment by 39189058** [comment]
手动修改t_center_oastaffer lzsj, outsj 类型为 varchar 40

**Comment by 39189058** [comment]
outsj（离职时间）： 日期控件（年月日） （不必填）
