### ISSUE TITLE
采购单信息异常

### ISSUE THREAD

**Issue by zhangxian** [qianlimu/yycoin#708]
生产采购部陈玲反馈，采购单：SO_CG201907161707673873403，驳回后再次提交合计金额和总金额变为0，路径：体内OA-采购管理-我的采购。查了帆软上的比价单流程都是对的，所以基本判断帆软这边应该没问题（相关比价单号：CQBJ201907161129578125789）
![9CD4E7B0-6426-4662-B741-C0B5F7B3F4F7](https://user-images.githubusercontent.com/6063368/61342174-e6e93e00-a87b-11e9-8fb2-315db0750454.png)
![D495109E-5F2C-4857-855B-C6BADD4D5157](https://user-images.githubusercontent.com/6063368/61342177-e94b9800-a87b-11e9-8683-8a7b58892d12.png)

**Comment by kingofhawks** [comment]
StockManagerImpl.rejectStock()在驳回的时候会把stockItem表中的price字段清零，是为了恢复采购询价的初始状态，和业务部门确认下是否要修改。
