### ISSUE TITLE
中收激励申请出错

### ISSUE THREAD

**Issue by zhangxian** [qianlimu/yycoin#711]
正常的已勾款订单，并未支付中收，只是昨天在申请的对公里面放置了明细，并未通过系统上传，实际订单中收标识未打标，现在正常申请中收系统报错已经申请，导订单号已提交中收激励申请(t_center_vs_tcpout表):UT201907171074045870
![CAA2DE10-521A-454a-9930-D1E09E481D1E](https://user-images.githubusercontent.com/6063368/61421988-30995d80-a93c-11e9-9cdb-a4efa9a11862.png)
![35766DD5-DD1C-4803-AB84-2FC9612DF607](https://user-images.githubusercontent.com/6063368/61421992-31ca8a80-a93c-11e9-9585-6023d234d4a4.png)
导入的文件:[1.xlsx](https://github.com/qianlimu/yycoin/files/3404325/1.xlsx)

**Comment by 39189058** [comment]
t_center_vs_tcpout 中存在相关记录， 移除相关记录

**Comment by 39189058** [comment]
select * from t_center_vs_tcpout a where a.refId like '%74045870'

select * from t_center_vs_tcpout a where a.refId = 'UT201907171074045870'

update t_center_vs_tcpout set fullId=concat(fullId, '_') where refId = 'UT201907171074045870';

delete from t_center_vs_tcpout where refId = 'UT201907171074045870';
