### ISSUE TITLE
中收激励申请导入提示错误

### ISSUE THREAD

**Issue by 39189058** [qianlimu/yycoin#714]
在对公业务申请预算项为银行中收作为附件上传的订单显示已提交中收激励申请(t_center_vs_tcpout表):UT201907221075020904，无法重新从中收激励申请导入端口导入，麻烦看一下，谢谢
![image](https://user-images.githubusercontent.com/28384119/61609221-f99eb100-ac87-11e9-8871-d16a3634d924.png)

**Comment by 39189058** [comment]
清空t_center_vs_tcpout表相关记录

**Comment by kingofhawks** [comment]
只有中收/激励申请，导入时才会写入tcpout表，其他申请类型不应该写入这个表
