### ISSUE TITLE
导入凭证异常

### ISSUE THREAD

**Issue by yanglu-china** [qianlimu/yycoin#719]
路径：体内OA--税务管理--导入凭证，财务反馈导入凭证显示成功，但是凭证明细里金额确全变成0了
![image](https://user-images.githubusercontent.com/49268537/61675828-72574900-ad2c-11e9-9a0a-69a3d1764828.png)
![image](https://user-images.githubusercontent.com/49268537/61675831-74210c80-ad2c-11e9-98ec-5b926cd93516.png)
![image](https://user-images.githubusercontent.com/49268537/61675836-76836680-ad2c-11e9-9360-b063a12d0e0d.png)

**Comment by yanglu-china** [comment]
PZ201907230975234594

**Comment by kingofhawks** [comment]
PZ201907231775286265
