### ISSUE TITLE
退款相关异常

### ISSUE THREAD

**Issue by yanglu-china** [qianlimu/yycoin#720]
商务申请退款报错，路径：体内OA-资金管理-申请预收退款
![image](https://user-images.githubusercontent.com/49268537/61677062-bd735b00-ad30-11e9-81d2-67bb966968f3.png)
![image](https://user-images.githubusercontent.com/49268537/61677064-bfd5b500-ad30-11e9-9c70-9da620a36f21.png)

**Comment by kingofhawks** [comment]
T_CENTER_BACKPREPAY_APPLY表有两个字段新增。
