### ISSUE TITLE
回款相关异常

### ISSUE THREAD

**Issue by yanglu-china** [qianlimu/yycoin#721]
单号：HK201907231075243772中SF201907231275256770、SF201907231275256964显示在业务：专员-丁雅楠-三部名下客户：中原银行郑州金水路支行-银行预收下，但是预收中没有
![image](https://user-images.githubusercontent.com/49268537/61694284-bd408300-ad63-11e9-97ed-4239847b2f71.png)
![image](https://user-images.githubusercontent.com/49268537/61694325-cd586280-ad63-11e9-9979-1cee0218db62.png)

**Comment by kingofhawks** [comment]
SF201907231275256770、SF201907231275256964的status从1(关联申请)改为2(预收)
