### ISSUE TITLE
订单数量异常

### ISSUE THREAD

**Issue by yanglu-china** [qianlimu/yycoin#724]
体内OA订单号：LY1907221525675044686一共9套商品，已有4个LY单共6个退货，应该还有3个商品可退。但页面显示已退货7个，只剩2套可退。
![QzpcVXNlcnNcQWRtaW5pc3RyYXRvclxBcHBEYXRhXFJvYW1pbmdcRGluZ1RhbGtcNTU5NjQ2MjY4X3YyXEltYWdlRmlsZXNcMzg2MTI2MjhcMTU2Mzk2MTYxOTcyMV8xMDk1MjYzNi03ODFELTQxNjEtQkQ2QS0yMDQ2NjRBNjJEMDcucG5n](https://user-images.githubusercontent.com/49268537/61784334-1d0a5d00-ae3c-11e9-8031-e3879e8f1ad5.png)
路径：
体内OA姚燕名下销售管理—领样巡展处理

**Comment by kingofhawks** [comment]
LY单下同一商品有多行，计算退库数量的时候有问题。
临时改代码去掉报错信息才能过单。
