### ISSUE TITLE
发票状态异常

### ISSUE THREAD

**Issue by yanglu-china** [qianlimu/yycoin#732]
1.OA开票申请驳回的发票A1201907261475923232未删除的情况下，新的发票A1201907261475924056重新开出；
2.订单已开票，开票状态还显示可开票；订单号：SO1907041521671666777
![2H A84E%U0CIPBUQG4ORS3C](https://user-images.githubusercontent.com/49268537/62094711-a09ad280-b2b0-11e9-9845-a8d9b99f096b.png)
非偶发情况，麻烦看一下具体原因

**Comment by yanglu-china** [comment]
已开票订单，开票状态会显示可开票或部分开票，麻烦查一下

**Comment by kingofhawks** [comment]
SO1906031513666024378
SO1907111658672906021、SO1907150842673632305

**Comment by kingofhawks** [comment]
SO1906031513666024378
SO1907111658672906021、SO1907150842673632305
SO1906031513666024366，SO1906031513666024378

**Comment by kingofhawks** [comment]
有多个不同成本商品行的，导入开票时，base表中invoiceMoney未设置。
