### ISSUE TITLE
客户预收查不到

### ISSUE THREAD

**Issue by 39189058** [qianlimu/yycoin#736]
张贤(164482901)  9:28:03
回款单：HK201907311076957484中收付款单SF201908011277195750显示款在专员-刘玉彬-三部的客户：中原银行信阳工商支行-银行名下，但是客户预收中没有，麻烦看一下，谢谢@顾立强 @王旭平

![image](https://user-images.githubusercontent.com/28384119/62434074-be14e400-b769-11e9-9c1a-792c9767fe96.png)
![image](https://user-images.githubusercontent.com/28384119/62434083-c9680f80-b769-11e9-971e-0def98f001da.png)
![image](https://user-images.githubusercontent.com/28384119/62434093-d127b400-b769-11e9-8fdf-a2e4021b1503.png)

**Comment by kingofhawks** [comment]
SF201908011277195750这个收款单似乎不是JOB生成的

**Comment by kingofhawks** [comment]
SF201908011277195750这个收款单似乎不是JOB生成的

**Comment by kingofhawks** [comment]
HK201907291076485970中收付款单SF201907291576520953显示款在专员-丁雅楠-三部的客户：中原银行郑州分行营业部-银行名下，但是客户预收中没有这笔收付款单

**Comment by kingofhawks** [comment]
增加了回款单：HK201908061450989249，先认领这笔款到了"兴业银行北京顺义天竺支行-银行"客户预收里，从客户预收进行批量的拆款，在拆款的一批订单中有两笔订单是驳回状态，然后我进行拆款显示成功，驳回两个订单对应的款显示在我驳回订单的客户预收里面“兴业银行北京首体支行-银行”，但实际的客户预收里面没有

根据业务部门反馈勾款异常还由两个场景：1.订单在待商务状态下勾款完成之后，待库管审批的时候驳回了；
                                                             2.订单出现退货状态，预收没有回到客户名下；

**Comment by kingofhawks** [comment]
SF201908080978333639    SF201908080978333646
HK201908080978333010
