### ISSUE TITLE
产品合成&拆分税率校验功能需求

### ISSUE THREAD

**Issue by yanglu-china** [qianlimu/yycoin#742]

**Comment by kingofhawks** [comment]
[产品合成&拆分税率校验功能需求20190809.xlsx](https://github.com/qianlimu/yycoin/files/3485542/20190809.xlsx)

**Comment by kingofhawks** [comment]
1、产品合成时做税率校验功能，相同税率配件金额占比最大的，决定成品的税率，如下图所示：成品名是“ YZ0541300 某年月日含17福字币20g银章生日钞含包装（普2）”
结论：配件中普2金额占比>普13金额占比>普6占比；成品名的税率应该为“普2”；对比成品品名“ YZ0541300 某年月日含17福字币20g银章生日钞含包装（普2）”税率标识是“普2”；校验后通过合成指令；
假使对比后配件中金额占比最大的税率与成品名税率标识不一致，则不能合成，系统报错，提示：配件金额占比最大的税率与成品名税率标识不一致，请重新确认合成配件。
注意：如出现占比相同的时候同样报错。

**Comment by kingofhawks** [comment]
2、产品拆分时做税率校验功能，相同税率配件金额占比最大的，要与成品名中标识的税率保持一致，如下图所示：成品名是“ YZ0543800 《祝福祖国》建国50周年纪念钞含19福字币中钞封装版（十连套装）（新版）（普2）”
结论：配件中普2金额占比>普13金额占比>普3金额占比>普16金额占比；金额占比最高的税率是“普2”；对比成品品名“  YZ0543800 《祝福祖国》建国50周年纪念钞含19福字币中钞封装版（十连套装）（新版）（普2）”税率标识是“普2”，税率一致，校验后通过拆分指令；
假使对比后配件中金额占比最大的税率与成品名税率标识不一致，则不能拆分，系统报错，提示：配件金额占比最大的税率与成品名税率标识不一致，请重新确认拆分配件。
注意：如出现占比相同的时候同样报错。
