### ISSUE TITLE
平台手续费凭证修改

### ISSUE THREAD

**Issue by yanglu-china** [qianlimu/yycoin#744]
申请单申请类型为平台手续费时，生成凭证中的  中收5504-47 变更为 5504-56，例：UT201906051066322878

**Comment by kingofhawks** [comment]
这个体内的麻烦修改为5504-55，体外的是5504-56

**Comment by kingofhawks** [comment]
insert into t_center_sysconfig(id,CONFIG, VALUE) values(42, 'APP_NAME','永银ERP');
insert into t_center_sysconfig(id,CONFIG, VALUE) values(42, 'APP_NAME','永银ERP(体外)');
