### ISSUE TITLE
体内&体外OA采购退货功能优化需求

### ISSUE THREAD

**Issue by yanglu-china** [qianlimu/yycoin#745]

**Comment by kingofhawks** [comment]
[体内&体外OA采购退货功能优化需求20190809.xlsx](https://github.com/qianlimu/yycoin/files/3488641/OA.20190809.xlsx)

**Comment by kingofhawks** [comment]
采购退货现在的审批流实际操作人是按照这个来的：发起人--待事业部经理审批（金加波，实际岗位是：生产采购经理审批）--待总裁审批（袁玉红，实际岗位是：分管副总裁审批）--待董事长审批（吉文静，实际岗位是：财务总监审批），因为要废弃现在的退货模式（增加入库单）， 所以要新做审批流，按照“发起人--生产采购经理审批--分管副总裁审批--财务总监审批”这个来，但是审批人还是原来的人

**Comment by 39189058** [comment]
南京-周苏东(70907255) 2019/9/11 8:41:56
采购退货有两种场景，一种是未拿货退货，另一种是拿货入库后退货

南京-周苏东(70907255) 2019/9/11 8:42:32
第一种是无需扣减库存，不生成凭证；第二种需扣减库存，生成凭证

南京-周苏东(70907255) 2019/9/11 8:47:25
第二种情况会再分三种场景：退货商品成本等于采购单成本，退货商品成本高于采购单成本，退货商品成本低于采购单成本，

**Comment by kingofhawks** [comment]
1、提交时多个商品行的情况，每行生成一个入库单
2、已入库退货，需要填写发货信息，参考到货调拨页面。在商品行后加个链接，跳转到发货信息页面。

**Comment by 39189058** [comment]
南京-周苏东(70907255)  16:58:13
采购退货提交时，供应商如果只有一个，就不用选了，默认带出，如果多个才选择，必输项，纳税实体和发票类型也一样

南京-周苏东(70907255)  16:59:55
未入库退货数量不能大于这张采购单商品的未入库数量-已退货数量

南京-周苏东(70907255)  17:00:03
已入库数量退货不能大于这张采购单的入库数量-已退货数量

**Comment by 39189058** [comment]
产品选择弹出列表，加产品名筛选

**Comment by 39189058** [comment]
采购退货后，要设置库存预占或者在途状态

**Comment by kingofhawks** [comment]
产品合成损益(5505-33)科目，借方金额=（入库单的库存成本-原采购单成本）*数量
根据供应商+产品，找到原采购单上对应的采购行。

**Comment by 39189058** [comment]
董源苑(694635482)  15:14:09
@顾立强 顾工，您好~采购退货还有两个地方需要优化一下：一、退单生成后就扣减库存的问题；二、采购单上需关联显示退货单据号的问题

**Comment by kingofhawks** [comment]
1、从两个供应商处采购同一商品各100，200个，并且全部拿货。退货时按照-100和-200提交时，会报超出数量。
2、“已入库退货”提交的时候，如果发货信息还没填，应该不允许提交

**Comment by 39189058** [comment]
bug 操作步骤：
我选了已入库退货，产品选的是2012年的熊猫银币做退货，选的库存货是网络交易库的，库存数量为9；我选的是供应商是“深圳市东方豪雅珠宝有限公司”（非故意选的，我以为我退的是2014年的熊猫银币），结果提交时正常提交了，未做校验；
生成了退货单，退货单上的供应商是“深圳市东方豪雅珠宝有限公司”，审批也都通过了；
结果采购订单上的退货记录供应商系统自动变更为了“山金金控（深圳）黄金投资发展有限公司”（如图所示）；@顾立强

要加几个校验：
1、如果先选择了采购退货产品，选择供应商的时候带出来的供应商，只能是与产品相匹配的供应商名称；
2、且必须先选择产品才可以选择供应商；
3、同一采购订单的同一产品采购退货总数量小于等于采购数量；
4、采购退货数量为0，不可提交；

**Comment by 39189058** [comment]
库存扣减在采购退货申请提交时做，凭证生成、CK单生成移到审批通过之后。

**Comment by 39189058** [comment]
董源苑(694635482) 2019/10/10 17:29:26
@顾立强 顾工，您好！采购退货审批流需要进行一些调整。
1、审批步骤名称：“采购退货-分管副总裁审批”改为“采购退货-运营总监审批”；“采购退货-财务总监审批”改为“采购退货-分管副总裁审批”；
2、审批流根据退单的总金额做如下控制：
退单总金额小于等于10万元，申请人--生产采购部经理审批--结束；
退单总金额大于10万元，小于等于50万元，申请人--生产采购部经理审批--运营总监审批--结束；
退单总金额大于50万元，申请人--生产采购部经理审批--运营总监审批--分管副总裁审批--结束；
3、在审批通过结束后推送单据给财务总监查阅；
4、增加一个“查看所有采购退货单”的菜单栏，显示所有采购退单；

**Comment by 39189058** [comment]
心在沉淀  13:55:56
退货总金额=退货单价*数量；
采购总金额=采购单价*数量；
产品合成损益=（采购单价-退货单价）*数量

心在沉淀  13:56:15
贷方就是采购总金额

**Comment by 39189058** [comment]
心在沉淀  13:55:56
退货总金额=退货单价*数量；
采购总金额=采购单价*数量；
产品合成损益=（采购单价-退货单价）*数量

心在沉淀  13:56:15
贷方就是采购总金额

发货信息填写，要根据“源仓库”判断，“未入库退货”和“已入库退货”中源仓库是【生产作业库】的单子不用填写发货信息；

**Comment by 39189058** [comment]
昨天测试又发现了一个问题，采购订单还未经过生产采购经理审批这一步，就可以发起退货~这个地方需要控制一下，如果订单状态还是“待采购经理审批”不可以做采购退货的操作
