### ISSUE TITLE
未回款订单预借激励费用的功能需求

### ISSUE THREAD

**Issue by zhangxian** [qianlimu/yycoin#754]
[预借激励费用开发说明.docx](https://github.com/qianlimu/yycoin/files/3499920/default.docx)

**Comment by kingofhawks** [comment]
预借激励费用开发说明
一．	概述
现有激励费用申请需勾款后才进可申请激励清单，未勾款订单无法申请激励，导致较多预借激励费用的申请及后续冲抵，效率较低，现将未勾款的订单的激励申请放开，做成单独的申请类型，后续订单勾款时，抵扣已申请的激励费用
二．	功能
1.	OA创建”未回款订单激励费用申请” 单据类型,单据审批流同“激励申请”单据审批流，同样同步至体外系统进行支付。此单据也通过批量导入端口导入生成，校验条件为激励状态为0，付款状态为0的销售单，申请提交时，也与原激励申请一致，将激励标识与单号写入OUT表，驳回时清除标识和申请单号信息
批量导入的端口是：报销管理—中收激励申请导入
审批流：初始->待省级经理审批->待总监审批->待大区总经理审批->待事业部总经理审批->待副总裁审批->结束
2.	OA创建“未回款订单激励费用申请”明细表（样式同“OA—报销管理--我的激励申请”），申请提交时，记录销售订单号，客户名，商品ID，商品名，数量，激励金额，申请时间，申请单号等信息，驳回时删除申请单相关的订单的信息。
3.	在帆软创建未回款订单激励费用申请统计表及明细表，统计表记录各订单相关业务员所申请的未回款订单申请激励的总金额，销售总金额，已申请激励总金额，已回款总销售额，已回款订单激励总金额，未回款已付激励订单总金额，未回款已付激励总金额。
点击各金额，跳转至对应明细清单，包括订单号、客户名、商品名、数量、销售金额、激励金额，激励申请时间，激励申请单号，回款状态，回款时间等信息

**Comment by kingofhawks** [comment]
类似激励申请一样，只是取消检查付款状态？

**Comment by kingofhawks** [comment]
UT201908161551016404

**Comment by kingofhawks** [comment]
INSERT INTO uportal.t_center_oamenuitem (id, MENUITEMNAME, URL, PARENTID, BottomFlag, AUTH, indexPos, description) VALUES ('1912', '我的未回款订单激励申请', '../tcp/querySelfTravelApply17.jsp', '19', 1, '0000', 5, '我的未回款订单激励申请');
