### ISSUE TITLE
开单模板优化

### ISSUE THREAD

**Issue by yanglu-china** [qianlimu/yycoin#761]
![image](https://user-images.githubusercontent.com/49268537/64167696-7f636e00-ce7c-11e9-8ded-f0385375c58e.png)

![image](https://user-images.githubusercontent.com/49268537/64167687-7a062380-ce7c-11e9-9db6-5a413804d20b.png)
原中信端口导入数据，分行取业务部门导入的数据，修改为自动从客户职员对照表中业务部门导入的网点所对应的一级分行如图：
![image](https://user-images.githubusercontent.com/49268537/64167784-b2a5fd00-ce7c-11e9-8cc5-8dcaf531ed25.png)
select * from t_center_customer_main c
left outer join   t_center_vs_stacus a  on (a.customerid=c.id)

**Comment by kingofhawks** [comment]
select * from t_center_customer_main c
left outer join t_center_vs_stacus a on (a.customerid=c.id) where c.name='comunicatonBranchName网点名称'

**Comment by kingofhawks** [comment]
1、导入模板中的分行名称是否去掉？是的
2、把查询到的分行名称直接写入out_import表是吧？是的
3、如果查询到分行名称字段为空，导入时直接报错吗？是的
