### ISSUE TITLE
中收申请优化

### ISSUE THREAD

**Issue by yanglu-china** [qianlimu/yycoin#763]
把中收申请的“待财务入账”环节取消，因为凭证已经在财务支付环节生成，无需财务入账，财务支付通过后，结束

**Comment by kingofhawks** [comment]
中收，中收2，平台手续费的流程都是一样的，是否三个类型都要改？

**Comment by kingofhawks** [comment]
CREATE TABLE uportal.t_center_tcpflow
(
    ID int(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    flowKey varchar(200) NOT NULL,
    tokenName varchar(200),
    nextPlugin varchar(50),
    currentStatus int(11) DEFAULT '0' NOT NULL,
    nextStatus int(11) DEFAULT '0' NOT NULL,
    singeAll int(11) DEFAULT '0' NOT NULL,
    reject int(11) DEFAULT '0' NOT NULL,
    rejectToPre int(11) DEFAULT '0' NOT NULL,
    begining int(11) DEFAULT '0' NOT NULL,
    ending int(11) DEFAULT '0' NOT NULL
);
CREATE UNIQUE INDEX U_ALL1 ON uportal.t_center_tcpflow (flowKey, currentStatus);
CREATE UNIQUE INDEX U_ALL2 ON uportal.t_center_tcpflow (flowKey, nextStatus);
CREATE INDEX I_flowKey ON uportal.t_center_tcpflow (flowKey);
INSERT INTO uportal.t_center_tcpflow (ID, flowKey, tokenName, nextPlugin, currentStatus, nextStatus, singeAll, reject, rejectToPre, begining, ending) VALUES (831, 'travel-ib-apply', null, 'group:A220140415000200001', 0, 28, 0, 1, 0, 1, 0);
INSERT INTO uportal.t_center_tcpflow (ID, flowKey, tokenName, nextPlugin, currentStatus, nextStatus, singeAll, reject, rejectToPre, begining, ending) VALUES (832, 'travel-ib-apply', null, 'group:A220110406000200005', 28, 6, 0, 1, 0, 0, 0);
INSERT INTO uportal.t_center_tcpflow (ID, flowKey, tokenName, nextPlugin, currentStatus, nextStatus, singeAll, reject, rejectToPre, begining, ending) VALUES (833, 'travel-ib-apply', null, 'pool:A220110406000200007', 6, 20, 0, 1, 0, 0, 0);
INSERT INTO uportal.t_center_tcpflow (ID, flowKey, tokenName, nextPlugin, currentStatus, nextStatus, singeAll, reject, rejectToPre, begining, ending) VALUES (834, 'travel-ib-apply', null, 'plugin:travelSingeAll', 20, 21, 0, 1, 0, 0, 0);
INSERT INTO uportal.t_center_tcpflow (ID, flowKey, tokenName, nextPlugin, currentStatus, nextStatus, singeAll, reject, rejectToPre, begining, ending) VALUES (835, 'travel-ib-apply', null, 'pool:A220110406000200008', 21, 22, 1, 1, 0, 0, 0);
INSERT INTO uportal.t_center_tcpflow (ID, flowKey, tokenName, nextPlugin, currentStatus, nextStatus, singeAll, reject, rejectToPre, begining, ending) VALUES (836, 'travel-ib-apply', null, 'group:A220110406000200009', 22, 23, 0, 1, 0, 0, 0);
INSERT INTO uportal.t_center_tcpflow (ID, flowKey, tokenName, nextPlugin, currentStatus, nextStatus, singeAll, reject, rejectToPre, begining, ending) VALUES (837, 'travel-ib-apply', null, 'end:end', 23, 99, 0, 0, 0, 0, 1);
