### ISSUE TITLE
更新订单批量导入模板

### ISSUE THREAD

**Issue by yanglu-china** [qianlimu/yycoin#770]
更新订单批量导入模板，删除“开票要求（税号）”，在原位置增加四个字段：增值税--购方名称、增值税--购方税号、增值税--银行信息、增值税--购方地址电话，分别对应out_import表的gfmc,gfsh,gfyh,gfdz

**Comment by kingofhawks** [comment]
ALTER TABLE t_center_out_import ADD COLUMN (gfmc VARCHAR(64),gfsh VARCHAR(64), gfyh VARCHAR(64),gfdz VARCHAR(64));
