### ISSUE TITLE
增加“退货付款类型”

### ISSUE THREAD

**Issue by yanglu-china** [qianlimu/yycoin#775]
入库单流程：
1.在out表增加退货付款类型字段，用来标识销售退单的回款性质
2.退货付款类型包括：1.已回款退货，2.未回款退货
3.在 入库-总部核对 的导出结果中， 增加此字段
4.在销售退货单生成时，根据原单的付款情况，标识付款类型，如提交时原单付款标识为0，则提交的销售退单付款类型为"未回款退货“，反之为”已回款退货“

**Comment by kingofhawks** [comment]
不能直接用pay这个字段吗？

**Comment by kingofhawks** [comment]
销售单流程:
1.销售订单付款状态标识PAY标识为1时，利用退货付款字段，标识付款类型
                  2.当销售单有收款单勾稽时，付款类型字段值设为3，实际收款完成
                  3.当销售单退货触发销售单付款状态变更时，判断原销售单的付款状态PAY为1时，付款类型字段设为4，实际付款退货
                 4.  当销售单退货触发销售单付款状态变更时，判断原销售单的付款状态PAY为0时，付款类型字段设为5，未付款退货

**Comment by kingofhawks** [comment]
smartman(2054958070) 2019/10/09 14:29:58
是的，退货会触发状态变化吗？
周苏东(70907255) 2019/10/09 14:30:34
会，如果全部退货，原销售单的付款状态都会变为1
不管有没真实付过款

**Comment by kingofhawks** [comment]
ParentOutAction.submitOut2()  line 7940 outManager.payOut

**Comment by kingofhawks** [comment]
这个状态变更，是不是只会从0变成1？会从1变成0吗？
@周苏东 
周苏东(70907255)  9:33:16
不会
smartman(2054958070)  9:33:35
那这样就只会出现4这种情况呢
3这种情况是不是就不会出现？
smartman(2054958070)  9:34:43
3这种情况就是原销售单PAY=1，现在退货时，还是1，状态并没有变更。
周苏东(70907255)  9:35:04
3，就指销售单先勾款，付款标识为1，然后全部退货，付款标识还是1，只是新增的付款类型字段要设为4，标识销售单原来是付过款的
付款状态还是1，是不变的
smartman(2054958070)  9:37:23
我再理一下，销售单勾款，PAY=1，新增的付款类型字段要设为3；然后退货，付款标识还是1，只是新增的付款类型字段要设为4。如果原单据PAY=0，直接退货了，付款类型字段要设为5。是这样吧？
周苏东(70907255)  9:38:10
对
smartman(2054958070)  9:38:18
好的

**Comment by kingofhawks** [comment]
SO1908121610678702408

**Comment by kingofhawks** [comment]
alter table t_center_out add column backPay int(11) default 0;
