### ISSUE TITLE
调拨脚本调整

### ISSUE THREAD

**Issue by yanglu-china** [qianlimu/yycoin#779]
1.销售单调整：内部销售，调拨后会进入销售单表t_center_olout及t_center_olbase表，系统为体外，销售价为0，结算价为维护的（成本单价-销售单价）负值，olbase新增结算价字段settleprice。（已完成）
OA的定时任务程序需修改为结算价字段有值则取，无值按原定逻辑取值（体内同样新增，但是体内不需要计算）

**Comment by kingofhawks** [comment]
周苏东(70907255) 2019/10/16 13:33:23
@smartman settleprice字段有值，则写入BASE表中的pprice和iprice中，如果settleprice字段没有值，按原来的结算价取值逻辑取值
smartman(2054958070) 2019/10/16 13:34:55
base表那几个字段都取这个值是吧？
周苏东(70907255) 2019/10/16 13:35:18
对

**Comment by kingofhawks** [comment]
alter table t_center_frdb add column settleprice double(10,2) default 0;

**Comment by kingofhawks** [comment]
D191011092609152000792
