### ISSUE TITLE
采购付款-申请异常

### ISSUE THREAD

**Issue by yanglu-china** [qianlimu/yycoin#786]
![image](https://user-images.githubusercontent.com/49268537/65829934-2ea92e80-e2dd-11e9-9515-572839f364bd.png)
采购付款-申请中，原单拆分申请了部分金额，产生了一条初始未申请的数据，在原申请付款订单驳回时，所以应的剩余金额的数据应该同步删除

**Comment by kingofhawks** [comment]
![1NV`76CHOC75J~OV}~5(7TI](https://user-images.githubusercontent.com/45868/67009877-2c3d3600-f11f-11e9-9b29-52b3dfd80d5f.jpg)

**Comment by kingofhawks** [comment]
![YX 93E7}09R7KYP@X8S7@BP](https://user-images.githubusercontent.com/45868/67009891-37906180-f11f-11e9-88e5-d0e2186b3db9.png)
采购付款的时候，我申请部分付款，实际付出了100，然后会生成另一条2000的初始状态未付款的单子

**Comment by kingofhawks** [comment]
![5Y~YXEZXG6R$J6M`Y_L~U)8](https://user-images.githubusercontent.com/45868/67009915-41b26000-f11f-11e9-8b31-fb04d451ff3f.png)
当驳回申请的付款单时，对应当时产生的2000的未付款单应该删除掉
