### ISSUE TITLE
退货校验优化

### ISSUE THREAD

**Issue by yanglu-china** [qianlimu/yycoin#797]
商务在OA退单的时候校验，实际的可退数再减去待物流收货，待核对做单，待销助确认，待物流拆包，待一键提交的数据
select sum(b.outamount) from t_center_outback a left join 
t_center_outback_product b on a.transportNo = b.transportno where a.status in ('1','2','3','4','6') and (b.complete is null or LENGTH(b.complete) = 0)

**Comment by kingofhawks** [comment]
create table t_center_outback_product
(
	id int auto_increment
		primary key,
	outtype varchar(255) null,
	sys varchar(10) null,
	fullid varchar(255) null,
	productname varchar(255) null,
	outamount varchar(255) null,
	staffer varchar(255) null,
	outreason varchar(255) null,
	expresscompany varchar(255) null,
	transportno varchar(255) null,
	bz varchar(255) null,
	creatername varchar(255) null,
	createtime datetime null,
	sign varchar(10) null,
	complete varchar(255) null,
	rklx_lp varchar(10) null,
	rklx_xf varchar(10) null,
	rklx_bl varchar(10) null,
	rklx_qt varchar(10) null
)
;

**Comment by kingofhawks** [comment]
现在LT1910221701652563024存在10个状态是1，但是在退货的时退11个没有任何报错还是能提交
