### ISSUE TITLE
退单单品异常

### ISSUE THREAD

**Issue by yanglu-china** [qianlimu/yycoin#825]
SO1910310939685832920，XT1911011750686035041
销售单单品奖励为正值，退单单品奖励为0
![image](https://user-images.githubusercontent.com/49268537/68662958-ca82b700-0578-11ea-8e6a-2d5be10cde3c.png)

**Comment by kingofhawks** [comment]
确认一下是否退单的中收激励金额都与原单一致？如cash,cash2,platformFee等多个字段
