### ISSUE TITLE
中信银行退款信息表

### ISSUE THREAD

**Issue by yanglu-china** [qianlimu/yycoin#837]
[中信银行退款信息表.xlsx](https://github.com/qianlimu/yycoin/files/3873378/default.xlsx)

**Comment by kingofhawks** [comment]
INSERT INTO uportal.t_center_oamenuitem (id, MENUITEMNAME, URL, PARENTID, BottomFlag, AUTH, indexPos, description) VALUES ('1638', '中信银行预收退款查询', '../backprepay/queryCiticBackPrePay.jsp', '16', 1, '1637', 99, null);

**Comment by kingofhawks** [comment]
中信订单号和OA单号如何取到？

**Comment by kingofhawks** [comment]
目的：中信银行萍乡安源支行-银行订单号728311201909290316863448
