### ISSUE TITLE
体外同步生成订单优化

### ISSUE THREAD

**Issue by yanglu-china** [qianlimu/yycoin#843]
体内外同步生成订单，申请生成的体外订单默认仓库：  
 物流作业库-体外  (A1201809281431327543)
物流作业-已合成预占仓(A1201809281431327544)，
发货方式是默认自提，并打标成虚拟订单

**Comment by yanglu-china** [comment]
![image](https://user-images.githubusercontent.com/49268537/69522282-fb60e400-0f9b-11ea-9594-c62e786151d7.png)
生成的订单单价取t_center_twthproduct中的twprice
金额=数量*单价

**Comment by kingofhawks** [comment]
SOTW1912090849007365002

**Comment by kingofhawks** [comment]
处理异常:核算项中部门不存在,ID:[679655470]

**Comment by kingofhawks** [comment]
主单发货方式：第三方/自提，仓库：物流中心-可发库  可发成品仓/各种预占仓，体外订单的仓库：物流作业库-体外  物流作业-已合成预占仓，发货方式：自提

主单：发货方式是：空发，仓库：空退空开库（仅限商务部操作）  空退空开库（仅限商务部操作）_默认仓区/代发库--南京物流中心  代发库--南京物流中心_默认仓区
体外订单跟着主单走，仓库：空退空开库（仅限商务部操作）  空退空开库（仅限商务部操作）_默认仓区/代发库--直发产品专用  代发仓，发货方式：空发

**Comment by yanglu-china** [comment]
麻烦您调整一下offlineOrderJob脚本，体外的 t_center_olout 表里我新增了virtualstatus字段， 当virtualstatus值为1时，标记为虚拟订单，体外订单的仓库：物流作业库-体外 物流作业-已合成预占仓，发货方式：自提，其他取值逻辑不变

**Comment by kingofhawks** [comment]
SOTW2001060959007456191

**Comment by kingofhawks** [comment]
SOTW2001071350007461450
