### ISSUE TITLE
开票接口的开票税率取值逻辑更改

### ISSUE THREAD

**Issue by yanglu-china** [qianlimu/yycoin#854]
开票接口的开票税率取值逻辑更改，先用开票品名到表t_center_invoice_kp找对应name的kpslid字段，如未找到相同名称的，再取销售单中产品在product表中对应的kpslid字段值，如还未取到，默认为 工艺品

**Comment by kingofhawks** [comment]
create table uportal.t_center_invoice_kp
(
	ID int auto_increment
		primary key,
	name varchar(255) null,
	kpslid int(20) null
)
;
