### ISSUE TITLE
批量退票需求

### ISSUE THREAD

**Issue by yanglu-china** [qianlimu/yycoin#859]
商务申请退票需逐个登录业务员OA账号一个一个进行申请，操作繁琐，已拟定批量退票需求
[商务+批量退票优化需求+M311911111147.xlsx](https://github.com/qianlimu/yycoin/files/3920915/%2B.%2BM311911111147.xlsx)

**Comment by kingofhawks** [comment]
SO1912110859653547335

**Comment by kingofhawks** [comment]
A1201909231651653445

**Comment by kingofhawks** [comment]
SO1909231513651653054
