### ISSUE TITLE
offlineOrderJob虚拟订单调整

### ISSUE THREAD

**Issue by kingofhawks** [qianlimu/yycoin#867]
体外的 t_center_olout 表里新增了virtualstatus字段， 当virtualstatus值为1时，标记为虚拟订单，并且设置默认值，体外订单的仓库：物流作业库-体外 物流作业-已合成预占仓，发货方式：自提，其他取值逻辑不变

**Comment by kingofhawks** [comment]
SOTW1912241853007406181

**Comment by kingofhawks** [comment]
D575752935201912240644

**Comment by yanglu-china** [comment]
SOTW1912251139007409017
