### ISSUE TITLE
退货控制异常

### ISSUE THREAD

**Issue by yanglu-china** [qianlimu/yycoin#868]
![VWL`HVS%PN6WF@Q42`~$)XL](https://user-images.githubusercontent.com/49268537/70791042-3606b100-1dd1-11ea-9d9f-a445e63b6c10.png)
快递单号：SF1004460183876中订单XZ1909071206681019128，在帆软中处于待销助确认状态时，oa商务空开空退端口未进行该状态的可退数量校验

**Comment by kingofhawks** [comment]
SOTW1909051145003510207，SOTW1909051145003510210

**Comment by kingofhawks** [comment]
LT1912241503691932445无法确认退库

**Comment by kingofhawks** [comment]
CREATE TABLE MY_TABLE (
  id INT,
  inway INT,
  productId VARCHAR,
  unit VARCHAR,
  amount INT,
  price DOUBLE,
  costPrice DOUBLE,
  costPriceKey VARCHAR,
  value DOUBLE,
  owner VARCHAR,
  ownerName VARCHAR,
  locationId VARCHAR,
  description VARCHAR,
  productName VARCHAR,
  showName VARCHAR,
  showId VARCHAR,
  outId VARCHAR,
  storageId VARCHAR,
  depotpartName VARCHAR,
  depotpartId VARCHAR,
  inputPrice DOUBLE,
  mtype INT,
  invoiceMoney DOUBLE,
  pprice DOUBLE,
  iprice DOUBLE,
  deliverType INT,
  expressPay INT,
  transportPay INT,
  profit DOUBLE,
  profitRatio DOUBLE,
  oldGoods INT,
  taxrate DOUBLE,
  tax DOUBLE,
  inputRate DOUBLE,
  refId VARCHAR,
  ibMoney DOUBLE,
  motivationMoney DOUBLE,
  profitmoney DOUBLE,
  grossProfit DOUBLE,
  checkgrossProfit DOUBLE,
  cash DOUBLE,
  ibMoney2 DOUBLE,
  motivationMoney2 DOUBLE,
  platformFee DOUBLE,
  productImportId VARCHAR,
  ykibMoney DOUBLE,
  cash2 DOUBLE,
  virtualPrice DOUBLE,
  virtualPriceKey VARCHAR,
  project_id VARCHAR
);
INSERT INTO MY_TABLE(id, inway, productId, unit, amount, price, costPrice, costPriceKey, value, owner, ownerName, locationId, description, productName, showName, showId, outId, storageId, depotpartName, depotpartId, inputPrice, mtype, invoiceMoney, pprice, iprice, deliverType, expressPay, transportPay, profit, profitRatio, oldGoods, taxrate, tax, inputRate, refId, ibMoney, motivationMoney, profitmoney, grossProfit, checkgrossProfit, cash, ibMoney2, motivationMoney2, platformFee, productImportId, ykibMoney, cash2, virtualPrice, virtualPriceKey, project_id) VALUES (3511375, 0, '76', '套', 5, 550, 570, '57000', 2750, '0', '公共', 'A1201809281431327543', '', 'TWYZ0001800 中国经典钱币第三四五套人民币珍藏册之第四五轮纪念钞15张小全套（综合定制）（普2）', '', '', 'SOTW1909051145003510207', '', '物流作业-已合成预占仓', 'A1201809281431327544', 512, 0, 0, 512, 512, 0, -1, -1, 190, 0.06909090909090909, -1, 0.02, 0, 0, '', 0, 0, null, 0, null, 0, 0, 0, 0, '', 0, 0, 0, '0', '0');
INSERT INTO MY_TABLE(id, inway, productId, unit, amount, price, costPrice, costPriceKey, value, owner, ownerName, locationId, description, productName, showName, showId, outId, storageId, depotpartName, depotpartId, inputPrice, mtype, invoiceMoney, pprice, iprice, deliverType, expressPay, transportPay, profit, profitRatio, oldGoods, taxrate, tax, inputRate, refId, ibMoney, motivationMoney, profitmoney, grossProfit, checkgrossProfit, cash, ibMoney2, motivationMoney2, platformFee, productImportId, ykibMoney, cash2, virtualPrice, virtualPriceKey, project_id) VALUES (4300010, 0, '76', '套', 2, 550, 570, '57000', 1100, '0', '公共', '99000000000000000002', '', 'TWYZ0001800 中国经典钱币第三四五套人民币珍藏册之第四五轮纪念钞15张小全套（综合定制）（普2）', '', '', 'XT1911221055004300009', '', '可发成品仓', '1', 507, 0, 0, 507, 507, -1, -1, -1, 0, 0, -1, 0, 0, 0, '', 0, 0, null, 0, -43, 0, 0, 0, 0, '', 0, 0, 0, '0', '0');
INSERT INTO MY_TABLE(id, inway, productId, unit, amount, price, costPrice, costPriceKey, value, owner, ownerName, locationId, description, productName, showName, showId, outId, storageId, depotpartName, depotpartId, inputPrice, mtype, invoiceMoney, pprice, iprice, deliverType, expressPay, transportPay, profit, profitRatio, oldGoods, taxrate, tax, inputRate, refId, ibMoney, motivationMoney, profitmoney, grossProfit, checkgrossProfit, cash, ibMoney2, motivationMoney2, platformFee, productImportId, ykibMoney, cash2, virtualPrice, virtualPriceKey, project_id) VALUES (4431216, 0, '76', '套', 1, 550, 570, '57000', 550, '0', '公共', '99000000000000000002', '', 'TWYZ0001800 中国经典钱币第三四五套人民币珍藏册之第四五轮纪念钞15张小全套（综合定制）（普2）', '', '', 'XTTW1912041008004431215', '', '可发成品仓', '1', 507, 0, 0, 507, 507, -1, -1, -1, 0, 0, -1, 0, 0, 0, '', 0, 0, null, 0, null, 0, 0, 0, 0, '', 0, 0, 0, '0', '0');
INSERT INTO MY_TABLE(id, inway, productId, unit, amount, price, costPrice, costPriceKey, value, owner, ownerName, locationId, description, productName, showName, showId, outId, storageId, depotpartName, depotpartId, inputPrice, mtype, invoiceMoney, pprice, iprice, deliverType, expressPay, transportPay, profit, profitRatio, oldGoods, taxrate, tax, inputRate, refId, ibMoney, motivationMoney, profitmoney, grossProfit, checkgrossProfit, cash, ibMoney2, motivationMoney2, platformFee, productImportId, ykibMoney, cash2, virtualPrice, virtualPriceKey, project_id) VALUES (4433329, 0, '76', '套', 1, 550, 570, '57000', 550, '0', '公共', '99000000000000000002', '', 'TWYZ0001800 中国经典钱币第三四五套人民币珍藏册之第四五轮纪念钞15张小全套（综合定制）（普2）', '', '', 'XTTW1912041354004433328', '', '可发成品仓', '1', 507, 0, 0, 507, 507, -1, -1, -1, 0, 0, -1, 0, 0, 0, '', 0, 0, null, 0, null, 0, 0, 0, 0, '', 0, 0, 0, '0', '0');
INSERT INTO MY_TABLE(id, inway, productId, unit, amount, price, costPrice, costPriceKey, value, owner, ownerName, locationId, description, productName, showName, showId, outId, storageId, depotpartName, depotpartId, inputPrice, mtype, invoiceMoney, pprice, iprice, deliverType, expressPay, transportPay, profit, profitRatio, oldGoods, taxrate, tax, inputRate, refId, ibMoney, motivationMoney, profitmoney, grossProfit, checkgrossProfit, cash, ibMoney2, motivationMoney2, platformFee, productImportId, ykibMoney, cash2, virtualPrice, virtualPriceKey, project_id) VALUES (4818845, 0, '76', '套', 1, 550, 570, '57000', 550, '0', '公共', 'A1201310151011526376', '570.0', 'TWYZ0001800 中国经典钱币第三四五套人民币珍藏册之第四五轮纪念钞15张小全套（综合定制）（普2）', '', '', 'XTTW1912301526004818844', '', '空退空开库（仅限商务部操作）_默认仓区', 'A1201310151011526377', 512, 1, 0, 512, 512, -1, -1, -1, 0, 0, -1, 0, 0, 0, '', 0, 0, null, 0, -38, 0, 0, 0, 0, '', 0, 0, 0, '0', '0');

**Comment by kingofhawks** [comment]
INSERT INTO t_center_out(id, fullId, flowId, outTime, managerTime, outType, channel, locationID, location, industryId, industryId2, department, customerId, description, total, hadPay, badDebts, status, type, hasInvoice, invoiceStatus, invoiceId, dutyId, mark, pay, inway, tempType, customerName, phone, stafferName, connector, checks, reday, arriveDate, redate, depotpartId, destinationId, tranNo, refOutFullId, stafferId, managerId, reserve1, reserve2, reserve3, reserve4, reserve5, reserve6, reserve7, reserve8, reserve9, invoiceMoney, curcredit, staffcredit, managercredit, checkStatus, badDebtsCheckStatus, changeTime, mtype, sailType, productType, ratio, vtype, vtypeFullId, pmtype, industryId3, payTime, forceBuyType, eventId, refBindOutId, promValue, promStatus, lastModified, operator, operatorName, logTime, guarantor, feedBackVisit, feedBackCheck, taxTotal, hasRebate, piDutyId, piMtype, piType, piStatus, hasConfirm, hasConfirmInsMoney, emergency, presentFlag, podate, ibFlag, motivationFlag, remoteAllocate, reason, transportNo, swbz, outbackStatus, customerCreated, flowTime, ibApplyId, motivationApplyId, refGiftId, profigflag, cashflag, ibFlag2, ibApplyId2, motivationFlag2, motivationApplyId2, customerDescription, delivery, posPayer, recommendation, platformFlag, platformApplyId, virtualstatus, backPay, buyReturnFlag, buyReturnType) VALUES (3510207, 'SOTW1909051145003510207', 'CITIC', '2019-09-05', '2019-09-05 14:34:00', 0, '', 999, 'A1201809281431327543', '180301084', '180301050', '', '640464001', '数据接口批量导入，银行单号SO1909051040680850247.SO1909051040680850247;退货转预收:SF201911230904309506,;退货转预收:SF201912061004459965,;退货转预收:SF201912061004460048,;退货转预收:SF201909241503706409,', 2750, 0, 0, 4, 0, 0, 0, '90000000000000000098', '90201008080000000001', 0, 1, 0, 97, '安徽淘礼网科技有限公司', '', '李园', '', '', '30', '31/08/2019', '2019-09-24', '', '0', '', '', '536584', '', 0, 0, 2, '', '', '', '', '', '', 0, 0, 0, 0, 0, 0, '2019-09-05 14:34:11', 1, '', '', '', 0, '', 0, '180301014', '2019-09-24 15:45:01', -1, '', '', 0, -1, '2019-12-30', '591963855', '汪艳-商务', '', '', 0, 0, 0, 0, 'COMMON', 1, 0, 1, 0, 0, 0, 0, '2019-09-05', 0, 0, 0, '', '', 'SO1909051040680850247', '', 0, '2019-09-05 14:34:11', '', '', '', 0, 0, 0, '', 0, '', '', '', '', '', 0, '', 1, 4, '0', '0');
INSERT INTO t_center_out(id, fullId, flowId, outTime, managerTime, outType, channel, locationID, location, industryId, industryId2, department, customerId, description, total, hadPay, badDebts, status, type, hasInvoice, invoiceStatus, invoiceId, dutyId, mark, pay, inway, tempType, customerName, phone, stafferName, connector, checks, reday, arriveDate, redate, depotpartId, destinationId, tranNo, refOutFullId, stafferId, managerId, reserve1, reserve2, reserve3, reserve4, reserve5, reserve6, reserve7, reserve8, reserve9, invoiceMoney, curcredit, staffcredit, managercredit, checkStatus, badDebtsCheckStatus, changeTime, mtype, sailType, productType, ratio, vtype, vtypeFullId, pmtype, industryId3, payTime, forceBuyType, eventId, refBindOutId, promValue, promStatus, lastModified, operator, operatorName, logTime, guarantor, feedBackVisit, feedBackCheck, taxTotal, hasRebate, piDutyId, piMtype, piType, piStatus, hasConfirm, hasConfirmInsMoney, emergency, presentFlag, podate, ibFlag, motivationFlag, remoteAllocate, reason, transportNo, swbz, outbackStatus, customerCreated, flowTime, ibApplyId, motivationApplyId, refGiftId, profigflag, cashflag, ibFlag2, ibApplyId2, motivationFlag2, motivationApplyId2, customerDescription, delivery, posPayer, recommendation, platformFlag, platformApplyId, virtualstatus, backPay, buyReturnFlag, buyReturnType) VALUES (4300009, 'XT1911221055004300009', '', '2019-11-22', '', 5, '', 999, '99000000000000000002', '180301084', '180301050', '', '640464001', '线下入库_SOTW1909051145003510207 _6079', 1100, 0, 0, 3, 1, 0, 0, '90000000000000000098', '90201008080000000001', 0, 1, 0, 0, '安徽淘礼网科技有限公司', '', '李园', '', '', '0', '2019-11-22', '2019-11-22', '1', '0', '', 'SOTW1909051145003510207 ', '536584', '', 0, 0, 0, '', '', '', '', '', '', 0, 0, 0, 0, 0, 0, '2019-11-23 09:42:14', 0, '', '', '', 0, '', 0, '180301014', '', -1, '', '', 0, -1, '', '', '系统', '2019-11-22 10:55:02', '', 0, 0, 0, 0, '', -1, -1, -1, 0, 0, 0, 0, '2019-11-22', 0, 0, 0, '', 'SF1013154467485', '', '', 0, '2019-12-26 20:20:30', '', '', '', 0, 0, 0, '', 0, '', '', '', '', '', 0, '', 0, 0, '0', '0');
INSERT INTO t_center_out(id, fullId, flowId, outTime, managerTime, outType, channel, locationID, location, industryId, industryId2, department, customerId, description, total, hadPay, badDebts, status, type, hasInvoice, invoiceStatus, invoiceId, dutyId, mark, pay, inway, tempType, customerName, phone, stafferName, connector, checks, reday, arriveDate, redate, depotpartId, destinationId, tranNo, refOutFullId, stafferId, managerId, reserve1, reserve2, reserve3, reserve4, reserve5, reserve6, reserve7, reserve8, reserve9, invoiceMoney, curcredit, staffcredit, managercredit, checkStatus, badDebtsCheckStatus, changeTime, mtype, sailType, productType, ratio, vtype, vtypeFullId, pmtype, industryId3, payTime, forceBuyType, eventId, refBindOutId, promValue, promStatus, lastModified, operator, operatorName, logTime, guarantor, feedBackVisit, feedBackCheck, taxTotal, hasRebate, piDutyId, piMtype, piType, piStatus, hasConfirm, hasConfirmInsMoney, emergency, presentFlag, podate, ibFlag, motivationFlag, remoteAllocate, reason, transportNo, swbz, outbackStatus, customerCreated, flowTime, ibApplyId, motivationApplyId, refGiftId, profigflag, cashflag, ibFlag2, ibApplyId2, motivationFlag2, motivationApplyId2, customerDescription, delivery, posPayer, recommendation, platformFlag, platformApplyId, virtualstatus, backPay, buyReturnFlag, buyReturnType) VALUES (4431215, 'XTTW1912041008004431215', '', '2019-12-04', '', 5, '', 999, '99000000000000000002', '180301084', '180301050', '', '640464001', '线下入库_SOTW1909051145003510207_6137', 550, 0, 0, 3, 1, 0, 0, '90000000000000000098', '90201008080000000001', 0, 1, 0, 0, '安徽淘礼网科技有限公司', '', '李园', '', '', '0', '2019-12-04', '2019-12-04', '1', '0', '', 'SOTW1909051145003510207', '536584', '', 0, 0, 0, '', '', '', '', '', '', 0, 0, 0, 0, 0, 0, '2019-12-06 10:47:58', 0, '', '', '', 0, '', 0, '180301014', '', -1, '', '', 0, -1, '', '', '系统', '2019-12-04 10:08:30', '', 0, 0, 0, 0, '', -1, -1, -1, 0, 0, 0, 0, '2019-12-04', 0, 0, 0, '', '1138452679425', '', '', 0, '2019-12-06 10:47:58', '', '', '', 0, 0, 0, '', 0, '', '', '', '', '', 0, '', 0, 0, '0', '0');
INSERT INTO t_center_out(id, fullId, flowId, outTime, managerTime, outType, channel, locationID, location, industryId, industryId2, department, customerId, description, total, hadPay, badDebts, status, type, hasInvoice, invoiceStatus, invoiceId, dutyId, mark, pay, inway, tempType, customerName, phone, stafferName, connector, checks, reday, arriveDate, redate, depotpartId, destinationId, tranNo, refOutFullId, stafferId, managerId, reserve1, reserve2, reserve3, reserve4, reserve5, reserve6, reserve7, reserve8, reserve9, invoiceMoney, curcredit, staffcredit, managercredit, checkStatus, badDebtsCheckStatus, changeTime, mtype, sailType, productType, ratio, vtype, vtypeFullId, pmtype, industryId3, payTime, forceBuyType, eventId, refBindOutId, promValue, promStatus, lastModified, operator, operatorName, logTime, guarantor, feedBackVisit, feedBackCheck, taxTotal, hasRebate, piDutyId, piMtype, piType, piStatus, hasConfirm, hasConfirmInsMoney, emergency, presentFlag, podate, ibFlag, motivationFlag, remoteAllocate, reason, transportNo, swbz, outbackStatus, customerCreated, flowTime, ibApplyId, motivationApplyId, refGiftId, profigflag, cashflag, ibFlag2, ibApplyId2, motivationFlag2, motivationApplyId2, customerDescription, delivery, posPayer, recommendation, platformFlag, platformApplyId, virtualstatus, backPay, buyReturnFlag, buyReturnType) VALUES (4433328, 'XTTW1912041354004433328', '', '2019-12-04', '', 5, '', 999, '99000000000000000002', '180301084', '180301050', '', '640464001', '线下入库_SOTW1909051145003510207_6139', 550, 0, 0, 3, 1, 0, 0, '90000000000000000098', '90201008080000000001', 0, 1, 0, 0, '安徽淘礼网科技有限公司', '', '李园', '', '', '0', '2019-12-04', '2019-12-04', '1', '0', '', 'SOTW1909051145003510207', '536584', '', 0, 0, 0, '', '', '', '', '', '', 0, 0, 0, 0, 0, 0, '2019-12-06 10:42:13', 0, '', '', '', 0, '', 0, '180301014', '', -1, '', '', 0, -1, '', '', '系统', '2019-12-04 13:54:30', '', 0, 0, 0, 0, '', -1, -1, -1, 0, 0, 0, 0, '2019-12-04', 0, 0, 0, '', 'SF1014327585723', '', '', 0, '2019-12-06 10:42:13', '', '', '', 0, 0, 0, '', 0, '', '', '', '', '', 0, '', 0, 0, '0', '0');
INSERT INTO t_center_out(id, fullId, flowId, outTime, managerTime, outType, channel, locationID, location, industryId, industryId2, department, customerId, description, total, hadPay, badDebts, status, type, hasInvoice, invoiceStatus, invoiceId, dutyId, mark, pay, inway, tempType, customerName, phone, stafferName, connector, checks, reday, arriveDate, redate, depotpartId, destinationId, tranNo, refOutFullId, stafferId, managerId, reserve1, reserve2, reserve3, reserve4, reserve5, reserve6, reserve7, reserve8, reserve9, invoiceMoney, curcredit, staffcredit, managercredit, checkStatus, badDebtsCheckStatus, changeTime, mtype, sailType, productType, ratio, vtype, vtypeFullId, pmtype, industryId3, payTime, forceBuyType, eventId, refBindOutId, promValue, promStatus, lastModified, operator, operatorName, logTime, guarantor, feedBackVisit, feedBackCheck, taxTotal, hasRebate, piDutyId, piMtype, piType, piStatus, hasConfirm, hasConfirmInsMoney, emergency, presentFlag, podate, ibFlag, motivationFlag, remoteAllocate, reason, transportNo, swbz, outbackStatus, customerCreated, flowTime, ibApplyId, motivationApplyId, refGiftId, profigflag, cashflag, ibFlag2, ibApplyId2, motivationFlag2, motivationApplyId2, customerDescription, delivery, posPayer, recommendation, platformFlag, platformApplyId, virtualstatus, backPay, buyReturnFlag, buyReturnType) VALUES (4818844, 'XTTW1912301526004818844', '', '2019-12-30', '', 5, '', 999, 'A1201310151011526376', '180301084', '180301050', '', '640464001', '销售退库,销售单号:SOTW1909051145003510207. 转订单', 550, 0, 0, 3, 1, 0, 0, '90000000000000000098', '90201008080000000001', 0, 1, 0, 0, '安徽淘礼网科技有限公司', '', '李园', '', '', '0', '', '', '', '0', '', 'SOTW1909051145003510207', '536584', '', 0, 0, 0, '', '', '', '', '', '', 0, 0, 0, 0, 0, 0, '2019-12-30 15:31:17', 1, '', '', '', 0, '', 1, '180301014', '', -1, '', '', 0, -1, '', '3328333', '周苏东', '', '', 0, 0, 0, 0, '', -1, -1, -1, 0, 0, 0, 0, '2019-12-30', 0, 0, 0, '', '转订单', '', '', 0, '2020-01-10 17:00:34', '', '', '', 0, 0, 0, '', 0, '', '', '', '', '', 0, '', 1, 1, '0', '0');

**Comment by kingofhawks** [comment]
INSERT INTO t_center_base(id, inway, productId, unit, amount, price, costPrice, costPriceKey, value, owner, ownerName, locationId, description, productName, showName, showId, outId, storageId, depotpartName, depotpartId, inputPrice, mtype, invoiceMoney, pprice, iprice, deliverType, expressPay, transportPay, profit, profitRatio, oldGoods, taxrate, tax, inputRate, refId, ibMoney, motivationMoney, profitmoney, grossProfit, checkgrossProfit, cash, ibMoney2, motivationMoney2, platformFee, productImportId, ykibMoney, cash2, virtualPrice, virtualPriceKey, project_id) VALUES (3511375, 0, '76', '套', 5, 550, 570, '57000', 2750, '0', '公共', 'A1201809281431327543', '', 'TWYZ0001800 中国经典钱币第三四五套人民币珍藏册之第四五轮纪念钞15张小全套（综合定制）（普2）', '', '', 'SOTW1909051145003510207', '', '物流作业-已合成预占仓', 'A1201809281431327544', 512, 0, 0, 512, 512, 0, -1, -1, 190, 0.06909090909090909, -1, 0.02, 0, 0, '', 0, 0, null, 0, null, 0, 0, 0, 0, '', 0, 0, 0, '0', '0');
INSERT INTO t_center_base(id, inway, productId, unit, amount, price, costPrice, costPriceKey, value, owner, ownerName, locationId, description, productName, showName, showId, outId, storageId, depotpartName, depotpartId, inputPrice, mtype, invoiceMoney, pprice, iprice, deliverType, expressPay, transportPay, profit, profitRatio, oldGoods, taxrate, tax, inputRate, refId, ibMoney, motivationMoney, profitmoney, grossProfit, checkgrossProfit, cash, ibMoney2, motivationMoney2, platformFee, productImportId, ykibMoney, cash2, virtualPrice, virtualPriceKey, project_id) VALUES (4300010, 0, '76', '套', 2, 550, 570, '57000', 1100, '0', '公共', '99000000000000000002', '', 'TWYZ0001800 中国经典钱币第三四五套人民币珍藏册之第四五轮纪念钞15张小全套（综合定制）（普2）', '', '', 'XT1911221055004300009', '', '可发成品仓', '1', 507, 0, 0, 507, 507, -1, -1, -1, 0, 0, -1, 0, 0, 0, '', 0, 0, null, 0, -43, 0, 0, 0, 0, '', 0, 0, 0, '0', '0');
INSERT INTO t_center_base(id, inway, productId, unit, amount, price, costPrice, costPriceKey, value, owner, ownerName, locationId, description, productName, showName, showId, outId, storageId, depotpartName, depotpartId, inputPrice, mtype, invoiceMoney, pprice, iprice, deliverType, expressPay, transportPay, profit, profitRatio, oldGoods, taxrate, tax, inputRate, refId, ibMoney, motivationMoney, profitmoney, grossProfit, checkgrossProfit, cash, ibMoney2, motivationMoney2, platformFee, productImportId, ykibMoney, cash2, virtualPrice, virtualPriceKey, project_id) VALUES (4431216, 0, '76', '套', 1, 550, 570, '57000', 550, '0', '公共', '99000000000000000002', '', 'TWYZ0001800 中国经典钱币第三四五套人民币珍藏册之第四五轮纪念钞15张小全套（综合定制）（普2）', '', '', 'XTTW1912041008004431215', '', '可发成品仓', '1', 507, 0, 0, 507, 507, -1, -1, -1, 0, 0, -1, 0, 0, 0, '', 0, 0, null, 0, null, 0, 0, 0, 0, '', 0, 0, 0, '0', '0');
INSERT INTO t_center_base(id, inway, productId, unit, amount, price, costPrice, costPriceKey, value, owner, ownerName, locationId, description, productName, showName, showId, outId, storageId, depotpartName, depotpartId, inputPrice, mtype, invoiceMoney, pprice, iprice, deliverType, expressPay, transportPay, profit, profitRatio, oldGoods, taxrate, tax, inputRate, refId, ibMoney, motivationMoney, profitmoney, grossProfit, checkgrossProfit, cash, ibMoney2, motivationMoney2, platformFee, productImportId, ykibMoney, cash2, virtualPrice, virtualPriceKey, project_id) VALUES (4433329, 0, '76', '套', 1, 550, 570, '57000', 550, '0', '公共', '99000000000000000002', '', 'TWYZ0001800 中国经典钱币第三四五套人民币珍藏册之第四五轮纪念钞15张小全套（综合定制）（普2）', '', '', 'XTTW1912041354004433328', '', '可发成品仓', '1', 507, 0, 0, 507, 507, -1, -1, -1, 0, 0, -1, 0, 0, 0, '', 0, 0, null, 0, null, 0, 0, 0, 0, '', 0, 0, 0, '0', '0');
INSERT INTO t_center_base(id, inway, productId, unit, amount, price, costPrice, costPriceKey, value, owner, ownerName, locationId, description, productName, showName, showId, outId, storageId, depotpartName, depotpartId, inputPrice, mtype, invoiceMoney, pprice, iprice, deliverType, expressPay, transportPay, profit, profitRatio, oldGoods, taxrate, tax, inputRate, refId, ibMoney, motivationMoney, profitmoney, grossProfit, checkgrossProfit, cash, ibMoney2, motivationMoney2, platformFee, productImportId, ykibMoney, cash2, virtualPrice, virtualPriceKey, project_id) VALUES (4818845, 0, '76', '套', 1, 550, 570, '57000', 550, '0', '公共', 'A1201310151011526376', '570.0', 'TWYZ0001800 中国经典钱币第三四五套人民币珍藏册之第四五轮纪念钞15张小全套（综合定制）（普2）', '', '', 'XTTW1912301526004818844', '', '空退空开库（仅限商务部操作）_默认仓区', 'A1201310151011526377', 512, 1, 0, 512, 512, -1, -1, -1, 0, 0, -1, 0, 0, 0, '', 0, 0, null, 0, -38, 0, 0, 0, 0, '', 0, 0, 0, '0', '0');
