### ISSUE TITLE
产品编码重复

### ISSUE THREAD

**Issue by kingofhawks** [qianlimu/yycoin#871]
YZ0627401 五岳纪念币之东岳（单枚装含塑盒）-方形圆角塑壳（普13）
YZ0627401 五岳纪念币之东岳（单枚装含塑盒）-裸币（普2）

**Comment by kingofhawks** [comment]
这两个产品在product_apply表中refProductId是一样的，但是在product表中又不一样了

**Comment by zhangxian** [comment]
cloesd
