### ISSUE TITLE
精度控制

### ISSUE THREAD

**Issue by yanglu-china** [qianlimu/yycoin#877]
![image](https://user-images.githubusercontent.com/49268537/71495627-c9d48480-2889-11ea-9c85-8fddcb9385a7.png)
![image](https://user-images.githubusercontent.com/49268537/71495632-cd680b80-2889-11ea-8178-983f564e36b0.png)

**Comment by kingofhawks** [comment]
create table uportal.t_center_pay_stockgjlog
(
	id int auto_increment
		primary key,
	providerid varchar(40) not null,
	moneys double(12,2) not null,
	status int(2) null comment '默认0',
	stockid varchar(40) not null,
	stockitemid varchar(40) not null,
	productid varchar(40) null,
	productname varchar(255) null,
	changeuser varchar(40) not null,
	changetime datetime not null,
	type varchar(10) null comment '1:实勾； 2：虚勾'
)
;

**Comment by kingofhawks** [comment]
create table uportal.t_center_pay_stockpregjlog
(
	id int auto_increment comment '预付款勾稽日志id'
		primary key,
	providerid varchar(40) not null comment '供应商id',
	moneys double(12,2) not null comment '勾稽日志',
	status int(2) null comment '默认0',
	stockid varchar(40) not null comment 'stockid',
	stockitemid varchar(40) not null comment 'stockitemid',
	productid varchar(40) not null comment '产品id',
	productname varchar(255) not null comment '产品名称',
	changeuser varchar(40) not null comment '提交人id',
	changetime datetime not null comment '提交时间',
	type varchar(10) null
)
;
