### ISSUE TITLE
空开空退的退单podate取值调整

### ISSUE THREAD

**Issue by yanglu-china** [qianlimu/yycoin#882]
销售单：一键空开空退和退货端口，只要是进空开空退的订单podate都取正单podate
![image](https://user-images.githubusercontent.com/49268537/71806664-5b22d280-30a4-11ea-8df4-1a6dff7fcd70.png)
仓库为：空退空开库（仅限商务部操作） 空退空开库（仅限商务部操作）_默认仓区-->公共
![image](https://user-images.githubusercontent.com/49268537/71806898-016ed800-30a5-11ea-8c48-502e40c0efa4.png)
销售退库端口提交：仓库为：空退空开库（仅限商务部操作） 空退空开库（仅限商务部操作）_默认仓区-->公共
![image](https://user-images.githubusercontent.com/49268537/71806953-206d6a00-30a5-11ea-94c3-2de869b095c5.png)

**Comment by yanglu-china** [comment]
flowtime取当日退单时间

**Comment by yanglu-china** [comment]
退单的outtime等于对应正单的podate

**Comment by kingofhawks** [comment]
只需要改空出空进和空开空退两个入口
