### ISSUE TITLE
菜单项调整

### ISSUE THREAD

**Issue by kingofhawks** [qianlimu/yycoin#893]
删除“回访对帐”
删除“项目管理”
删除“客户信用”
删除“流程管理”
删除“入库管理”中的 金银料*** 功能菜单

**Comment by 39189058** [comment]
delete from `t_center_oamenuitem` where id like '07%';
delete from `t_center_oamenuitem` where id like '09%';
delete from `t_center_oamenuitem` where id like '20%';
delete from `t_center_oamenuitem` where id like '21%';

delete from `t_center_oamenuitem` where id in ('1027','1029','1030','1031');

**Comment by 39189058** [comment]
恢复金银料相关， 1027， 1029， 1030， 1031
