### ISSUE TITLE
OA中信端口取值逻辑调整

### ISSUE THREAD

**Issue by yanglu-china** [qianlimu/yycoin#899]
终端事业部：
1、当职员是孟君，读取在售表BANK= 终端拍卖客户；
2、当职员是非孟君，读取在售表BANK= 终端事业部；
3、如果职员挂靠终端事业部，读取在售表BANK=终端事业部，没找到产品，就再根据客户银行找产品，如还没找到，就报错；
4、OA出库单数量等于折算系数*开单数量；
钱币事业部：
1、如果职员挂靠钱币事业部，读取在售表BANK= 钱币事业部，没找到产品，就再根据客户银行找产品，如还没找到，就报错；
2、OA出库单数量等于折算系数*开单数量；

**Comment by kingofhawks** [comment]
180301093 04-02终端事业部

**Comment by kingofhawks** [comment]
终端拍卖客户改为“零售拍卖客户”
