### ISSUE TITLE
 OA资金导款、收付款单功能优化

### ISSUE THREAD

**Issue by yanglu-china** [qianlimu/yycoin#900]
[OA资金导款、收付款单功能优化需求文档2.7.pdf](https://github.com/qianlimu/yycoin/files/4178506/OA.2.7.pdf)

**Comment by kingofhawks** [comment]
//贷款利息
    String DKLX = "5506-11";

**Comment by yanglu-china** [comment]
[体外OA需求-资金导款、收付款单功能优化需求文档.xlsx](https://github.com/qianlimu/yycoin/files/4260158/OA.-.xlsx)

**Comment by kingofhawks** [comment]
CREATE TABLE MY_TABLE (
  ID VARCHAR,
  parentId VARCHAR,
  parentId0 VARCHAR,
  parentId1 VARCHAR,
  parentId2 VARCHAR,
  parentId3 VARCHAR,
  parentId4 VARCHAR,
  parentId5 VARCHAR,
  parentId6 VARCHAR,
  parentId7 VARCHAR,
  parentId8 VARCHAR,
  code VARCHAR,
  ptype VARCHAR,
  name VARCHAR,
  bname VARCHAR,
  refId VARCHAR,
  refType INT,
  type INT,
  status INT,
  bottomFlag INT,
  level INT,
  forward INT,
  unit INT,
  department INT,
  staffer INT,
  depot INT,
  product INT,
  duty INT,
  checkStaffer INT
);
INSERT INTO MY_TABLE(ID, parentId, parentId0, parentId1, parentId2, parentId3, parentId4, parentId5, parentId6, parentId7, parentId8, code, ptype, name, bname, refId, refType, type, status, bottomFlag, level, forward, unit, department, staffer, depot, product, duty, checkStaffer) VALUES ('1001-15-03', '1001-15', '1001', '1001-15', '', '', '', '', '', '', '', '1001-15-03', 'A1110000000000000001', '现金-永银-公司总部-现钞', null, 'A1201905221302887670', 0, 0, 0, 1, 2, 1, 0, 0, 0, 0, 0, 0, 0);
