### ISSUE TITLE
退货异常修改

### ISSUE THREAD

**Issue by yanglu-china** [qianlimu/yycoin#903]
1.退款端口未扣减在途数量
[退货.xlsx](https://github.com/qianlimu/yycoin/files/4260455/default.xlsx)
2.base表中virtualPrice不一样
现在这两个字段在库存那边都会用到，在退库的时候只用了成本，也要把虚料金额带上才行
![image](https://user-images.githubusercontent.com/49268537/75427033-bb394500-5980-11ea-90f9-6914860663de.png)

**Comment by yanglu-china** [comment]
![image](https://user-images.githubusercontent.com/49268537/75427192-fd628680-5980-11ea-8406-7f9558f5581c.png)

**Comment by kingofhawks** [comment]
YL2002240911653905429
YL2002241035653906178

**Comment by kingofhawks** [comment]
select sum(b.outamount) from t_center_outback a left join
        t_center_outback_product b on a.transportNo = b.transportno
        where a.status in ('1','2','3','4','6') and (b.complete is null or LENGTH(b.complete) = 0)
        and b.fullid =#fullId#
        and b.productname = #productName#
        and b.outtype = '退货'
