### ISSUE TITLE
增加批量回款认领功能——对接人：冯工

### ISSUE THREAD

**Issue by yanglu-china** [qianlimu/yycoin#927]
1.在“资金管理”中增加菜单项“批量认款”功能
2.导入模板字段：认领类型，客户名/供应商名，回款单号，销售单号，金额，备注
3.认领类型分为两种：销售回款、供应商回款，必填
4.客户名/供应商名：填写客户或供应商名称，必填
5.回款单号：HK开头的单号，此单状态必须为“未认领”
6.销售单号：可填，如不填，则对应回款单金额转为客户预收
7.金额，必填，对应销售单金额或转预收金额，同一回款单号行记录的金额累计必须等于回款单金额
8.备注：可填

**Comment by kingofhawks** [comment]
是否对应“认领（通用）“功能？

**Comment by yanglu-china** [comment]
![image](https://user-images.githubusercontent.com/49268537/77605530-278f7000-6f50-11ea-9558-83e05c7bb6ad.png)

以此为准

**Comment by kingofhawks** [comment]
那在模板里，认领类型给是供应商回款的时候，需要录入金额吗？
周苏东(70907255)  14:54:21
其实就是回款单上默认的金额
前端是默认的，批量的导入还是指定下，防止弄错

**Comment by kingofhawks** [comment]
INSERT INTO uportal.t_center_oamenuitem (id, MENUITEMNAME, URL, PARENTID, BottomFlag, AUTH, indexPos, description) VALUES ('1656', '批量认款', '../bank/batchDrawPayment.jsp', '16', 1, '1602',99, '批量回款认领');

**Comment by kingofhawks** [comment]
1、批量认款，生成的预收收款单的职员，不能设为操作人，要设为客户对应的职员
2、多个HK单对应一个SO单导入会报错

**Comment by yanglu-china** [comment]
![Uploading image.png…]()

**Comment by kingofhawks** [comment]
多个HK单对应同一个销售单勾款现在应该已经支持了

**Comment by kingofhawks** [comment]
![0__JXU$@`8{M8GMVG}FMLGX](https://user-images.githubusercontent.com/45868/79942488-87b6fa80-8499-11ea-8856-a67daef9f4a1.png)
