### ISSUE TITLE
预先分配快递单号功能优化

### ISSUE THREAD

**Issue by yanglu-china** [qianlimu/yycoin#930]
[Uploading 预先分配快递单号功能优化.docx…]()

**Comment by kingofhawks** [comment]
要补一个点：在开票申请生成CK单号时，也要检查原单号是否在已分配清单里，如果在清单里且状态为0，则一并列入中间表，快递单号同原销售单指定的单号，如状态为1且CK单状态为初始，则并入此CK单号，否则单独生成

**Comment by kingofhawks** [comment]
一．	背景
现有部分银行与电商渠道要推行预给快递单号的模式，因此，作业流程及系统功能需做优化调整，基本流程为在生成CK单时检查中间表，并在后续操作中进行分辨操作。
二．	功能修改
1.新建中间表prepackage,包含字段，类型，外部订单号，快递公司，快递单号，状态
2.中间表由帆软导入数据，状态分为0与1，0代表未生成CK单，1代表已生成CK单
3.OA生成CK单前先到此表中确认有无对应的状态为0外部单号（根据fullid到out_import表取oano对应的CITICNO），如有，则在生成CK单时将快递公司与快递单号带入,并将状态更新为1
4.有预生成快递单号的CK单不与其他订单合并
5.类型1代表招商银行直邮，2代表京东，3代表天猫，其他后续再更新
6.在package表中增加type字段，普通CK单为0，其他的取
7.在“商品拣配”的查询条件中增加“发货类型”条件，下拉条件为普通CK单，招行直邮CK单，京东CK单，天猫CK单
8.非普通CK单在发货清单打印时，将快递公司及快递单号打印在页面下方，并同时显示快递单号条形码
9.顺丰面单打印，遇到非普通订单时，报错提示“XXCK单已有外部快递单号”

**Comment by kingofhawks** [comment]
那个预给快递单号的需求里，有个在出库单上打印快递单号的条形码，编码规则用code128b

**Comment by kingofhawks** [comment]
CK202004011454437327

**Comment by kingofhawks** [comment]
在拣配环节的查询条件上可以加个查询条件“预配号类型”
