### ISSUE TITLE
OA-发货管理-商务拣配优化——对接人：冯工

### ISSUE THREAD

**Issue by yanglu-china** [qianlimu/yycoin#942]
OA-发货管理-商务拣配，收货地址的现规则是后六位一样会合并为同一个CK单发货，需要调整为：当客户名称为【拍卖客户】和【国华拍卖】，不适用此规则，仍需分开发货
当客户为【永银天猫旗舰店-有赞】，【国华天猫旗舰店-有赞】，【国华天猫旗舰店-零售】，【永银京东旗舰店-零售】，【永银京东旗舰店-线上】，【国华京东旗舰店-线上】时，也不适用此规则，仍需分开发货

**Comment by kingofhawks** [comment]
还需要新增客户：中金国华-京东；中金国华-天猫；永银天猫旗舰店-线上；永银京东旗舰店-有赞；钱币交易部-京东；国华天猫旗舰店-线上；国华京东旗舰店-有赞；国华京东旗舰店-零售

**Comment by yanglu-china** [comment]
同一个客户的【收货人，手机号，发货方式和地址后六位】信息一致，仍参照之前逻辑并单发货，针对相同信息的不同客户，且客户在以上特殊客户名单中，仍需要分开发货

**Comment by kingofhawks** [comment]
INSERT INTO uportal.t_center_customer_main (id, code, name, simpleName, type, provinceId, cityId, areaId, address, sellType, protype, protype2, qqtype, rtype, fromType, introducer, industry, historySales, salesAmount, creditLevelId, creditVal, creditUpdateTime, contactTimes, lastContactTime, status, ostatus, createrId, createTime, logTime, reserve1, reserve2, reserve3, reserve4, reserve5, reserve6, reserve7, reserve8, reserve9, reserve10, hasNew, checkStatus, checks, refCorpCustId, refDepartCustId, formerCust) VALUES ('241188116', 'A1201509161141188117', '钱币交易部-京东', '钱币交易部-京东', 2, '320000', '320100', '320101', '', 0, 0, 0, 1, 1, 99, '', 1, 0, 0, '90000000000000000001', 30, 0, 0, '', 1, 0, '20158225', '2015-09-16 11:57:21', '2015-09-16 11:57:21', '', '', '', '', '', '', '', '', '', '', 0, 0, '', '', '241188116', '');
INSERT INTO uportal.t_center_customer_main (id, code, name, simpleName, type, provinceId, cityId, areaId, address, sellType, protype, protype2, qqtype, rtype, fromType, introducer, industry, historySales, salesAmount, creditLevelId, creditVal, creditUpdateTime, contactTimes, lastContactTime, status, ostatus, createrId, createTime, logTime, reserve1, reserve2, reserve3, reserve4, reserve5, reserve6, reserve7, reserve8, reserve9, reserve10, hasNew, checkStatus, checks, refCorpCustId, refDepartCustId, formerCust) VALUES ('588695925', 'A1201711071788695926', '中金国华-天猫', '', 2, '320000', '320100', '110118', '', 0, 0, 0, 0, 0, 0, '', 0, 0, 0, '90000000000000000001', 30, 0, 0, '', 1, 0, '', '2017-11-07 17:41:25', '2019-12-31 15:39:41', '无', '', '', '', '', '', '', '', '', '', 0, 0, '朱恒', '', '', '');
INSERT INTO uportal.t_center_customer_main (id, code, name, simpleName, type, provinceId, cityId, areaId, address, sellType, protype, protype2, qqtype, rtype, fromType, introducer, industry, historySales, salesAmount, creditLevelId, creditVal, creditUpdateTime, contactTimes, lastContactTime, status, ostatus, createrId, createTime, logTime, reserve1, reserve2, reserve3, reserve4, reserve5, reserve6, reserve7, reserve8, reserve9, reserve10, hasNew, checkStatus, checks, refCorpCustId, refDepartCustId, formerCust) VALUES ('588695927', 'A1201711071788695928', '中金国华-京东', '', 2, '320000', '320100', '110118', '', 0, 0, 0, 0, 0, 0, '', 0, 0, 0, '90000000000000000001', 30, 0, 0, '', 1, 0, '', '2017-11-07 17:41:25', '2017-11-07 17:41:25', '', '', '', '', '', '', '', '', '', '', 0, 0, '', '', '', '');
INSERT INTO uportal.t_center_customer_main (id, code, name, simpleName, type, provinceId, cityId, areaId, address, sellType, protype, protype2, qqtype, rtype, fromType, introducer, industry, historySales, salesAmount, creditLevelId, creditVal, creditUpdateTime, contactTimes, lastContactTime, status, ostatus, createrId, createTime, logTime, reserve1, reserve2, reserve3, reserve4, reserve5, reserve6, reserve7, reserve8, reserve9, reserve10, hasNew, checkStatus, checks, refCorpCustId, refDepartCustId, formerCust) VALUES ('607296916', 'A1201803291107296917', '拍卖客户', '', 2, '130000', '130200', '000011', '', 0, 0, 0, 0, 0, 0, '', 0, 0, 0, '90000000000000000001', 30, 0, 0, '', 1, 0, '', '2018-03-29 11:50:02', '2018-03-29 11:50:02', 'XX', '', '', '', '', '', '', '', '', '', 0, 0, '', '', '', '');
INSERT INTO uportal.t_center_customer_main (id, code, name, simpleName, type, provinceId, cityId, areaId, address, sellType, protype, protype2, qqtype, rtype, fromType, introducer, industry, historySales, salesAmount, creditLevelId, creditVal, creditUpdateTime, contactTimes, lastContactTime, status, ostatus, createrId, createTime, logTime, reserve1, reserve2, reserve3, reserve4, reserve5, reserve6, reserve7, reserve8, reserve9, reserve10, hasNew, checkStatus, checks, refCorpCustId, refDepartCustId, formerCust) VALUES ('651826185', 'A1201903071551826186', '永银天猫旗舰店-有赞', '', 2, '320000', '320100', '110118', '', 0, 0, 0, 0, 0, 0, '', 0, 0, 0, '90000000000000000001', 30, 0, 0, '', 1, 0, '', '2019-03-07 15:07:57', '2019-03-07 15:07:57', '', '', '', '', '', '', '', '', '', '', 0, 0, '', '', '', '');
INSERT INTO uportal.t_center_customer_main (id, code, name, simpleName, type, provinceId, cityId, areaId, address, sellType, protype, protype2, qqtype, rtype, fromType, introducer, industry, historySales, salesAmount, creditLevelId, creditVal, creditUpdateTime, contactTimes, lastContactTime, status, ostatus, createrId, createTime, logTime, reserve1, reserve2, reserve3, reserve4, reserve5, reserve6, reserve7, reserve8, reserve9, reserve10, hasNew, checkStatus, checks, refCorpCustId, refDepartCustId, formerCust) VALUES ('651826187', 'A1201903071551826188', '国华天猫旗舰店-零售', '', 2, '320000', '320100', '110118', '', 0, 0, 0, 0, 0, 0, '', 0, 0, 0, '90000000000000000001', 30, 0, 0, '', 1, 0, '', '2019-03-07 15:07:57', '2019-03-07 15:07:57', '国华天猫', '线下', '', '', '', '', '', '', '', '', 0, 0, '', '', '', '');
INSERT INTO uportal.t_center_customer_main (id, code, name, simpleName, type, provinceId, cityId, areaId, address, sellType, protype, protype2, qqtype, rtype, fromType, introducer, industry, historySales, salesAmount, creditLevelId, creditVal, creditUpdateTime, contactTimes, lastContactTime, status, ostatus, createrId, createTime, logTime, reserve1, reserve2, reserve3, reserve4, reserve5, reserve6, reserve7, reserve8, reserve9, reserve10, hasNew, checkStatus, checks, refCorpCustId, refDepartCustId, formerCust) VALUES ('651826189', 'A1201903071551826190', '国华天猫旗舰店-有赞', '', 2, '320000', '320100', '110118', '', 0, 0, 0, 0, 0, 0, '', 0, 0, 0, '90000000000000000001', 30, 0, 0, '', 1, 0, '', '2019-03-07 15:07:57', '2019-03-07 15:07:57', '', '', '', '', '', '', '', '', '', '', 0, 0, '', '', '', '');
INSERT INTO uportal.t_center_customer_main (id, code, name, simpleName, type, provinceId, cityId, areaId, address, sellType, protype, protype2, qqtype, rtype, fromType, introducer, industry, historySales, salesAmount, creditLevelId, creditVal, creditUpdateTime, contactTimes, lastContactTime, status, ostatus, createrId, createTime, logTime, reserve1, reserve2, reserve3, reserve4, reserve5, reserve6, reserve7, reserve8, reserve9, reserve10, hasNew, checkStatus, checks, refCorpCustId, refDepartCustId, formerCust) VALUES ('651826191', 'A1201903071551826192', '国华京东旗舰店-零售', '', 2, '320000', '320100', '110118', '', 0, 0, 0, 0, 0, 0, '', 0, 0, 0, '90000000000000000001', 30, 0, 0, '', 1, 0, '', '2019-03-07 15:07:57', '2019-03-07 15:07:57', '国华京东', '线下', '', '', '', '', '', '', '', '', 0, 0, '', '', '', '');
INSERT INTO uportal.t_center_customer_main (id, code, name, simpleName, type, provinceId, cityId, areaId, address, sellType, protype, protype2, qqtype, rtype, fromType, introducer, industry, historySales, salesAmount, creditLevelId, creditVal, creditUpdateTime, contactTimes, lastContactTime, status, ostatus, createrId, createTime, logTime, reserve1, reserve2, reserve3, reserve4, reserve5, reserve6, reserve7, reserve8, reserve9, reserve10, hasNew, checkStatus, checks, refCorpCustId, refDepartCustId, formerCust) VALUES ('651826193', 'A1201903071551826194', '国华京东旗舰店-有赞', '', 2, '320000', '320100', '110118', '', 0, 0, 0, 0, 0, 0, '', 0, 0, 0, '90000000000000000001', 30, 0, 0, '', 1, 0, '', '2019-03-07 15:07:57', '2019-03-07 15:07:57', '', '', '', '', '', '', '', '', '', '', 0, 0, '', '', '', '');
INSERT INTO uportal.t_center_customer_main (id, code, name, simpleName, type, provinceId, cityId, areaId, address, sellType, protype, protype2, qqtype, rtype, fromType, introducer, industry, historySales, salesAmount, creditLevelId, creditVal, creditUpdateTime, contactTimes, lastContactTime, status, ostatus, createrId, createTime, logTime, reserve1, reserve2, reserve3, reserve4, reserve5, reserve6, reserve7, reserve8, reserve9, reserve10, hasNew, checkStatus, checks, refCorpCustId, refDepartCustId, formerCust) VALUES ('651826195', 'A1201903071551826196', '永银京东旗舰店-零售', '', 2, '320000', '320100', '110118', '', 0, 0, 0, 0, 0, 0, '', 0, 0, 0, '90000000000000000001', 30, 0, 0, '', 1, 0, '', '2019-03-07 15:07:57', '2019-03-07 15:07:57', '永银京东', '线下', '', '', '', '', '', '', '', '', 0, 0, '', '', '', '');
INSERT INTO uportal.t_center_customer_main (id, code, name, simpleName, type, provinceId, cityId, areaId, address, sellType, protype, protype2, qqtype, rtype, fromType, introducer, industry, historySales, salesAmount, creditLevelId, creditVal, creditUpdateTime, contactTimes, lastContactTime, status, ostatus, createrId, createTime, logTime, reserve1, reserve2, reserve3, reserve4, reserve5, reserve6, reserve7, reserve8, reserve9, reserve10, hasNew, checkStatus, checks, refCorpCustId, refDepartCustId, formerCust) VALUES ('651826197', 'A1201903071551826198', '永银京东旗舰店-有赞', '', 2, '320000', '320100', '110118', '', 0, 0, 0, 0, 0, 0, '', 0, 0, 0, '90000000000000000001', 30, 0, 0, '', 1, 0, '', '2019-03-07 15:07:57', '2019-03-07 15:07:57', '', '', '', '', '', '', '', '', '', '', 0, 0, '', '', '', '');
INSERT INTO uportal.t_center_customer_main (id, code, name, simpleName, type, provinceId, cityId, areaId, address, sellType, protype, protype2, qqtype, rtype, fromType, introducer, industry, historySales, salesAmount, creditLevelId, creditVal, creditUpdateTime, contactTimes, lastContactTime, status, ostatus, createrId, createTime, logTime, reserve1, reserve2, reserve3, reserve4, reserve5, reserve6, reserve7, reserve8, reserve9, reserve10, hasNew, checkStatus, checks, refCorpCustId, refDepartCustId, formerCust) VALUES ('651827562', 'A1201903071551827563', '永银天猫旗舰店-线上', '', 2, '320000', '320100', '110118', '', 0, 0, 0, 0, 0, 0, '', 0, 0, 0, '90000000000000000001', 30, 0, 0, '', 1, 0, '', '2019-03-07 15:20:49', '2019-09-15 10:43:00', '永银天猫', '', '', '', '', '', '', '', '', '', 0, 0, '朱恒', '', '', '');
INSERT INTO uportal.t_center_customer_main (id, code, name, simpleName, type, provinceId, cityId, areaId, address, sellType, protype, protype2, qqtype, rtype, fromType, introducer, industry, historySales, salesAmount, creditLevelId, creditVal, creditUpdateTime, contactTimes, lastContactTime, status, ostatus, createrId, createTime, logTime, reserve1, reserve2, reserve3, reserve4, reserve5, reserve6, reserve7, reserve8, reserve9, reserve10, hasNew, checkStatus, checks, refCorpCustId, refDepartCustId, formerCust) VALUES ('651827564', 'A1201903071551827565', '国华天猫旗舰店-线上', '', 2, '320000', '320100', '110118', '', 0, 0, 0, 0, 0, 0, '', 0, 0, 0, '90000000000000000001', 30, 0, 0, '', 1, 0, '', '2019-03-07 15:20:49', '2019-09-15 10:21:10', '国华天猫', '', '', '', '', '', '', '', '', '', 0, 0, '朱恒', '', '', '');
INSERT INTO uportal.t_center_customer_main (id, code, name, simpleName, type, provinceId, cityId, areaId, address, sellType, protype, protype2, qqtype, rtype, fromType, introducer, industry, historySales, salesAmount, creditLevelId, creditVal, creditUpdateTime, contactTimes, lastContactTime, status, ostatus, createrId, createTime, logTime, reserve1, reserve2, reserve3, reserve4, reserve5, reserve6, reserve7, reserve8, reserve9, reserve10, hasNew, checkStatus, checks, refCorpCustId, refDepartCustId, formerCust) VALUES ('651827566', 'A1201903071551827567', '国华京东旗舰店-线上', '', 2, '320000', '320100', '110118', '', 0, 0, 0, 0, 0, 0, '', 0, 0, 0, '90000000000000000001', 30, 0, 0, '', 1, 0, '', '2019-03-07 15:20:49', '2019-09-15 10:43:35', '国华京东', '', '', '', '', '', '', '', '', '', 0, 0, '朱恒', '', '', '');
INSERT INTO uportal.t_center_customer_main (id, code, name, simpleName, type, provinceId, cityId, areaId, address, sellType, protype, protype2, qqtype, rtype, fromType, introducer, industry, historySales, salesAmount, creditLevelId, creditVal, creditUpdateTime, contactTimes, lastContactTime, status, ostatus, createrId, createTime, logTime, reserve1, reserve2, reserve3, reserve4, reserve5, reserve6, reserve7, reserve8, reserve9, reserve10, hasNew, checkStatus, checks, refCorpCustId, refDepartCustId, formerCust) VALUES ('651827568', 'A1201903071551827569', '永银京东旗舰店-线上', '', 2, '320000', '320100', '110118', '', 0, 0, 0, 0, 0, 0, '', 0, 0, 0, '90000000000000000001', 30, 0, 0, '', 1, 0, '', '2019-03-07 15:20:49', '2019-09-21 10:08:28', '永银京东', '', '', '', '', '', '', '', '', '', 0, 0, '朱恒', '', '', '');
INSERT INTO uportal.t_center_customer_main (id, code, name, simpleName, type, provinceId, cityId, areaId, address, sellType, protype, protype2, qqtype, rtype, fromType, introducer, industry, historySales, salesAmount, creditLevelId, creditVal, creditUpdateTime, contactTimes, lastContactTime, status, ostatus, createrId, createTime, logTime, reserve1, reserve2, reserve3, reserve4, reserve5, reserve6, reserve7, reserve8, reserve9, reserve10, hasNew, checkStatus, checks, refCorpCustId, refDepartCustId, formerCust) VALUES ('690271628', 'A1201912101490271629', '国华拍卖', '', 2, '320000', '320100', '110118', '', 0, 0, 0, 0, 0, 0, '', 0, 0, 0, '90000000000000000001', 30, 0, 0, '', 1, 0, '', '2019-12-10 14:45:40', '2019-12-10 14:45:40', '无', '', '', '', '', '', '', '', '', '', 0, 0, '', '', '', '');
