### ISSUE TITLE
增加销售订单类型“服务订单",在批量入库、增加销售单中——对接人：周总

### ISSUE THREAD

**Issue by yanglu-china** [qianlimu/yycoin#953]
系统：永银
功能：增加销售订单类型“服务订单",在批量入库、增加销售单中，增加此类型，此类订单锁定产品”服务费“，不检查扣减库存，不取结算价，取消结算价不为0的检查，成本价与结算价均设为销售价，生成凭证为  借：应收账款     贷:主营业务收入

**Comment by kingofhawks** [comment]
YZ0422300 服务费,这个产品选不到
