### ISSUE TITLE
权限项“库存管理“根据权限项”查询销售实际成本“项控制——对接人：周总——优先处理

### ISSUE THREAD

**Issue by yanglu-china** [qianlimu/yycoin#963]
1.增加权限项“库存管理“，此权限控制可显示  库存管理目录，无此权限则不显示库存管理目录 
2.根据权限项”查询销售实际成本“项控制，如无授权，则在 库存管理 中仓库明细商品的成本价不显示

**Comment by yanglu-china** [comment]
1.在”报销管理“权限目录下增加一个权限项”查看中收激励明细“，授权后才可显示“报销管理”目录下的“中收激励申请统计”菜单
2.关闭“报销管理”目录下的“银行业务部层级关系导入”菜单

**Comment by 39189058** [comment]
1.增加权限项“库存管理“，此权限控制可显示 库存管理目录，无此权限则不显示库存管理目录
按周总需求，以上暂时不动。
其余已更新
